******************************************************************
*  COPYBOOK  : GOAZC001
*  KIND      : COMMAREA
*  COVERAGE  : Owners and Contractors Protective Liability (OC)
*  STATE     : AZ
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-OAZ-REQUEST-ID        PIC X(6).
     03 CA-OAZ-RETURN-CODE       PIC 9(2).
     03 CA-OAZ-POLICY-NUM        PIC 9(10).
     03 CA-OAZ-CUSTOMER-NUM      PIC 9(10).

          03 CA-OAZ-ISSUE-DATE                PIC X(10).
          03 CA-OAZ-EXPIRY-DATE               PIC X(10).
          03 CA-OAZ-LASTCHANGED               PIC X(26).
          03 CA-OAZ-BROKERID                  PIC 9(10).
          03 CA-OAZ-BROKERSREF                PIC X(10).
          03 CA-OAZ-PAYMENT                   PIC 9(6).
          03 CA-OAZ-CONTRACT-VALUE            PIC 9(9).
          03 CA-OAZ-PROJECT-DURATION-MOS      PIC 9(3).
          03 CA-OAZ-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-OAZ-BASE-RATE                 PIC 9(4)V9(4).
