******************************************************************
*  COPYBOOK  : GOCTP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Owners and Contractors Protective Liability (OC)
*  STATE     : CT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-OCT-POLICY.

          03 DB2-OCT-ISSUE-DATE               PIC X(10).
          03 DB2-OCT-EXPIRY-DATE              PIC X(10).
          03 DB2-OCT-LASTCHANGED              PIC X(26).
          03 DB2-OCT-BROKERID                 PIC 9(10).
          03 DB2-OCT-BROKERSREF               PIC X(10).
          03 DB2-OCT-PAYMENT                  PIC 9(6).
          03 DB2-OCT-CONTRACT-VALUE           PIC 9(9).
          03 DB2-OCT-PROJECT-DURATION-MOS     PIC 9(3).
          03 DB2-OCT-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-OCT-BASE-RATE                PIC 9(4)V9(4).
