******************************************************************
*  COPYBOOK  : GODCP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Owners and Contractors Protective Liability (OC)
*  STATE     : DC
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-ODC-POLICY.

          03 DB2-ODC-ISSUE-DATE               PIC X(10).
          03 DB2-ODC-EXPIRY-DATE              PIC X(10).
          03 DB2-ODC-LASTCHANGED              PIC X(26).
          03 DB2-ODC-BROKERID                 PIC 9(10).
          03 DB2-ODC-BROKERSREF               PIC X(10).
          03 DB2-ODC-PAYMENT                  PIC 9(6).
          03 DB2-ODC-CONTRACT-VALUE           PIC 9(9).
          03 DB2-ODC-PROJECT-DURATION-MOS     PIC 9(3).
          03 DB2-ODC-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-ODC-BASE-RATE                PIC 9(4)V9(4).
