******************************************************************
*  COPYBOOK  : GODEP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Owners and Contractors Protective Liability (OC)
*  STATE     : DE
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-ODE-POLICY.

          03 DB2-ODE-ISSUE-DATE               PIC X(10).
          03 DB2-ODE-EXPIRY-DATE              PIC X(10).
          03 DB2-ODE-LASTCHANGED              PIC X(26).
          03 DB2-ODE-BROKERID                 PIC 9(10).
          03 DB2-ODE-BROKERSREF               PIC X(10).
          03 DB2-ODE-PAYMENT                  PIC 9(6).
          03 DB2-ODE-CONTRACT-VALUE           PIC 9(9).
          03 DB2-ODE-PROJECT-DURATION-MOS     PIC 9(3).
          03 DB2-ODE-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-ODE-BASE-RATE                PIC 9(4)V9(4).
