******************************************************************
*  COPYBOOK  : GOFLC001
*  KIND      : COMMAREA
*  COVERAGE  : Owners and Contractors Protective Liability (OC)
*  STATE     : FL
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-OFL-REQUEST-ID        PIC X(6).
     03 CA-OFL-RETURN-CODE       PIC 9(2).
     03 CA-OFL-POLICY-NUM        PIC 9(10).
     03 CA-OFL-CUSTOMER-NUM      PIC 9(10).

          03 CA-OFL-ISSUE-DATE                PIC X(10).
          03 CA-OFL-EXPIRY-DATE               PIC X(10).
          03 CA-OFL-LASTCHANGED               PIC X(26).
          03 CA-OFL-BROKERID                  PIC 9(10).
          03 CA-OFL-BROKERSREF                PIC X(10).
          03 CA-OFL-PAYMENT                   PIC 9(6).
          03 CA-OFL-CONTRACT-VALUE            PIC 9(9).
          03 CA-OFL-PROJECT-DURATION-MOS      PIC 9(3).
          03 CA-OFL-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-OFL-BASE-RATE                 PIC 9(4)V9(4).
