******************************************************************
*  COPYBOOK  : GOFLP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Owners and Contractors Protective Liability (OC)
*  STATE     : FL
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-OFL-POLICY.

          03 DB2-OFL-ISSUE-DATE               PIC X(10).
          03 DB2-OFL-EXPIRY-DATE              PIC X(10).
          03 DB2-OFL-LASTCHANGED              PIC X(26).
          03 DB2-OFL-BROKERID                 PIC 9(10).
          03 DB2-OFL-BROKERSREF               PIC X(10).
          03 DB2-OFL-PAYMENT                  PIC 9(6).
          03 DB2-OFL-CONTRACT-VALUE           PIC 9(9).
          03 DB2-OFL-PROJECT-DURATION-MOS     PIC 9(3).
          03 DB2-OFL-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-OFL-BASE-RATE                PIC 9(4)V9(4).
