******************************************************************
*  COPYBOOK  : GOHIP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Owners and Contractors Protective Liability (OC)
*  STATE     : HI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-OHI-POLICY.

          03 DB2-OHI-ISSUE-DATE               PIC X(10).
          03 DB2-OHI-EXPIRY-DATE              PIC X(10).
          03 DB2-OHI-LASTCHANGED              PIC X(26).
          03 DB2-OHI-BROKERID                 PIC 9(10).
          03 DB2-OHI-BROKERSREF               PIC X(10).
          03 DB2-OHI-PAYMENT                  PIC 9(6).
          03 DB2-OHI-CONTRACT-VALUE           PIC 9(9).
          03 DB2-OHI-PROJECT-DURATION-MOS     PIC 9(3).
          03 DB2-OHI-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-OHI-BASE-RATE                PIC 9(4)V9(4).
