******************************************************************
*  COPYBOOK  : GOIAC001
*  KIND      : COMMAREA
*  COVERAGE  : Owners and Contractors Protective Liability (OC)
*  STATE     : IA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-OIA-REQUEST-ID        PIC X(6).
     03 CA-OIA-RETURN-CODE       PIC 9(2).
     03 CA-OIA-POLICY-NUM        PIC 9(10).
     03 CA-OIA-CUSTOMER-NUM      PIC 9(10).

          03 CA-OIA-ISSUE-DATE                PIC X(10).
          03 CA-OIA-EXPIRY-DATE               PIC X(10).
          03 CA-OIA-LASTCHANGED               PIC X(26).
          03 CA-OIA-BROKERID                  PIC 9(10).
          03 CA-OIA-BROKERSREF                PIC X(10).
          03 CA-OIA-PAYMENT                   PIC 9(6).
          03 CA-OIA-CONTRACT-VALUE            PIC 9(9).
          03 CA-OIA-PROJECT-DURATION-MOS      PIC 9(3).
          03 CA-OIA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-OIA-BASE-RATE                 PIC 9(4)V9(4).
