******************************************************************
*  COPYBOOK  : GOILP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Owners and Contractors Protective Liability (OC)
*  STATE     : IL
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-OIL-POLICY.

          03 DB2-OIL-ISSUE-DATE               PIC X(10).
          03 DB2-OIL-EXPIRY-DATE              PIC X(10).
          03 DB2-OIL-LASTCHANGED              PIC X(26).
          03 DB2-OIL-BROKERID                 PIC 9(10).
          03 DB2-OIL-BROKERSREF               PIC X(10).
          03 DB2-OIL-PAYMENT                  PIC 9(6).
          03 DB2-OIL-CONTRACT-VALUE           PIC 9(9).
          03 DB2-OIL-PROJECT-DURATION-MOS     PIC 9(3).
          03 DB2-OIL-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-OIL-BASE-RATE                PIC 9(4)V9(4).
