******************************************************************
*  COPYBOOK  : GOINP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Owners and Contractors Protective Liability (OC)
*  STATE     : IN
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-OIN-POLICY.

          03 DB2-OIN-ISSUE-DATE               PIC X(10).
          03 DB2-OIN-EXPIRY-DATE              PIC X(10).
          03 DB2-OIN-LASTCHANGED              PIC X(26).
          03 DB2-OIN-BROKERID                 PIC 9(10).
          03 DB2-OIN-BROKERSREF               PIC X(10).
          03 DB2-OIN-PAYMENT                  PIC 9(6).
          03 DB2-OIN-CONTRACT-VALUE           PIC 9(9).
          03 DB2-OIN-PROJECT-DURATION-MOS     PIC 9(3).
          03 DB2-OIN-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-OIN-BASE-RATE                PIC 9(4)V9(4).
