******************************************************************
*  COPYBOOK  : GOINC001
*  KIND      : COMMAREA
*  COVERAGE  : Owners and Contractors Protective Liability (OC)
*  STATE     : IN
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-OIN-REQUEST-ID        PIC X(6).
     03 CA-OIN-RETURN-CODE       PIC 9(2).
     03 CA-OIN-POLICY-NUM        PIC 9(10).
     03 CA-OIN-CUSTOMER-NUM      PIC 9(10).

          03 CA-OIN-ISSUE-DATE                PIC X(10).
          03 CA-OIN-EXPIRY-DATE               PIC X(10).
          03 CA-OIN-LASTCHANGED               PIC X(26).
          03 CA-OIN-BROKERID                  PIC 9(10).
          03 CA-OIN-BROKERSREF                PIC X(10).
          03 CA-OIN-PAYMENT                   PIC 9(6).
          03 CA-OIN-CONTRACT-VALUE            PIC 9(9).
          03 CA-OIN-PROJECT-DURATION-MOS      PIC 9(3).
          03 CA-OIN-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-OIN-BASE-RATE                 PIC 9(4)V9(4).
