******************************************************************
*  COPYBOOK  : GOMSP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Owners and Contractors Protective Liability (OC)
*  STATE     : MS
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-OMS-POLICY.

          03 DB2-OMS-ISSUE-DATE               PIC X(10).
          03 DB2-OMS-EXPIRY-DATE              PIC X(10).
          03 DB2-OMS-LASTCHANGED              PIC X(26).
          03 DB2-OMS-BROKERID                 PIC 9(10).
          03 DB2-OMS-BROKERSREF               PIC X(10).
          03 DB2-OMS-PAYMENT                  PIC 9(6).
          03 DB2-OMS-CONTRACT-VALUE           PIC 9(9).
          03 DB2-OMS-PROJECT-DURATION-MOS     PIC 9(3).
          03 DB2-OMS-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-OMS-BASE-RATE                PIC 9(4)V9(4).
