******************************************************************
*  COPYBOOK  : GONCP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Owners and Contractors Protective Liability (OC)
*  STATE     : NC
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-ONC-POLICY.

          03 DB2-ONC-ISSUE-DATE               PIC X(10).
          03 DB2-ONC-EXPIRY-DATE              PIC X(10).
          03 DB2-ONC-LASTCHANGED              PIC X(26).
          03 DB2-ONC-BROKERID                 PIC 9(10).
          03 DB2-ONC-BROKERSREF               PIC X(10).
          03 DB2-ONC-PAYMENT                  PIC 9(6).
          03 DB2-ONC-CONTRACT-VALUE           PIC 9(9).
          03 DB2-ONC-PROJECT-DURATION-MOS     PIC 9(3).
          03 DB2-ONC-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-ONC-BASE-RATE                PIC 9(4)V9(4).
