******************************************************************
*  COPYBOOK  : GONDC001
*  KIND      : COMMAREA
*  COVERAGE  : Owners and Contractors Protective Liability (OC)
*  STATE     : ND
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-OND-REQUEST-ID        PIC X(6).
     03 CA-OND-RETURN-CODE       PIC 9(2).
     03 CA-OND-POLICY-NUM        PIC 9(10).
     03 CA-OND-CUSTOMER-NUM      PIC 9(10).

          03 CA-OND-ISSUE-DATE                PIC X(10).
          03 CA-OND-EXPIRY-DATE               PIC X(10).
          03 CA-OND-LASTCHANGED               PIC X(26).
          03 CA-OND-BROKERID                  PIC 9(10).
          03 CA-OND-BROKERSREF                PIC X(10).
          03 CA-OND-PAYMENT                   PIC 9(6).
          03 CA-OND-CONTRACT-VALUE            PIC 9(9).
          03 CA-OND-PROJECT-DURATION-MOS      PIC 9(3).
          03 CA-OND-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-OND-BASE-RATE                 PIC 9(4)V9(4).
