******************************************************************
*  COPYBOOK  : GONHP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Owners and Contractors Protective Liability (OC)
*  STATE     : NH
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-ONH-POLICY.

          03 DB2-ONH-ISSUE-DATE               PIC X(10).
          03 DB2-ONH-EXPIRY-DATE              PIC X(10).
          03 DB2-ONH-LASTCHANGED              PIC X(26).
          03 DB2-ONH-BROKERID                 PIC 9(10).
          03 DB2-ONH-BROKERSREF               PIC X(10).
          03 DB2-ONH-PAYMENT                  PIC 9(6).
          03 DB2-ONH-CONTRACT-VALUE           PIC 9(9).
          03 DB2-ONH-PROJECT-DURATION-MOS     PIC 9(3).
          03 DB2-ONH-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-ONH-BASE-RATE                PIC 9(4)V9(4).
