******************************************************************
*  COPYBOOK  : GONYC001
*  KIND      : COMMAREA
*  COVERAGE  : Owners and Contractors Protective Liability (OC)
*  STATE     : NY
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-ONY-REQUEST-ID        PIC X(6).
     03 CA-ONY-RETURN-CODE       PIC 9(2).
     03 CA-ONY-POLICY-NUM        PIC 9(10).
     03 CA-ONY-CUSTOMER-NUM      PIC 9(10).

          03 CA-ONY-ISSUE-DATE                PIC X(10).
          03 CA-ONY-EXPIRY-DATE               PIC X(10).
          03 CA-ONY-LASTCHANGED               PIC X(26).
          03 CA-ONY-BROKERID                  PIC 9(10).
          03 CA-ONY-BROKERSREF                PIC X(10).
          03 CA-ONY-PAYMENT                   PIC 9(6).
          03 CA-ONY-CONTRACT-VALUE            PIC 9(9).
          03 CA-ONY-PROJECT-DURATION-MOS      PIC 9(3).
          03 CA-ONY-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-ONY-BASE-RATE                 PIC 9(4)V9(4).
