******************************************************************
*  COPYBOOK  : GONYP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Owners and Contractors Protective Liability (OC)
*  STATE     : NY
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-ONY-POLICY.

          03 DB2-ONY-ISSUE-DATE               PIC X(10).
          03 DB2-ONY-EXPIRY-DATE              PIC X(10).
          03 DB2-ONY-LASTCHANGED              PIC X(26).
          03 DB2-ONY-BROKERID                 PIC 9(10).
          03 DB2-ONY-BROKERSREF               PIC X(10).
          03 DB2-ONY-PAYMENT                  PIC 9(6).
          03 DB2-ONY-CONTRACT-VALUE           PIC 9(9).
          03 DB2-ONY-PROJECT-DURATION-MOS     PIC 9(3).
          03 DB2-ONY-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-ONY-BASE-RATE                PIC 9(4)V9(4).
