******************************************************************
*  COPYBOOK  : GOOKC001
*  KIND      : COMMAREA
*  COVERAGE  : Owners and Contractors Protective Liability (OC)
*  STATE     : OK
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-OOK-REQUEST-ID        PIC X(6).
     03 CA-OOK-RETURN-CODE       PIC 9(2).
     03 CA-OOK-POLICY-NUM        PIC 9(10).
     03 CA-OOK-CUSTOMER-NUM      PIC 9(10).

          03 CA-OOK-ISSUE-DATE                PIC X(10).
          03 CA-OOK-EXPIRY-DATE               PIC X(10).
          03 CA-OOK-LASTCHANGED               PIC X(26).
          03 CA-OOK-BROKERID                  PIC 9(10).
          03 CA-OOK-BROKERSREF                PIC X(10).
          03 CA-OOK-PAYMENT                   PIC 9(6).
          03 CA-OOK-CONTRACT-VALUE            PIC 9(9).
          03 CA-OOK-PROJECT-DURATION-MOS      PIC 9(3).
          03 CA-OOK-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-OOK-BASE-RATE                 PIC 9(4)V9(4).
