******************************************************************
*  COPYBOOK  : GOTNP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Owners and Contractors Protective Liability (OC)
*  STATE     : TN
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-OTN-POLICY.

          03 DB2-OTN-ISSUE-DATE               PIC X(10).
          03 DB2-OTN-EXPIRY-DATE              PIC X(10).
          03 DB2-OTN-LASTCHANGED              PIC X(26).
          03 DB2-OTN-BROKERID                 PIC 9(10).
          03 DB2-OTN-BROKERSREF               PIC X(10).
          03 DB2-OTN-PAYMENT                  PIC 9(6).
          03 DB2-OTN-CONTRACT-VALUE           PIC 9(9).
          03 DB2-OTN-PROJECT-DURATION-MOS     PIC 9(3).
          03 DB2-OTN-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-OTN-BASE-RATE                PIC 9(4)V9(4).
