******************************************************************
*  COPYBOOK  : GOTXC001
*  KIND      : COMMAREA
*  COVERAGE  : Owners and Contractors Protective Liability (OC)
*  STATE     : TX
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-OTX-REQUEST-ID        PIC X(6).
     03 CA-OTX-RETURN-CODE       PIC 9(2).
     03 CA-OTX-POLICY-NUM        PIC 9(10).
     03 CA-OTX-CUSTOMER-NUM      PIC 9(10).

          03 CA-OTX-ISSUE-DATE                PIC X(10).
          03 CA-OTX-EXPIRY-DATE               PIC X(10).
          03 CA-OTX-LASTCHANGED               PIC X(26).
          03 CA-OTX-BROKERID                  PIC 9(10).
          03 CA-OTX-BROKERSREF                PIC X(10).
          03 CA-OTX-PAYMENT                   PIC 9(6).
          03 CA-OTX-CONTRACT-VALUE            PIC 9(9).
          03 CA-OTX-PROJECT-DURATION-MOS      PIC 9(3).
          03 CA-OTX-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-OTX-BASE-RATE                 PIC 9(4)V9(4).
