******************************************************************
*  COPYBOOK  : GOVAC001
*  KIND      : COMMAREA
*  COVERAGE  : Owners and Contractors Protective Liability (OC)
*  STATE     : VA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-OVA-REQUEST-ID        PIC X(6).
     03 CA-OVA-RETURN-CODE       PIC 9(2).
     03 CA-OVA-POLICY-NUM        PIC 9(10).
     03 CA-OVA-CUSTOMER-NUM      PIC 9(10).

          03 CA-OVA-ISSUE-DATE                PIC X(10).
          03 CA-OVA-EXPIRY-DATE               PIC X(10).
          03 CA-OVA-LASTCHANGED               PIC X(26).
          03 CA-OVA-BROKERID                  PIC 9(10).
          03 CA-OVA-BROKERSREF                PIC X(10).
          03 CA-OVA-PAYMENT                   PIC 9(6).
          03 CA-OVA-CONTRACT-VALUE            PIC 9(9).
          03 CA-OVA-PROJECT-DURATION-MOS      PIC 9(3).
          03 CA-OVA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-OVA-BASE-RATE                 PIC 9(4)V9(4).
