******************************************************************
*  COPYBOOK  : GOVTC001
*  KIND      : COMMAREA
*  COVERAGE  : Owners and Contractors Protective Liability (OC)
*  STATE     : VT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-OVT-REQUEST-ID        PIC X(6).
     03 CA-OVT-RETURN-CODE       PIC 9(2).
     03 CA-OVT-POLICY-NUM        PIC 9(10).
     03 CA-OVT-CUSTOMER-NUM      PIC 9(10).

          03 CA-OVT-ISSUE-DATE                PIC X(10).
          03 CA-OVT-EXPIRY-DATE               PIC X(10).
          03 CA-OVT-LASTCHANGED               PIC X(26).
          03 CA-OVT-BROKERID                  PIC 9(10).
          03 CA-OVT-BROKERSREF                PIC X(10).
          03 CA-OVT-PAYMENT                   PIC 9(6).
          03 CA-OVT-CONTRACT-VALUE            PIC 9(9).
          03 CA-OVT-PROJECT-DURATION-MOS      PIC 9(3).
          03 CA-OVT-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-OVT-BASE-RATE                 PIC 9(4)V9(4).
