******************************************************************
*  COPYBOOK  : GOWAC001
*  KIND      : COMMAREA
*  COVERAGE  : Owners and Contractors Protective Liability (OC)
*  STATE     : WA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-OWA-REQUEST-ID        PIC X(6).
     03 CA-OWA-RETURN-CODE       PIC 9(2).
     03 CA-OWA-POLICY-NUM        PIC 9(10).
     03 CA-OWA-CUSTOMER-NUM      PIC 9(10).

          03 CA-OWA-ISSUE-DATE                PIC X(10).
          03 CA-OWA-EXPIRY-DATE               PIC X(10).
          03 CA-OWA-LASTCHANGED               PIC X(26).
          03 CA-OWA-BROKERID                  PIC 9(10).
          03 CA-OWA-BROKERSREF                PIC X(10).
          03 CA-OWA-PAYMENT                   PIC 9(6).
          03 CA-OWA-CONTRACT-VALUE            PIC 9(9).
          03 CA-OWA-PROJECT-DURATION-MOS      PIC 9(3).
          03 CA-OWA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-OWA-BASE-RATE                 PIC 9(4)V9(4).
