******************************************************************
*  COPYBOOK  : GOWYP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Owners and Contractors Protective Liability (OC)
*  STATE     : WY
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-OWY-POLICY.

          03 DB2-OWY-ISSUE-DATE               PIC X(10).
          03 DB2-OWY-EXPIRY-DATE              PIC X(10).
          03 DB2-OWY-LASTCHANGED              PIC X(26).
          03 DB2-OWY-BROKERID                 PIC 9(10).
          03 DB2-OWY-BROKERSREF               PIC X(10).
          03 DB2-OWY-PAYMENT                  PIC 9(6).
          03 DB2-OWY-CONTRACT-VALUE           PIC 9(9).
          03 DB2-OWY-PROJECT-DURATION-MOS     PIC 9(3).
          03 DB2-OWY-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-OWY-BASE-RATE                PIC 9(4)V9(4).
