******************************************************************
*  PROGRAM   : GMWYAL01
*  LAYER     : BUSINESS LOGIC
*  OPERATION : ADD
*  COVERAGE  : Medical Payments (MP)
*  STATE     : WY
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGAPOL01.cbl (github.com/cicsdev/cics-genapp): validate
*  the commarea, then LINK to the DB2-access program.
******************************************************************
 IDENTIFICATION DIVISION.
 PROGRAM-ID. GMWYAL01.
 ENVIRONMENT DIVISION.
 CONFIGURATION SECTION.
 DATA DIVISION.
 WORKING-STORAGE SECTION.

  01  WS-HEADER.
     03 WS-EYECATCHER            PIC X(16) VALUE 'GMWYAL01------WS'.
     03 WS-TRANSID               PIC X(4).
     03 WS-TERMID                PIC X(4).
     03 WS-TASKNUM               PIC 9(7).
     03 WS-CALEN                 PIC S9(4) COMP.

 01  WS-COMMAREA-LENGTHS.
     03 WS-CA-HEADER-LEN         PIC S9(4) COMP VALUE +28.

 01  GMWYAD01                    PIC X(8)  VALUE 'GMWYAD01'.

 LINKAGE SECTION.
 01  DFHCOMMAREA.
     COPY GMWYC001.

 PROCEDURE DIVISION.
 MAINLINE SECTION.
     INITIALIZE WS-HEADER.
     MOVE EIBTRNID TO WS-TRANSID.
     MOVE EIBTRMID TO WS-TERMID.
     MOVE EIBTASKN TO WS-TASKNUM.
     MOVE EIBCALEN TO WS-CALEN.

     IF EIBCALEN IS EQUAL TO ZERO
         EXEC CICS ABEND ABCODE('GMWY') NODUMP
         END-EXEC
     END-IF

     IF EIBCALEN IS LESS THAN WS-CA-HEADER-LEN
         MOVE '98' TO CA-RETURN-CODE
         EXEC CICS RETURN END-EXEC
     END-IF

     EXEC CICS LINK PROGRAM(GMWYAD01)
          COMMAREA(DFHCOMMAREA)
          LENGTH(32500)
     END-EXEC.

     EXEC CICS RETURN END-EXEC.

 MAINLINE-EXIT.
     EXIT.
