******************************************************************
*  COPYBOOK  : GHAKC001
*  KIND      : COMMAREA
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : AK
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-HAK-REQUEST-ID        PIC X(6).
     03 CA-HAK-RETURN-CODE       PIC 9(2).
     03 CA-HAK-POLICY-NUM        PIC 9(10).
     03 CA-HAK-CUSTOMER-NUM      PIC 9(10).

          03 CA-HAK-ISSUE-DATE                PIC X(10).
          03 CA-HAK-EXPIRY-DATE               PIC X(10).
          03 CA-HAK-LASTCHANGED               PIC X(26).
          03 CA-HAK-BROKERID                  PIC 9(10).
          03 CA-HAK-BROKERSREF                PIC X(10).
          03 CA-HAK-PAYMENT                   PIC 9(6).
          03 CA-HAK-VEHICLE-COUNT             PIC 9(4).
          03 CA-HAK-HIRED-AUTO-COST           PIC 9(9).
          03 CA-HAK-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-HAK-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-HAK-TERRITORY-CODE            PIC X(3).
