******************************************************************
*  COPYBOOK  : GHALP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : AL
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-HAL-POLICY.

          03 DB2-HAL-ISSUE-DATE               PIC X(10).
          03 DB2-HAL-EXPIRY-DATE              PIC X(10).
          03 DB2-HAL-LASTCHANGED              PIC X(26).
          03 DB2-HAL-BROKERID                 PIC 9(10).
          03 DB2-HAL-BROKERSREF               PIC X(10).
          03 DB2-HAL-PAYMENT                  PIC 9(6).
          03 DB2-HAL-VEHICLE-COUNT            PIC 9(4).
          03 DB2-HAL-HIRED-AUTO-COST          PIC 9(9).
          03 DB2-HAL-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-HAL-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-HAL-TERRITORY-CODE           PIC X(3).
