******************************************************************
*  COPYBOOK  : GHCTP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : CT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-HCT-POLICY.

          03 DB2-HCT-ISSUE-DATE               PIC X(10).
          03 DB2-HCT-EXPIRY-DATE              PIC X(10).
          03 DB2-HCT-LASTCHANGED              PIC X(26).
          03 DB2-HCT-BROKERID                 PIC 9(10).
          03 DB2-HCT-BROKERSREF               PIC X(10).
          03 DB2-HCT-PAYMENT                  PIC 9(6).
          03 DB2-HCT-VEHICLE-COUNT            PIC 9(4).
          03 DB2-HCT-HIRED-AUTO-COST          PIC 9(9).
          03 DB2-HCT-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-HCT-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-HCT-TERRITORY-CODE           PIC X(3).
