******************************************************************
*  COPYBOOK  : GHIDC001
*  KIND      : COMMAREA
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : ID
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-HID-REQUEST-ID        PIC X(6).
     03 CA-HID-RETURN-CODE       PIC 9(2).
     03 CA-HID-POLICY-NUM        PIC 9(10).
     03 CA-HID-CUSTOMER-NUM      PIC 9(10).

          03 CA-HID-ISSUE-DATE                PIC X(10).
          03 CA-HID-EXPIRY-DATE               PIC X(10).
          03 CA-HID-LASTCHANGED               PIC X(26).
          03 CA-HID-BROKERID                  PIC 9(10).
          03 CA-HID-BROKERSREF                PIC X(10).
          03 CA-HID-PAYMENT                   PIC 9(6).
          03 CA-HID-VEHICLE-COUNT             PIC 9(4).
          03 CA-HID-HIRED-AUTO-COST           PIC 9(9).
          03 CA-HID-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-HID-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-HID-TERRITORY-CODE            PIC X(3).
