******************************************************************
*  COPYBOOK  : GHILP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : IL
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-HIL-POLICY.

          03 DB2-HIL-ISSUE-DATE               PIC X(10).
          03 DB2-HIL-EXPIRY-DATE              PIC X(10).
          03 DB2-HIL-LASTCHANGED              PIC X(26).
          03 DB2-HIL-BROKERID                 PIC 9(10).
          03 DB2-HIL-BROKERSREF               PIC X(10).
          03 DB2-HIL-PAYMENT                  PIC 9(6).
          03 DB2-HIL-VEHICLE-COUNT            PIC 9(4).
          03 DB2-HIL-HIRED-AUTO-COST          PIC 9(9).
          03 DB2-HIL-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-HIL-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-HIL-TERRITORY-CODE           PIC X(3).
