******************************************************************
*  COPYBOOK  : GHILC001
*  KIND      : COMMAREA
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : IL
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-HIL-REQUEST-ID        PIC X(6).
     03 CA-HIL-RETURN-CODE       PIC 9(2).
     03 CA-HIL-POLICY-NUM        PIC 9(10).
     03 CA-HIL-CUSTOMER-NUM      PIC 9(10).

          03 CA-HIL-ISSUE-DATE                PIC X(10).
          03 CA-HIL-EXPIRY-DATE               PIC X(10).
          03 CA-HIL-LASTCHANGED               PIC X(26).
          03 CA-HIL-BROKERID                  PIC 9(10).
          03 CA-HIL-BROKERSREF                PIC X(10).
          03 CA-HIL-PAYMENT                   PIC 9(6).
          03 CA-HIL-VEHICLE-COUNT             PIC 9(4).
          03 CA-HIL-HIRED-AUTO-COST           PIC 9(9).
          03 CA-HIL-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-HIL-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-HIL-TERRITORY-CODE            PIC X(3).
