******************************************************************
*  COPYBOOK  : GHKSP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : KS
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-HKS-POLICY.

          03 DB2-HKS-ISSUE-DATE               PIC X(10).
          03 DB2-HKS-EXPIRY-DATE              PIC X(10).
          03 DB2-HKS-LASTCHANGED              PIC X(26).
          03 DB2-HKS-BROKERID                 PIC 9(10).
          03 DB2-HKS-BROKERSREF               PIC X(10).
          03 DB2-HKS-PAYMENT                  PIC 9(6).
          03 DB2-HKS-VEHICLE-COUNT            PIC 9(4).
          03 DB2-HKS-HIRED-AUTO-COST          PIC 9(9).
          03 DB2-HKS-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-HKS-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-HKS-TERRITORY-CODE           PIC X(3).
