******************************************************************
*  COPYBOOK  : GHKYP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : KY
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-HKY-POLICY.

          03 DB2-HKY-ISSUE-DATE               PIC X(10).
          03 DB2-HKY-EXPIRY-DATE              PIC X(10).
          03 DB2-HKY-LASTCHANGED              PIC X(26).
          03 DB2-HKY-BROKERID                 PIC 9(10).
          03 DB2-HKY-BROKERSREF               PIC X(10).
          03 DB2-HKY-PAYMENT                  PIC 9(6).
          03 DB2-HKY-VEHICLE-COUNT            PIC 9(4).
          03 DB2-HKY-HIRED-AUTO-COST          PIC 9(9).
          03 DB2-HKY-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-HKY-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-HKY-TERRITORY-CODE           PIC X(3).
