******************************************************************
*  COPYBOOK  : GHKYC001
*  KIND      : COMMAREA
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : KY
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-HKY-REQUEST-ID        PIC X(6).
     03 CA-HKY-RETURN-CODE       PIC 9(2).
     03 CA-HKY-POLICY-NUM        PIC 9(10).
     03 CA-HKY-CUSTOMER-NUM      PIC 9(10).

          03 CA-HKY-ISSUE-DATE                PIC X(10).
          03 CA-HKY-EXPIRY-DATE               PIC X(10).
          03 CA-HKY-LASTCHANGED               PIC X(26).
          03 CA-HKY-BROKERID                  PIC 9(10).
          03 CA-HKY-BROKERSREF                PIC X(10).
          03 CA-HKY-PAYMENT                   PIC 9(6).
          03 CA-HKY-VEHICLE-COUNT             PIC 9(4).
          03 CA-HKY-HIRED-AUTO-COST           PIC 9(9).
          03 CA-HKY-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-HKY-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-HKY-TERRITORY-CODE            PIC X(3).
