******************************************************************
*  COPYBOOK  : GHMAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : MA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-HMA-POLICY.

          03 DB2-HMA-ISSUE-DATE               PIC X(10).
          03 DB2-HMA-EXPIRY-DATE              PIC X(10).
          03 DB2-HMA-LASTCHANGED              PIC X(26).
          03 DB2-HMA-BROKERID                 PIC 9(10).
          03 DB2-HMA-BROKERSREF               PIC X(10).
          03 DB2-HMA-PAYMENT                  PIC 9(6).
          03 DB2-HMA-VEHICLE-COUNT            PIC 9(4).
          03 DB2-HMA-HIRED-AUTO-COST          PIC 9(9).
          03 DB2-HMA-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-HMA-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-HMA-TERRITORY-CODE           PIC X(3).
