******************************************************************
*  COPYBOOK  : GHMAC001
*  KIND      : COMMAREA
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : MA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-HMA-REQUEST-ID        PIC X(6).
     03 CA-HMA-RETURN-CODE       PIC 9(2).
     03 CA-HMA-POLICY-NUM        PIC 9(10).
     03 CA-HMA-CUSTOMER-NUM      PIC 9(10).

          03 CA-HMA-ISSUE-DATE                PIC X(10).
          03 CA-HMA-EXPIRY-DATE               PIC X(10).
          03 CA-HMA-LASTCHANGED               PIC X(26).
          03 CA-HMA-BROKERID                  PIC 9(10).
          03 CA-HMA-BROKERSREF                PIC X(10).
          03 CA-HMA-PAYMENT                   PIC 9(6).
          03 CA-HMA-VEHICLE-COUNT             PIC 9(4).
          03 CA-HMA-HIRED-AUTO-COST           PIC 9(9).
          03 CA-HMA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-HMA-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-HMA-TERRITORY-CODE            PIC X(3).
