******************************************************************
*  COPYBOOK  : GHMIC001
*  KIND      : COMMAREA
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : MI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-HMI-REQUEST-ID        PIC X(6).
     03 CA-HMI-RETURN-CODE       PIC 9(2).
     03 CA-HMI-POLICY-NUM        PIC 9(10).
     03 CA-HMI-CUSTOMER-NUM      PIC 9(10).

          03 CA-HMI-ISSUE-DATE                PIC X(10).
          03 CA-HMI-EXPIRY-DATE               PIC X(10).
          03 CA-HMI-LASTCHANGED               PIC X(26).
          03 CA-HMI-BROKERID                  PIC 9(10).
          03 CA-HMI-BROKERSREF                PIC X(10).
          03 CA-HMI-PAYMENT                   PIC 9(6).
          03 CA-HMI-VEHICLE-COUNT             PIC 9(4).
          03 CA-HMI-HIRED-AUTO-COST           PIC 9(9).
          03 CA-HMI-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-HMI-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-HMI-TERRITORY-CODE            PIC X(3).
