******************************************************************
*  COPYBOOK  : GHMSC001
*  KIND      : COMMAREA
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : MS
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-HMS-REQUEST-ID        PIC X(6).
     03 CA-HMS-RETURN-CODE       PIC 9(2).
     03 CA-HMS-POLICY-NUM        PIC 9(10).
     03 CA-HMS-CUSTOMER-NUM      PIC 9(10).

          03 CA-HMS-ISSUE-DATE                PIC X(10).
          03 CA-HMS-EXPIRY-DATE               PIC X(10).
          03 CA-HMS-LASTCHANGED               PIC X(26).
          03 CA-HMS-BROKERID                  PIC 9(10).
          03 CA-HMS-BROKERSREF                PIC X(10).
          03 CA-HMS-PAYMENT                   PIC 9(6).
          03 CA-HMS-VEHICLE-COUNT             PIC 9(4).
          03 CA-HMS-HIRED-AUTO-COST           PIC 9(9).
          03 CA-HMS-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-HMS-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-HMS-TERRITORY-CODE            PIC X(3).
