******************************************************************
*  COPYBOOK  : GHNDC001
*  KIND      : COMMAREA
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : ND
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-HND-REQUEST-ID        PIC X(6).
     03 CA-HND-RETURN-CODE       PIC 9(2).
     03 CA-HND-POLICY-NUM        PIC 9(10).
     03 CA-HND-CUSTOMER-NUM      PIC 9(10).

          03 CA-HND-ISSUE-DATE                PIC X(10).
          03 CA-HND-EXPIRY-DATE               PIC X(10).
          03 CA-HND-LASTCHANGED               PIC X(26).
          03 CA-HND-BROKERID                  PIC 9(10).
          03 CA-HND-BROKERSREF                PIC X(10).
          03 CA-HND-PAYMENT                   PIC 9(6).
          03 CA-HND-VEHICLE-COUNT             PIC 9(4).
          03 CA-HND-HIRED-AUTO-COST           PIC 9(9).
          03 CA-HND-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-HND-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-HND-TERRITORY-CODE            PIC X(3).
