******************************************************************
*  COPYBOOK  : GHNEC001
*  KIND      : COMMAREA
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : NE
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-HNE-REQUEST-ID        PIC X(6).
     03 CA-HNE-RETURN-CODE       PIC 9(2).
     03 CA-HNE-POLICY-NUM        PIC 9(10).
     03 CA-HNE-CUSTOMER-NUM      PIC 9(10).

          03 CA-HNE-ISSUE-DATE                PIC X(10).
          03 CA-HNE-EXPIRY-DATE               PIC X(10).
          03 CA-HNE-LASTCHANGED               PIC X(26).
          03 CA-HNE-BROKERID                  PIC 9(10).
          03 CA-HNE-BROKERSREF                PIC X(10).
          03 CA-HNE-PAYMENT                   PIC 9(6).
          03 CA-HNE-VEHICLE-COUNT             PIC 9(4).
          03 CA-HNE-HIRED-AUTO-COST           PIC 9(9).
          03 CA-HNE-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-HNE-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-HNE-TERRITORY-CODE            PIC X(3).
