******************************************************************
*  COPYBOOK  : GHNEP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : NE
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-HNE-POLICY.

          03 DB2-HNE-ISSUE-DATE               PIC X(10).
          03 DB2-HNE-EXPIRY-DATE              PIC X(10).
          03 DB2-HNE-LASTCHANGED              PIC X(26).
          03 DB2-HNE-BROKERID                 PIC 9(10).
          03 DB2-HNE-BROKERSREF               PIC X(10).
          03 DB2-HNE-PAYMENT                  PIC 9(6).
          03 DB2-HNE-VEHICLE-COUNT            PIC 9(4).
          03 DB2-HNE-HIRED-AUTO-COST          PIC 9(9).
          03 DB2-HNE-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-HNE-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-HNE-TERRITORY-CODE           PIC X(3).
