******************************************************************
*  COPYBOOK  : GHNJC001
*  KIND      : COMMAREA
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : NJ
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-HNJ-REQUEST-ID        PIC X(6).
     03 CA-HNJ-RETURN-CODE       PIC 9(2).
     03 CA-HNJ-POLICY-NUM        PIC 9(10).
     03 CA-HNJ-CUSTOMER-NUM      PIC 9(10).

          03 CA-HNJ-ISSUE-DATE                PIC X(10).
          03 CA-HNJ-EXPIRY-DATE               PIC X(10).
          03 CA-HNJ-LASTCHANGED               PIC X(26).
          03 CA-HNJ-BROKERID                  PIC 9(10).
          03 CA-HNJ-BROKERSREF                PIC X(10).
          03 CA-HNJ-PAYMENT                   PIC 9(6).
          03 CA-HNJ-VEHICLE-COUNT             PIC 9(4).
          03 CA-HNJ-HIRED-AUTO-COST           PIC 9(9).
          03 CA-HNJ-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-HNJ-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-HNJ-TERRITORY-CODE            PIC X(3).
