******************************************************************
*  COPYBOOK  : GHNVP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : NV
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-HNV-POLICY.

          03 DB2-HNV-ISSUE-DATE               PIC X(10).
          03 DB2-HNV-EXPIRY-DATE              PIC X(10).
          03 DB2-HNV-LASTCHANGED              PIC X(26).
          03 DB2-HNV-BROKERID                 PIC 9(10).
          03 DB2-HNV-BROKERSREF               PIC X(10).
          03 DB2-HNV-PAYMENT                  PIC 9(6).
          03 DB2-HNV-VEHICLE-COUNT            PIC 9(4).
          03 DB2-HNV-HIRED-AUTO-COST          PIC 9(9).
          03 DB2-HNV-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-HNV-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-HNV-TERRITORY-CODE           PIC X(3).
