******************************************************************
*  COPYBOOK  : GHNYP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : NY
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-HNY-POLICY.

          03 DB2-HNY-ISSUE-DATE               PIC X(10).
          03 DB2-HNY-EXPIRY-DATE              PIC X(10).
          03 DB2-HNY-LASTCHANGED              PIC X(26).
          03 DB2-HNY-BROKERID                 PIC 9(10).
          03 DB2-HNY-BROKERSREF               PIC X(10).
          03 DB2-HNY-PAYMENT                  PIC 9(6).
          03 DB2-HNY-VEHICLE-COUNT            PIC 9(4).
          03 DB2-HNY-HIRED-AUTO-COST          PIC 9(9).
          03 DB2-HNY-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-HNY-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-HNY-TERRITORY-CODE           PIC X(3).
