******************************************************************
*  COPYBOOK  : GHNYC001
*  KIND      : COMMAREA
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : NY
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-HNY-REQUEST-ID        PIC X(6).
     03 CA-HNY-RETURN-CODE       PIC 9(2).
     03 CA-HNY-POLICY-NUM        PIC 9(10).
     03 CA-HNY-CUSTOMER-NUM      PIC 9(10).

          03 CA-HNY-ISSUE-DATE                PIC X(10).
          03 CA-HNY-EXPIRY-DATE               PIC X(10).
          03 CA-HNY-LASTCHANGED               PIC X(26).
          03 CA-HNY-BROKERID                  PIC 9(10).
          03 CA-HNY-BROKERSREF                PIC X(10).
          03 CA-HNY-PAYMENT                   PIC 9(6).
          03 CA-HNY-VEHICLE-COUNT             PIC 9(4).
          03 CA-HNY-HIRED-AUTO-COST           PIC 9(9).
          03 CA-HNY-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-HNY-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-HNY-TERRITORY-CODE            PIC X(3).
