******************************************************************
*  COPYBOOK  : GHOHC001
*  KIND      : COMMAREA
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : OH
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-HOH-REQUEST-ID        PIC X(6).
     03 CA-HOH-RETURN-CODE       PIC 9(2).
     03 CA-HOH-POLICY-NUM        PIC 9(10).
     03 CA-HOH-CUSTOMER-NUM      PIC 9(10).

          03 CA-HOH-ISSUE-DATE                PIC X(10).
          03 CA-HOH-EXPIRY-DATE               PIC X(10).
          03 CA-HOH-LASTCHANGED               PIC X(26).
          03 CA-HOH-BROKERID                  PIC 9(10).
          03 CA-HOH-BROKERSREF                PIC X(10).
          03 CA-HOH-PAYMENT                   PIC 9(6).
          03 CA-HOH-VEHICLE-COUNT             PIC 9(4).
          03 CA-HOH-HIRED-AUTO-COST           PIC 9(9).
          03 CA-HOH-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-HOH-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-HOH-TERRITORY-CODE            PIC X(3).
