******************************************************************
*  COPYBOOK  : GHPAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : PA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-HPA-POLICY.

          03 DB2-HPA-ISSUE-DATE               PIC X(10).
          03 DB2-HPA-EXPIRY-DATE              PIC X(10).
          03 DB2-HPA-LASTCHANGED              PIC X(26).
          03 DB2-HPA-BROKERID                 PIC 9(10).
          03 DB2-HPA-BROKERSREF               PIC X(10).
          03 DB2-HPA-PAYMENT                  PIC 9(6).
          03 DB2-HPA-VEHICLE-COUNT            PIC 9(4).
          03 DB2-HPA-HIRED-AUTO-COST          PIC 9(9).
          03 DB2-HPA-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-HPA-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-HPA-TERRITORY-CODE           PIC X(3).
