******************************************************************
*  COPYBOOK  : GHRIP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : RI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-HRI-POLICY.

          03 DB2-HRI-ISSUE-DATE               PIC X(10).
          03 DB2-HRI-EXPIRY-DATE              PIC X(10).
          03 DB2-HRI-LASTCHANGED              PIC X(26).
          03 DB2-HRI-BROKERID                 PIC 9(10).
          03 DB2-HRI-BROKERSREF               PIC X(10).
          03 DB2-HRI-PAYMENT                  PIC 9(6).
          03 DB2-HRI-VEHICLE-COUNT            PIC 9(4).
          03 DB2-HRI-HIRED-AUTO-COST          PIC 9(9).
          03 DB2-HRI-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-HRI-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-HRI-TERRITORY-CODE           PIC X(3).
