******************************************************************
*  COPYBOOK  : GHSCP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : SC
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-HSC-POLICY.

          03 DB2-HSC-ISSUE-DATE               PIC X(10).
          03 DB2-HSC-EXPIRY-DATE              PIC X(10).
          03 DB2-HSC-LASTCHANGED              PIC X(26).
          03 DB2-HSC-BROKERID                 PIC 9(10).
          03 DB2-HSC-BROKERSREF               PIC X(10).
          03 DB2-HSC-PAYMENT                  PIC 9(6).
          03 DB2-HSC-VEHICLE-COUNT            PIC 9(4).
          03 DB2-HSC-HIRED-AUTO-COST          PIC 9(9).
          03 DB2-HSC-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-HSC-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-HSC-TERRITORY-CODE           PIC X(3).
