******************************************************************
*  COPYBOOK  : GHSDC001
*  KIND      : COMMAREA
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : SD
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-HSD-REQUEST-ID        PIC X(6).
     03 CA-HSD-RETURN-CODE       PIC 9(2).
     03 CA-HSD-POLICY-NUM        PIC 9(10).
     03 CA-HSD-CUSTOMER-NUM      PIC 9(10).

          03 CA-HSD-ISSUE-DATE                PIC X(10).
          03 CA-HSD-EXPIRY-DATE               PIC X(10).
          03 CA-HSD-LASTCHANGED               PIC X(26).
          03 CA-HSD-BROKERID                  PIC 9(10).
          03 CA-HSD-BROKERSREF                PIC X(10).
          03 CA-HSD-PAYMENT                   PIC 9(6).
          03 CA-HSD-VEHICLE-COUNT             PIC 9(4).
          03 CA-HSD-HIRED-AUTO-COST           PIC 9(9).
          03 CA-HSD-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-HSD-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-HSD-TERRITORY-CODE            PIC X(3).
