******************************************************************
*  COPYBOOK  : GHSDP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : SD
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-HSD-POLICY.

          03 DB2-HSD-ISSUE-DATE               PIC X(10).
          03 DB2-HSD-EXPIRY-DATE              PIC X(10).
          03 DB2-HSD-LASTCHANGED              PIC X(26).
          03 DB2-HSD-BROKERID                 PIC 9(10).
          03 DB2-HSD-BROKERSREF               PIC X(10).
          03 DB2-HSD-PAYMENT                  PIC 9(6).
          03 DB2-HSD-VEHICLE-COUNT            PIC 9(4).
          03 DB2-HSD-HIRED-AUTO-COST          PIC 9(9).
          03 DB2-HSD-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-HSD-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-HSD-TERRITORY-CODE           PIC X(3).
