******************************************************************
*  COPYBOOK  : GHTXP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : TX
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-HTX-POLICY.

          03 DB2-HTX-ISSUE-DATE               PIC X(10).
          03 DB2-HTX-EXPIRY-DATE              PIC X(10).
          03 DB2-HTX-LASTCHANGED              PIC X(26).
          03 DB2-HTX-BROKERID                 PIC 9(10).
          03 DB2-HTX-BROKERSREF               PIC X(10).
          03 DB2-HTX-PAYMENT                  PIC 9(6).
          03 DB2-HTX-VEHICLE-COUNT            PIC 9(4).
          03 DB2-HTX-HIRED-AUTO-COST          PIC 9(9).
          03 DB2-HTX-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-HTX-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-HTX-TERRITORY-CODE           PIC X(3).
