******************************************************************
*  COPYBOOK  : GHTXC001
*  KIND      : COMMAREA
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : TX
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-HTX-REQUEST-ID        PIC X(6).
     03 CA-HTX-RETURN-CODE       PIC 9(2).
     03 CA-HTX-POLICY-NUM        PIC 9(10).
     03 CA-HTX-CUSTOMER-NUM      PIC 9(10).

          03 CA-HTX-ISSUE-DATE                PIC X(10).
          03 CA-HTX-EXPIRY-DATE               PIC X(10).
          03 CA-HTX-LASTCHANGED               PIC X(26).
          03 CA-HTX-BROKERID                  PIC 9(10).
          03 CA-HTX-BROKERSREF                PIC X(10).
          03 CA-HTX-PAYMENT                   PIC 9(6).
          03 CA-HTX-VEHICLE-COUNT             PIC 9(4).
          03 CA-HTX-HIRED-AUTO-COST           PIC 9(9).
          03 CA-HTX-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-HTX-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-HTX-TERRITORY-CODE            PIC X(3).
