******************************************************************
*  COPYBOOK  : GHUTP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : UT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-HUT-POLICY.

          03 DB2-HUT-ISSUE-DATE               PIC X(10).
          03 DB2-HUT-EXPIRY-DATE              PIC X(10).
          03 DB2-HUT-LASTCHANGED              PIC X(26).
          03 DB2-HUT-BROKERID                 PIC 9(10).
          03 DB2-HUT-BROKERSREF               PIC X(10).
          03 DB2-HUT-PAYMENT                  PIC 9(6).
          03 DB2-HUT-VEHICLE-COUNT            PIC 9(4).
          03 DB2-HUT-HIRED-AUTO-COST          PIC 9(9).
          03 DB2-HUT-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-HUT-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-HUT-TERRITORY-CODE           PIC X(3).
