******************************************************************
*  COPYBOOK  : GHUTC001
*  KIND      : COMMAREA
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : UT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-HUT-REQUEST-ID        PIC X(6).
     03 CA-HUT-RETURN-CODE       PIC 9(2).
     03 CA-HUT-POLICY-NUM        PIC 9(10).
     03 CA-HUT-CUSTOMER-NUM      PIC 9(10).

          03 CA-HUT-ISSUE-DATE                PIC X(10).
          03 CA-HUT-EXPIRY-DATE               PIC X(10).
          03 CA-HUT-LASTCHANGED               PIC X(26).
          03 CA-HUT-BROKERID                  PIC 9(10).
          03 CA-HUT-BROKERSREF                PIC X(10).
          03 CA-HUT-PAYMENT                   PIC 9(6).
          03 CA-HUT-VEHICLE-COUNT             PIC 9(4).
          03 CA-HUT-HIRED-AUTO-COST           PIC 9(9).
          03 CA-HUT-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-HUT-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-HUT-TERRITORY-CODE            PIC X(3).
