******************************************************************
*  COPYBOOK  : GHVTC001
*  KIND      : COMMAREA
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : VT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-HVT-REQUEST-ID        PIC X(6).
     03 CA-HVT-RETURN-CODE       PIC 9(2).
     03 CA-HVT-POLICY-NUM        PIC 9(10).
     03 CA-HVT-CUSTOMER-NUM      PIC 9(10).

          03 CA-HVT-ISSUE-DATE                PIC X(10).
          03 CA-HVT-EXPIRY-DATE               PIC X(10).
          03 CA-HVT-LASTCHANGED               PIC X(26).
          03 CA-HVT-BROKERID                  PIC 9(10).
          03 CA-HVT-BROKERSREF                PIC X(10).
          03 CA-HVT-PAYMENT                   PIC 9(6).
          03 CA-HVT-VEHICLE-COUNT             PIC 9(4).
          03 CA-HVT-HIRED-AUTO-COST           PIC 9(9).
          03 CA-HVT-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-HVT-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-HVT-TERRITORY-CODE            PIC X(3).
