******************************************************************
*  COPYBOOK  : GHWAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : WA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-HWA-POLICY.

          03 DB2-HWA-ISSUE-DATE               PIC X(10).
          03 DB2-HWA-EXPIRY-DATE              PIC X(10).
          03 DB2-HWA-LASTCHANGED              PIC X(26).
          03 DB2-HWA-BROKERID                 PIC 9(10).
          03 DB2-HWA-BROKERSREF               PIC X(10).
          03 DB2-HWA-PAYMENT                  PIC 9(6).
          03 DB2-HWA-VEHICLE-COUNT            PIC 9(4).
          03 DB2-HWA-HIRED-AUTO-COST          PIC 9(9).
          03 DB2-HWA-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-HWA-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-HWA-TERRITORY-CODE           PIC X(3).
