******************************************************************
*  COPYBOOK  : GHWIC001
*  KIND      : COMMAREA
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : WI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-HWI-REQUEST-ID        PIC X(6).
     03 CA-HWI-RETURN-CODE       PIC 9(2).
     03 CA-HWI-POLICY-NUM        PIC 9(10).
     03 CA-HWI-CUSTOMER-NUM      PIC 9(10).

          03 CA-HWI-ISSUE-DATE                PIC X(10).
          03 CA-HWI-EXPIRY-DATE               PIC X(10).
          03 CA-HWI-LASTCHANGED               PIC X(26).
          03 CA-HWI-BROKERID                  PIC 9(10).
          03 CA-HWI-BROKERSREF                PIC X(10).
          03 CA-HWI-PAYMENT                   PIC 9(6).
          03 CA-HWI-VEHICLE-COUNT             PIC 9(4).
          03 CA-HWI-HIRED-AUTO-COST           PIC 9(9).
          03 CA-HWI-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-HWI-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-HWI-TERRITORY-CODE            PIC X(3).
