******************************************************************
*  COPYBOOK  : GHWVP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : WV
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-HWV-POLICY.

          03 DB2-HWV-ISSUE-DATE               PIC X(10).
          03 DB2-HWV-EXPIRY-DATE              PIC X(10).
          03 DB2-HWV-LASTCHANGED              PIC X(26).
          03 DB2-HWV-BROKERID                 PIC 9(10).
          03 DB2-HWV-BROKERSREF               PIC X(10).
          03 DB2-HWV-PAYMENT                  PIC 9(6).
          03 DB2-HWV-VEHICLE-COUNT            PIC 9(4).
          03 DB2-HWV-HIRED-AUTO-COST          PIC 9(9).
          03 DB2-HWV-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-HWV-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-HWV-TERRITORY-CODE           PIC X(3).
