******************************************************************
*  COPYBOOK  : GHWYP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Hired and Non-Owned Auto Liability (HN)
*  STATE     : WY
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-HWY-POLICY.

          03 DB2-HWY-ISSUE-DATE               PIC X(10).
          03 DB2-HWY-EXPIRY-DATE              PIC X(10).
          03 DB2-HWY-LASTCHANGED              PIC X(26).
          03 DB2-HWY-BROKERID                 PIC 9(10).
          03 DB2-HWY-BROKERSREF               PIC X(10).
          03 DB2-HWY-PAYMENT                  PIC 9(6).
          03 DB2-HWY-VEHICLE-COUNT            PIC 9(4).
          03 DB2-HWY-HIRED-AUTO-COST          PIC 9(9).
          03 DB2-HWY-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-HWY-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-HWY-TERRITORY-CODE           PIC X(3).
