******************************************************************
*  COPYBOOK  : GFAKC001
*  KIND      : COMMAREA
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : AK
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-FAK-REQUEST-ID        PIC X(6).
     03 CA-FAK-RETURN-CODE       PIC 9(2).
     03 CA-FAK-POLICY-NUM        PIC 9(10).
     03 CA-FAK-CUSTOMER-NUM      PIC 9(10).

          03 CA-FAK-ISSUE-DATE                PIC X(10).
          03 CA-FAK-EXPIRY-DATE               PIC X(10).
          03 CA-FAK-LASTCHANGED               PIC X(26).
          03 CA-FAK-BROKERID                  PIC 9(10).
          03 CA-FAK-BROKERSREF                PIC X(10).
          03 CA-FAK-PAYMENT                   PIC 9(6).
          03 CA-FAK-LIMIT-PER-PREMISES        PIC 9(9).
          03 CA-FAK-RENTED-SQFT               PIC 9(7).
          03 CA-FAK-CONSTRUCTION-TYPE         PIC X(2).
          03 CA-FAK-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-FAK-TERRITORY-CODE            PIC X(3).
