******************************************************************
*  COPYBOOK  : GFCAC001
*  KIND      : COMMAREA
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : CA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-FCA-REQUEST-ID        PIC X(6).
     03 CA-FCA-RETURN-CODE       PIC 9(2).
     03 CA-FCA-POLICY-NUM        PIC 9(10).
     03 CA-FCA-CUSTOMER-NUM      PIC 9(10).

          03 CA-FCA-ISSUE-DATE                PIC X(10).
          03 CA-FCA-EXPIRY-DATE               PIC X(10).
          03 CA-FCA-LASTCHANGED               PIC X(26).
          03 CA-FCA-BROKERID                  PIC 9(10).
          03 CA-FCA-BROKERSREF                PIC X(10).
          03 CA-FCA-PAYMENT                   PIC 9(6).
          03 CA-FCA-LIMIT-PER-PREMISES        PIC 9(9).
          03 CA-FCA-RENTED-SQFT               PIC 9(7).
          03 CA-FCA-CONSTRUCTION-TYPE         PIC X(2).
          03 CA-FCA-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-FCA-TERRITORY-CODE            PIC X(3).
