******************************************************************
*  COPYBOOK  : GFCOC001
*  KIND      : COMMAREA
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : CO
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-FCO-REQUEST-ID        PIC X(6).
     03 CA-FCO-RETURN-CODE       PIC 9(2).
     03 CA-FCO-POLICY-NUM        PIC 9(10).
     03 CA-FCO-CUSTOMER-NUM      PIC 9(10).

          03 CA-FCO-ISSUE-DATE                PIC X(10).
          03 CA-FCO-EXPIRY-DATE               PIC X(10).
          03 CA-FCO-LASTCHANGED               PIC X(26).
          03 CA-FCO-BROKERID                  PIC 9(10).
          03 CA-FCO-BROKERSREF                PIC X(10).
          03 CA-FCO-PAYMENT                   PIC 9(6).
          03 CA-FCO-LIMIT-PER-PREMISES        PIC 9(9).
          03 CA-FCO-RENTED-SQFT               PIC 9(7).
          03 CA-FCO-CONSTRUCTION-TYPE         PIC X(2).
          03 CA-FCO-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-FCO-TERRITORY-CODE            PIC X(3).
