******************************************************************
*  COPYBOOK  : GFDCC001
*  KIND      : COMMAREA
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : DC
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-FDC-REQUEST-ID        PIC X(6).
     03 CA-FDC-RETURN-CODE       PIC 9(2).
     03 CA-FDC-POLICY-NUM        PIC 9(10).
     03 CA-FDC-CUSTOMER-NUM      PIC 9(10).

          03 CA-FDC-ISSUE-DATE                PIC X(10).
          03 CA-FDC-EXPIRY-DATE               PIC X(10).
          03 CA-FDC-LASTCHANGED               PIC X(26).
          03 CA-FDC-BROKERID                  PIC 9(10).
          03 CA-FDC-BROKERSREF                PIC X(10).
          03 CA-FDC-PAYMENT                   PIC 9(6).
          03 CA-FDC-LIMIT-PER-PREMISES        PIC 9(9).
          03 CA-FDC-RENTED-SQFT               PIC 9(7).
          03 CA-FDC-CONSTRUCTION-TYPE         PIC X(2).
          03 CA-FDC-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-FDC-TERRITORY-CODE            PIC X(3).
