******************************************************************
*  COPYBOOK  : GFDEC001
*  KIND      : COMMAREA
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : DE
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-FDE-REQUEST-ID        PIC X(6).
     03 CA-FDE-RETURN-CODE       PIC 9(2).
     03 CA-FDE-POLICY-NUM        PIC 9(10).
     03 CA-FDE-CUSTOMER-NUM      PIC 9(10).

          03 CA-FDE-ISSUE-DATE                PIC X(10).
          03 CA-FDE-EXPIRY-DATE               PIC X(10).
          03 CA-FDE-LASTCHANGED               PIC X(26).
          03 CA-FDE-BROKERID                  PIC 9(10).
          03 CA-FDE-BROKERSREF                PIC X(10).
          03 CA-FDE-PAYMENT                   PIC 9(6).
          03 CA-FDE-LIMIT-PER-PREMISES        PIC 9(9).
          03 CA-FDE-RENTED-SQFT               PIC 9(7).
          03 CA-FDE-CONSTRUCTION-TYPE         PIC X(2).
          03 CA-FDE-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-FDE-TERRITORY-CODE            PIC X(3).
