******************************************************************
*  COPYBOOK  : GFFLC001
*  KIND      : COMMAREA
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : FL
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-FFL-REQUEST-ID        PIC X(6).
     03 CA-FFL-RETURN-CODE       PIC 9(2).
     03 CA-FFL-POLICY-NUM        PIC 9(10).
     03 CA-FFL-CUSTOMER-NUM      PIC 9(10).

          03 CA-FFL-ISSUE-DATE                PIC X(10).
          03 CA-FFL-EXPIRY-DATE               PIC X(10).
          03 CA-FFL-LASTCHANGED               PIC X(26).
          03 CA-FFL-BROKERID                  PIC 9(10).
          03 CA-FFL-BROKERSREF                PIC X(10).
          03 CA-FFL-PAYMENT                   PIC 9(6).
          03 CA-FFL-LIMIT-PER-PREMISES        PIC 9(9).
          03 CA-FFL-RENTED-SQFT               PIC 9(7).
          03 CA-FFL-CONSTRUCTION-TYPE         PIC X(2).
          03 CA-FFL-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-FFL-TERRITORY-CODE            PIC X(3).
