******************************************************************
*  COPYBOOK  : GFHIP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : HI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-FHI-POLICY.

          03 DB2-FHI-ISSUE-DATE               PIC X(10).
          03 DB2-FHI-EXPIRY-DATE              PIC X(10).
          03 DB2-FHI-LASTCHANGED              PIC X(26).
          03 DB2-FHI-BROKERID                 PIC 9(10).
          03 DB2-FHI-BROKERSREF               PIC X(10).
          03 DB2-FHI-PAYMENT                  PIC 9(6).
          03 DB2-FHI-LIMIT-PER-PREMISES       PIC 9(9).
          03 DB2-FHI-RENTED-SQFT              PIC 9(7).
          03 DB2-FHI-CONSTRUCTION-TYPE        PIC X(2).
          03 DB2-FHI-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-FHI-TERRITORY-CODE           PIC X(3).
