******************************************************************
*  COPYBOOK  : GFHIC001
*  KIND      : COMMAREA
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : HI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-FHI-REQUEST-ID        PIC X(6).
     03 CA-FHI-RETURN-CODE       PIC 9(2).
     03 CA-FHI-POLICY-NUM        PIC 9(10).
     03 CA-FHI-CUSTOMER-NUM      PIC 9(10).

          03 CA-FHI-ISSUE-DATE                PIC X(10).
          03 CA-FHI-EXPIRY-DATE               PIC X(10).
          03 CA-FHI-LASTCHANGED               PIC X(26).
          03 CA-FHI-BROKERID                  PIC 9(10).
          03 CA-FHI-BROKERSREF                PIC X(10).
          03 CA-FHI-PAYMENT                   PIC 9(6).
          03 CA-FHI-LIMIT-PER-PREMISES        PIC 9(9).
          03 CA-FHI-RENTED-SQFT               PIC 9(7).
          03 CA-FHI-CONSTRUCTION-TYPE         PIC X(2).
          03 CA-FHI-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-FHI-TERRITORY-CODE            PIC X(3).
