******************************************************************
*  COPYBOOK  : GFILC001
*  KIND      : COMMAREA
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : IL
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-FIL-REQUEST-ID        PIC X(6).
     03 CA-FIL-RETURN-CODE       PIC 9(2).
     03 CA-FIL-POLICY-NUM        PIC 9(10).
     03 CA-FIL-CUSTOMER-NUM      PIC 9(10).

          03 CA-FIL-ISSUE-DATE                PIC X(10).
          03 CA-FIL-EXPIRY-DATE               PIC X(10).
          03 CA-FIL-LASTCHANGED               PIC X(26).
          03 CA-FIL-BROKERID                  PIC 9(10).
          03 CA-FIL-BROKERSREF                PIC X(10).
          03 CA-FIL-PAYMENT                   PIC 9(6).
          03 CA-FIL-LIMIT-PER-PREMISES        PIC 9(9).
          03 CA-FIL-RENTED-SQFT               PIC 9(7).
          03 CA-FIL-CONSTRUCTION-TYPE         PIC X(2).
          03 CA-FIL-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-FIL-TERRITORY-CODE            PIC X(3).
