******************************************************************
*  COPYBOOK  : GFKYC001
*  KIND      : COMMAREA
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : KY
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-FKY-REQUEST-ID        PIC X(6).
     03 CA-FKY-RETURN-CODE       PIC 9(2).
     03 CA-FKY-POLICY-NUM        PIC 9(10).
     03 CA-FKY-CUSTOMER-NUM      PIC 9(10).

          03 CA-FKY-ISSUE-DATE                PIC X(10).
          03 CA-FKY-EXPIRY-DATE               PIC X(10).
          03 CA-FKY-LASTCHANGED               PIC X(26).
          03 CA-FKY-BROKERID                  PIC 9(10).
          03 CA-FKY-BROKERSREF                PIC X(10).
          03 CA-FKY-PAYMENT                   PIC 9(6).
          03 CA-FKY-LIMIT-PER-PREMISES        PIC 9(9).
          03 CA-FKY-RENTED-SQFT               PIC 9(7).
          03 CA-FKY-CONSTRUCTION-TYPE         PIC X(2).
          03 CA-FKY-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-FKY-TERRITORY-CODE            PIC X(3).
