******************************************************************
*  COPYBOOK  : GFLAC001
*  KIND      : COMMAREA
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : LA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-FLA-REQUEST-ID        PIC X(6).
     03 CA-FLA-RETURN-CODE       PIC 9(2).
     03 CA-FLA-POLICY-NUM        PIC 9(10).
     03 CA-FLA-CUSTOMER-NUM      PIC 9(10).

          03 CA-FLA-ISSUE-DATE                PIC X(10).
          03 CA-FLA-EXPIRY-DATE               PIC X(10).
          03 CA-FLA-LASTCHANGED               PIC X(26).
          03 CA-FLA-BROKERID                  PIC 9(10).
          03 CA-FLA-BROKERSREF                PIC X(10).
          03 CA-FLA-PAYMENT                   PIC 9(6).
          03 CA-FLA-LIMIT-PER-PREMISES        PIC 9(9).
          03 CA-FLA-RENTED-SQFT               PIC 9(7).
          03 CA-FLA-CONSTRUCTION-TYPE         PIC X(2).
          03 CA-FLA-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-FLA-TERRITORY-CODE            PIC X(3).
