******************************************************************
*  COPYBOOK  : GFMAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : MA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-FMA-POLICY.

          03 DB2-FMA-ISSUE-DATE               PIC X(10).
          03 DB2-FMA-EXPIRY-DATE              PIC X(10).
          03 DB2-FMA-LASTCHANGED              PIC X(26).
          03 DB2-FMA-BROKERID                 PIC 9(10).
          03 DB2-FMA-BROKERSREF               PIC X(10).
          03 DB2-FMA-PAYMENT                  PIC 9(6).
          03 DB2-FMA-LIMIT-PER-PREMISES       PIC 9(9).
          03 DB2-FMA-RENTED-SQFT              PIC 9(7).
          03 DB2-FMA-CONSTRUCTION-TYPE        PIC X(2).
          03 DB2-FMA-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-FMA-TERRITORY-CODE           PIC X(3).
