******************************************************************
*  COPYBOOK  : GFMOC001
*  KIND      : COMMAREA
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : MO
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-FMO-REQUEST-ID        PIC X(6).
     03 CA-FMO-RETURN-CODE       PIC 9(2).
     03 CA-FMO-POLICY-NUM        PIC 9(10).
     03 CA-FMO-CUSTOMER-NUM      PIC 9(10).

          03 CA-FMO-ISSUE-DATE                PIC X(10).
          03 CA-FMO-EXPIRY-DATE               PIC X(10).
          03 CA-FMO-LASTCHANGED               PIC X(26).
          03 CA-FMO-BROKERID                  PIC 9(10).
          03 CA-FMO-BROKERSREF                PIC X(10).
          03 CA-FMO-PAYMENT                   PIC 9(6).
          03 CA-FMO-LIMIT-PER-PREMISES        PIC 9(9).
          03 CA-FMO-RENTED-SQFT               PIC 9(7).
          03 CA-FMO-CONSTRUCTION-TYPE         PIC X(2).
          03 CA-FMO-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-FMO-TERRITORY-CODE            PIC X(3).
