******************************************************************
*  COPYBOOK  : GFMOP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : MO
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-FMO-POLICY.

          03 DB2-FMO-ISSUE-DATE               PIC X(10).
          03 DB2-FMO-EXPIRY-DATE              PIC X(10).
          03 DB2-FMO-LASTCHANGED              PIC X(26).
          03 DB2-FMO-BROKERID                 PIC 9(10).
          03 DB2-FMO-BROKERSREF               PIC X(10).
          03 DB2-FMO-PAYMENT                  PIC 9(6).
          03 DB2-FMO-LIMIT-PER-PREMISES       PIC 9(9).
          03 DB2-FMO-RENTED-SQFT              PIC 9(7).
          03 DB2-FMO-CONSTRUCTION-TYPE        PIC X(2).
          03 DB2-FMO-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-FMO-TERRITORY-CODE           PIC X(3).
