******************************************************************
*  COPYBOOK  : GFMTC001
*  KIND      : COMMAREA
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : MT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-FMT-REQUEST-ID        PIC X(6).
     03 CA-FMT-RETURN-CODE       PIC 9(2).
     03 CA-FMT-POLICY-NUM        PIC 9(10).
     03 CA-FMT-CUSTOMER-NUM      PIC 9(10).

          03 CA-FMT-ISSUE-DATE                PIC X(10).
          03 CA-FMT-EXPIRY-DATE               PIC X(10).
          03 CA-FMT-LASTCHANGED               PIC X(26).
          03 CA-FMT-BROKERID                  PIC 9(10).
          03 CA-FMT-BROKERSREF                PIC X(10).
          03 CA-FMT-PAYMENT                   PIC 9(6).
          03 CA-FMT-LIMIT-PER-PREMISES        PIC 9(9).
          03 CA-FMT-RENTED-SQFT               PIC 9(7).
          03 CA-FMT-CONSTRUCTION-TYPE         PIC X(2).
          03 CA-FMT-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-FMT-TERRITORY-CODE            PIC X(3).
