******************************************************************
*  COPYBOOK  : GFMTP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : MT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-FMT-POLICY.

          03 DB2-FMT-ISSUE-DATE               PIC X(10).
          03 DB2-FMT-EXPIRY-DATE              PIC X(10).
          03 DB2-FMT-LASTCHANGED              PIC X(26).
          03 DB2-FMT-BROKERID                 PIC 9(10).
          03 DB2-FMT-BROKERSREF               PIC X(10).
          03 DB2-FMT-PAYMENT                  PIC 9(6).
          03 DB2-FMT-LIMIT-PER-PREMISES       PIC 9(9).
          03 DB2-FMT-RENTED-SQFT              PIC 9(7).
          03 DB2-FMT-CONSTRUCTION-TYPE        PIC X(2).
          03 DB2-FMT-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-FMT-TERRITORY-CODE           PIC X(3).
