******************************************************************
*  COPYBOOK  : GFNCC001
*  KIND      : COMMAREA
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : NC
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-FNC-REQUEST-ID        PIC X(6).
     03 CA-FNC-RETURN-CODE       PIC 9(2).
     03 CA-FNC-POLICY-NUM        PIC 9(10).
     03 CA-FNC-CUSTOMER-NUM      PIC 9(10).

          03 CA-FNC-ISSUE-DATE                PIC X(10).
          03 CA-FNC-EXPIRY-DATE               PIC X(10).
          03 CA-FNC-LASTCHANGED               PIC X(26).
          03 CA-FNC-BROKERID                  PIC 9(10).
          03 CA-FNC-BROKERSREF                PIC X(10).
          03 CA-FNC-PAYMENT                   PIC 9(6).
          03 CA-FNC-LIMIT-PER-PREMISES        PIC 9(9).
          03 CA-FNC-RENTED-SQFT               PIC 9(7).
          03 CA-FNC-CONSTRUCTION-TYPE         PIC X(2).
          03 CA-FNC-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-FNC-TERRITORY-CODE            PIC X(3).
