******************************************************************
*  COPYBOOK  : GFNDP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : ND
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-FND-POLICY.

          03 DB2-FND-ISSUE-DATE               PIC X(10).
          03 DB2-FND-EXPIRY-DATE              PIC X(10).
          03 DB2-FND-LASTCHANGED              PIC X(26).
          03 DB2-FND-BROKERID                 PIC 9(10).
          03 DB2-FND-BROKERSREF               PIC X(10).
          03 DB2-FND-PAYMENT                  PIC 9(6).
          03 DB2-FND-LIMIT-PER-PREMISES       PIC 9(9).
          03 DB2-FND-RENTED-SQFT              PIC 9(7).
          03 DB2-FND-CONSTRUCTION-TYPE        PIC X(2).
          03 DB2-FND-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-FND-TERRITORY-CODE           PIC X(3).
