******************************************************************
*  COPYBOOK  : GFNEP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : NE
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-FNE-POLICY.

          03 DB2-FNE-ISSUE-DATE               PIC X(10).
          03 DB2-FNE-EXPIRY-DATE              PIC X(10).
          03 DB2-FNE-LASTCHANGED              PIC X(26).
          03 DB2-FNE-BROKERID                 PIC 9(10).
          03 DB2-FNE-BROKERSREF               PIC X(10).
          03 DB2-FNE-PAYMENT                  PIC 9(6).
          03 DB2-FNE-LIMIT-PER-PREMISES       PIC 9(9).
          03 DB2-FNE-RENTED-SQFT              PIC 9(7).
          03 DB2-FNE-CONSTRUCTION-TYPE        PIC X(2).
          03 DB2-FNE-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-FNE-TERRITORY-CODE           PIC X(3).
