******************************************************************
*  COPYBOOK  : GFNHC001
*  KIND      : COMMAREA
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : NH
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-FNH-REQUEST-ID        PIC X(6).
     03 CA-FNH-RETURN-CODE       PIC 9(2).
     03 CA-FNH-POLICY-NUM        PIC 9(10).
     03 CA-FNH-CUSTOMER-NUM      PIC 9(10).

          03 CA-FNH-ISSUE-DATE                PIC X(10).
          03 CA-FNH-EXPIRY-DATE               PIC X(10).
          03 CA-FNH-LASTCHANGED               PIC X(26).
          03 CA-FNH-BROKERID                  PIC 9(10).
          03 CA-FNH-BROKERSREF                PIC X(10).
          03 CA-FNH-PAYMENT                   PIC 9(6).
          03 CA-FNH-LIMIT-PER-PREMISES        PIC 9(9).
          03 CA-FNH-RENTED-SQFT               PIC 9(7).
          03 CA-FNH-CONSTRUCTION-TYPE         PIC X(2).
          03 CA-FNH-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-FNH-TERRITORY-CODE            PIC X(3).
