******************************************************************
*  COPYBOOK  : GFNVP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : NV
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-FNV-POLICY.

          03 DB2-FNV-ISSUE-DATE               PIC X(10).
          03 DB2-FNV-EXPIRY-DATE              PIC X(10).
          03 DB2-FNV-LASTCHANGED              PIC X(26).
          03 DB2-FNV-BROKERID                 PIC 9(10).
          03 DB2-FNV-BROKERSREF               PIC X(10).
          03 DB2-FNV-PAYMENT                  PIC 9(6).
          03 DB2-FNV-LIMIT-PER-PREMISES       PIC 9(9).
          03 DB2-FNV-RENTED-SQFT              PIC 9(7).
          03 DB2-FNV-CONSTRUCTION-TYPE        PIC X(2).
          03 DB2-FNV-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-FNV-TERRITORY-CODE           PIC X(3).
