******************************************************************
*  COPYBOOK  : GFOHC001
*  KIND      : COMMAREA
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : OH
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-FOH-REQUEST-ID        PIC X(6).
     03 CA-FOH-RETURN-CODE       PIC 9(2).
     03 CA-FOH-POLICY-NUM        PIC 9(10).
     03 CA-FOH-CUSTOMER-NUM      PIC 9(10).

          03 CA-FOH-ISSUE-DATE                PIC X(10).
          03 CA-FOH-EXPIRY-DATE               PIC X(10).
          03 CA-FOH-LASTCHANGED               PIC X(26).
          03 CA-FOH-BROKERID                  PIC 9(10).
          03 CA-FOH-BROKERSREF                PIC X(10).
          03 CA-FOH-PAYMENT                   PIC 9(6).
          03 CA-FOH-LIMIT-PER-PREMISES        PIC 9(9).
          03 CA-FOH-RENTED-SQFT               PIC 9(7).
          03 CA-FOH-CONSTRUCTION-TYPE         PIC X(2).
          03 CA-FOH-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-FOH-TERRITORY-CODE            PIC X(3).
