******************************************************************
*  COPYBOOK  : GFOKC001
*  KIND      : COMMAREA
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : OK
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-FOK-REQUEST-ID        PIC X(6).
     03 CA-FOK-RETURN-CODE       PIC 9(2).
     03 CA-FOK-POLICY-NUM        PIC 9(10).
     03 CA-FOK-CUSTOMER-NUM      PIC 9(10).

          03 CA-FOK-ISSUE-DATE                PIC X(10).
          03 CA-FOK-EXPIRY-DATE               PIC X(10).
          03 CA-FOK-LASTCHANGED               PIC X(26).
          03 CA-FOK-BROKERID                  PIC 9(10).
          03 CA-FOK-BROKERSREF                PIC X(10).
          03 CA-FOK-PAYMENT                   PIC 9(6).
          03 CA-FOK-LIMIT-PER-PREMISES        PIC 9(9).
          03 CA-FOK-RENTED-SQFT               PIC 9(7).
          03 CA-FOK-CONSTRUCTION-TYPE         PIC X(2).
          03 CA-FOK-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-FOK-TERRITORY-CODE            PIC X(3).
