******************************************************************
*  COPYBOOK  : GFSCP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : SC
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-FSC-POLICY.

          03 DB2-FSC-ISSUE-DATE               PIC X(10).
          03 DB2-FSC-EXPIRY-DATE              PIC X(10).
          03 DB2-FSC-LASTCHANGED              PIC X(26).
          03 DB2-FSC-BROKERID                 PIC 9(10).
          03 DB2-FSC-BROKERSREF               PIC X(10).
          03 DB2-FSC-PAYMENT                  PIC 9(6).
          03 DB2-FSC-LIMIT-PER-PREMISES       PIC 9(9).
          03 DB2-FSC-RENTED-SQFT              PIC 9(7).
          03 DB2-FSC-CONSTRUCTION-TYPE        PIC X(2).
          03 DB2-FSC-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-FSC-TERRITORY-CODE           PIC X(3).
