******************************************************************
*  COPYBOOK  : GFSDC001
*  KIND      : COMMAREA
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : SD
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-FSD-REQUEST-ID        PIC X(6).
     03 CA-FSD-RETURN-CODE       PIC 9(2).
     03 CA-FSD-POLICY-NUM        PIC 9(10).
     03 CA-FSD-CUSTOMER-NUM      PIC 9(10).

          03 CA-FSD-ISSUE-DATE                PIC X(10).
          03 CA-FSD-EXPIRY-DATE               PIC X(10).
          03 CA-FSD-LASTCHANGED               PIC X(26).
          03 CA-FSD-BROKERID                  PIC 9(10).
          03 CA-FSD-BROKERSREF                PIC X(10).
          03 CA-FSD-PAYMENT                   PIC 9(6).
          03 CA-FSD-LIMIT-PER-PREMISES        PIC 9(9).
          03 CA-FSD-RENTED-SQFT               PIC 9(7).
          03 CA-FSD-CONSTRUCTION-TYPE         PIC X(2).
          03 CA-FSD-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-FSD-TERRITORY-CODE            PIC X(3).
