******************************************************************
*  COPYBOOK  : GFVAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : VA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-FVA-POLICY.

          03 DB2-FVA-ISSUE-DATE               PIC X(10).
          03 DB2-FVA-EXPIRY-DATE              PIC X(10).
          03 DB2-FVA-LASTCHANGED              PIC X(26).
          03 DB2-FVA-BROKERID                 PIC 9(10).
          03 DB2-FVA-BROKERSREF               PIC X(10).
          03 DB2-FVA-PAYMENT                  PIC 9(6).
          03 DB2-FVA-LIMIT-PER-PREMISES       PIC 9(9).
          03 DB2-FVA-RENTED-SQFT              PIC 9(7).
          03 DB2-FVA-CONSTRUCTION-TYPE        PIC X(2).
          03 DB2-FVA-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-FVA-TERRITORY-CODE           PIC X(3).
