******************************************************************
*  COPYBOOK  : GFVTC001
*  KIND      : COMMAREA
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : VT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-FVT-REQUEST-ID        PIC X(6).
     03 CA-FVT-RETURN-CODE       PIC 9(2).
     03 CA-FVT-POLICY-NUM        PIC 9(10).
     03 CA-FVT-CUSTOMER-NUM      PIC 9(10).

          03 CA-FVT-ISSUE-DATE                PIC X(10).
          03 CA-FVT-EXPIRY-DATE               PIC X(10).
          03 CA-FVT-LASTCHANGED               PIC X(26).
          03 CA-FVT-BROKERID                  PIC 9(10).
          03 CA-FVT-BROKERSREF                PIC X(10).
          03 CA-FVT-PAYMENT                   PIC 9(6).
          03 CA-FVT-LIMIT-PER-PREMISES        PIC 9(9).
          03 CA-FVT-RENTED-SQFT               PIC 9(7).
          03 CA-FVT-CONSTRUCTION-TYPE         PIC X(2).
          03 CA-FVT-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-FVT-TERRITORY-CODE            PIC X(3).
