******************************************************************
*  COPYBOOK  : GFVTP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Damage to Premises Rented to You (Fire Legal Liability) (FL)
*  STATE     : VT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-FVT-POLICY.

          03 DB2-FVT-ISSUE-DATE               PIC X(10).
          03 DB2-FVT-EXPIRY-DATE              PIC X(10).
          03 DB2-FVT-LASTCHANGED              PIC X(26).
          03 DB2-FVT-BROKERID                 PIC 9(10).
          03 DB2-FVT-BROKERSREF               PIC X(10).
          03 DB2-FVT-PAYMENT                  PIC 9(6).
          03 DB2-FVT-LIMIT-PER-PREMISES       PIC 9(9).
          03 DB2-FVT-RENTED-SQFT              PIC 9(7).
          03 DB2-FVT-CONSTRUCTION-TYPE        PIC X(2).
          03 DB2-FVT-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-FVT-TERRITORY-CODE           PIC X(3).
