******************************************************************
*  COPYBOOK  : GMAKC001
*  KIND      : COMMAREA
*  COVERAGE  : Medical Payments (MP)
*  STATE     : AK
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-MAK-REQUEST-ID        PIC X(6).
     03 CA-MAK-RETURN-CODE       PIC 9(2).
     03 CA-MAK-POLICY-NUM        PIC 9(10).
     03 CA-MAK-CUSTOMER-NUM      PIC 9(10).

          03 CA-MAK-ISSUE-DATE                PIC X(10).
          03 CA-MAK-EXPIRY-DATE               PIC X(10).
          03 CA-MAK-LASTCHANGED               PIC X(26).
          03 CA-MAK-BROKERID                  PIC 9(10).
          03 CA-MAK-BROKERSREF                PIC X(10).
          03 CA-MAK-PAYMENT                   PIC 9(6).
          03 CA-MAK-LIMIT-PER-PERSON          PIC 9(7).
          03 CA-MAK-PREMISES-COUNT            PIC 9(3).
          03 CA-MAK-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-MAK-CLASS-CODE                PIC X(4).
