******************************************************************
*  COPYBOOK  : GMARC001
*  KIND      : COMMAREA
*  COVERAGE  : Medical Payments (MP)
*  STATE     : AR
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-MAR-REQUEST-ID        PIC X(6).
     03 CA-MAR-RETURN-CODE       PIC 9(2).
     03 CA-MAR-POLICY-NUM        PIC 9(10).
     03 CA-MAR-CUSTOMER-NUM      PIC 9(10).

          03 CA-MAR-ISSUE-DATE                PIC X(10).
          03 CA-MAR-EXPIRY-DATE               PIC X(10).
          03 CA-MAR-LASTCHANGED               PIC X(26).
          03 CA-MAR-BROKERID                  PIC 9(10).
          03 CA-MAR-BROKERSREF                PIC X(10).
          03 CA-MAR-PAYMENT                   PIC 9(6).
          03 CA-MAR-LIMIT-PER-PERSON          PIC 9(7).
          03 CA-MAR-PREMISES-COUNT            PIC 9(3).
          03 CA-MAR-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-MAR-CLASS-CODE                PIC X(4).
