******************************************************************
*  COPYBOOK  : GMARP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Medical Payments (MP)
*  STATE     : AR
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-MAR-POLICY.

          03 DB2-MAR-ISSUE-DATE               PIC X(10).
          03 DB2-MAR-EXPIRY-DATE              PIC X(10).
          03 DB2-MAR-LASTCHANGED              PIC X(26).
          03 DB2-MAR-BROKERID                 PIC 9(10).
          03 DB2-MAR-BROKERSREF               PIC X(10).
          03 DB2-MAR-PAYMENT                  PIC 9(6).
          03 DB2-MAR-LIMIT-PER-PERSON         PIC 9(7).
          03 DB2-MAR-PREMISES-COUNT           PIC 9(3).
          03 DB2-MAR-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-MAR-CLASS-CODE               PIC X(4).
