******************************************************************
*  COPYBOOK  : GMAZC001
*  KIND      : COMMAREA
*  COVERAGE  : Medical Payments (MP)
*  STATE     : AZ
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-MAZ-REQUEST-ID        PIC X(6).
     03 CA-MAZ-RETURN-CODE       PIC 9(2).
     03 CA-MAZ-POLICY-NUM        PIC 9(10).
     03 CA-MAZ-CUSTOMER-NUM      PIC 9(10).

          03 CA-MAZ-ISSUE-DATE                PIC X(10).
          03 CA-MAZ-EXPIRY-DATE               PIC X(10).
          03 CA-MAZ-LASTCHANGED               PIC X(26).
          03 CA-MAZ-BROKERID                  PIC 9(10).
          03 CA-MAZ-BROKERSREF                PIC X(10).
          03 CA-MAZ-PAYMENT                   PIC 9(6).
          03 CA-MAZ-LIMIT-PER-PERSON          PIC 9(7).
          03 CA-MAZ-PREMISES-COUNT            PIC 9(3).
          03 CA-MAZ-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-MAZ-CLASS-CODE                PIC X(4).
