******************************************************************
*  COPYBOOK  : GMAZP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Medical Payments (MP)
*  STATE     : AZ
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-MAZ-POLICY.

          03 DB2-MAZ-ISSUE-DATE               PIC X(10).
          03 DB2-MAZ-EXPIRY-DATE              PIC X(10).
          03 DB2-MAZ-LASTCHANGED              PIC X(26).
          03 DB2-MAZ-BROKERID                 PIC 9(10).
          03 DB2-MAZ-BROKERSREF               PIC X(10).
          03 DB2-MAZ-PAYMENT                  PIC 9(6).
          03 DB2-MAZ-LIMIT-PER-PERSON         PIC 9(7).
          03 DB2-MAZ-PREMISES-COUNT           PIC 9(3).
          03 DB2-MAZ-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-MAZ-CLASS-CODE               PIC X(4).
