******************************************************************
*  COPYBOOK  : GMCAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Medical Payments (MP)
*  STATE     : CA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-MCA-POLICY.

          03 DB2-MCA-ISSUE-DATE               PIC X(10).
          03 DB2-MCA-EXPIRY-DATE              PIC X(10).
          03 DB2-MCA-LASTCHANGED              PIC X(26).
          03 DB2-MCA-BROKERID                 PIC 9(10).
          03 DB2-MCA-BROKERSREF               PIC X(10).
          03 DB2-MCA-PAYMENT                  PIC 9(6).
          03 DB2-MCA-LIMIT-PER-PERSON         PIC 9(7).
          03 DB2-MCA-PREMISES-COUNT           PIC 9(3).
          03 DB2-MCA-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-MCA-CLASS-CODE               PIC X(4).
