******************************************************************
*  COPYBOOK  : GMCAC001
*  KIND      : COMMAREA
*  COVERAGE  : Medical Payments (MP)
*  STATE     : CA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-MCA-REQUEST-ID        PIC X(6).
     03 CA-MCA-RETURN-CODE       PIC 9(2).
     03 CA-MCA-POLICY-NUM        PIC 9(10).
     03 CA-MCA-CUSTOMER-NUM      PIC 9(10).

          03 CA-MCA-ISSUE-DATE                PIC X(10).
          03 CA-MCA-EXPIRY-DATE               PIC X(10).
          03 CA-MCA-LASTCHANGED               PIC X(26).
          03 CA-MCA-BROKERID                  PIC 9(10).
          03 CA-MCA-BROKERSREF                PIC X(10).
          03 CA-MCA-PAYMENT                   PIC 9(6).
          03 CA-MCA-LIMIT-PER-PERSON          PIC 9(7).
          03 CA-MCA-PREMISES-COUNT            PIC 9(3).
          03 CA-MCA-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-MCA-CLASS-CODE                PIC X(4).
