******************************************************************
*  COPYBOOK  : GMCOC001
*  KIND      : COMMAREA
*  COVERAGE  : Medical Payments (MP)
*  STATE     : CO
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-MCO-REQUEST-ID        PIC X(6).
     03 CA-MCO-RETURN-CODE       PIC 9(2).
     03 CA-MCO-POLICY-NUM        PIC 9(10).
     03 CA-MCO-CUSTOMER-NUM      PIC 9(10).

          03 CA-MCO-ISSUE-DATE                PIC X(10).
          03 CA-MCO-EXPIRY-DATE               PIC X(10).
          03 CA-MCO-LASTCHANGED               PIC X(26).
          03 CA-MCO-BROKERID                  PIC 9(10).
          03 CA-MCO-BROKERSREF                PIC X(10).
          03 CA-MCO-PAYMENT                   PIC 9(6).
          03 CA-MCO-LIMIT-PER-PERSON          PIC 9(7).
          03 CA-MCO-PREMISES-COUNT            PIC 9(3).
          03 CA-MCO-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-MCO-CLASS-CODE                PIC X(4).
