******************************************************************
*  COPYBOOK  : GMDEC001
*  KIND      : COMMAREA
*  COVERAGE  : Medical Payments (MP)
*  STATE     : DE
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-MDE-REQUEST-ID        PIC X(6).
     03 CA-MDE-RETURN-CODE       PIC 9(2).
     03 CA-MDE-POLICY-NUM        PIC 9(10).
     03 CA-MDE-CUSTOMER-NUM      PIC 9(10).

          03 CA-MDE-ISSUE-DATE                PIC X(10).
          03 CA-MDE-EXPIRY-DATE               PIC X(10).
          03 CA-MDE-LASTCHANGED               PIC X(26).
          03 CA-MDE-BROKERID                  PIC 9(10).
          03 CA-MDE-BROKERSREF                PIC X(10).
          03 CA-MDE-PAYMENT                   PIC 9(6).
          03 CA-MDE-LIMIT-PER-PERSON          PIC 9(7).
          03 CA-MDE-PREMISES-COUNT            PIC 9(3).
          03 CA-MDE-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-MDE-CLASS-CODE                PIC X(4).
