******************************************************************
*  COPYBOOK  : GMDEP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Medical Payments (MP)
*  STATE     : DE
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-MDE-POLICY.

          03 DB2-MDE-ISSUE-DATE               PIC X(10).
          03 DB2-MDE-EXPIRY-DATE              PIC X(10).
          03 DB2-MDE-LASTCHANGED              PIC X(26).
          03 DB2-MDE-BROKERID                 PIC 9(10).
          03 DB2-MDE-BROKERSREF               PIC X(10).
          03 DB2-MDE-PAYMENT                  PIC 9(6).
          03 DB2-MDE-LIMIT-PER-PERSON         PIC 9(7).
          03 DB2-MDE-PREMISES-COUNT           PIC 9(3).
          03 DB2-MDE-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-MDE-CLASS-CODE               PIC X(4).
