******************************************************************
*  COPYBOOK  : GMHIC001
*  KIND      : COMMAREA
*  COVERAGE  : Medical Payments (MP)
*  STATE     : HI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-MHI-REQUEST-ID        PIC X(6).
     03 CA-MHI-RETURN-CODE       PIC 9(2).
     03 CA-MHI-POLICY-NUM        PIC 9(10).
     03 CA-MHI-CUSTOMER-NUM      PIC 9(10).

          03 CA-MHI-ISSUE-DATE                PIC X(10).
          03 CA-MHI-EXPIRY-DATE               PIC X(10).
          03 CA-MHI-LASTCHANGED               PIC X(26).
          03 CA-MHI-BROKERID                  PIC 9(10).
          03 CA-MHI-BROKERSREF                PIC X(10).
          03 CA-MHI-PAYMENT                   PIC 9(6).
          03 CA-MHI-LIMIT-PER-PERSON          PIC 9(7).
          03 CA-MHI-PREMISES-COUNT            PIC 9(3).
          03 CA-MHI-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-MHI-CLASS-CODE                PIC X(4).
