******************************************************************
*  COPYBOOK  : GMILC001
*  KIND      : COMMAREA
*  COVERAGE  : Medical Payments (MP)
*  STATE     : IL
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-MIL-REQUEST-ID        PIC X(6).
     03 CA-MIL-RETURN-CODE       PIC 9(2).
     03 CA-MIL-POLICY-NUM        PIC 9(10).
     03 CA-MIL-CUSTOMER-NUM      PIC 9(10).

          03 CA-MIL-ISSUE-DATE                PIC X(10).
          03 CA-MIL-EXPIRY-DATE               PIC X(10).
          03 CA-MIL-LASTCHANGED               PIC X(26).
          03 CA-MIL-BROKERID                  PIC 9(10).
          03 CA-MIL-BROKERSREF                PIC X(10).
          03 CA-MIL-PAYMENT                   PIC 9(6).
          03 CA-MIL-LIMIT-PER-PERSON          PIC 9(7).
          03 CA-MIL-PREMISES-COUNT            PIC 9(3).
          03 CA-MIL-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-MIL-CLASS-CODE                PIC X(4).
