******************************************************************
*  COPYBOOK  : GMINP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Medical Payments (MP)
*  STATE     : IN
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-MIN-POLICY.

          03 DB2-MIN-ISSUE-DATE               PIC X(10).
          03 DB2-MIN-EXPIRY-DATE              PIC X(10).
          03 DB2-MIN-LASTCHANGED              PIC X(26).
          03 DB2-MIN-BROKERID                 PIC 9(10).
          03 DB2-MIN-BROKERSREF               PIC X(10).
          03 DB2-MIN-PAYMENT                  PIC 9(6).
          03 DB2-MIN-LIMIT-PER-PERSON         PIC 9(7).
          03 DB2-MIN-PREMISES-COUNT           PIC 9(3).
          03 DB2-MIN-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-MIN-CLASS-CODE               PIC X(4).
