******************************************************************
*  COPYBOOK  : GMKSP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Medical Payments (MP)
*  STATE     : KS
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-MKS-POLICY.

          03 DB2-MKS-ISSUE-DATE               PIC X(10).
          03 DB2-MKS-EXPIRY-DATE              PIC X(10).
          03 DB2-MKS-LASTCHANGED              PIC X(26).
          03 DB2-MKS-BROKERID                 PIC 9(10).
          03 DB2-MKS-BROKERSREF               PIC X(10).
          03 DB2-MKS-PAYMENT                  PIC 9(6).
          03 DB2-MKS-LIMIT-PER-PERSON         PIC 9(7).
          03 DB2-MKS-PREMISES-COUNT           PIC 9(3).
          03 DB2-MKS-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-MKS-CLASS-CODE               PIC X(4).
