******************************************************************
*  COPYBOOK  : GMKYC001
*  KIND      : COMMAREA
*  COVERAGE  : Medical Payments (MP)
*  STATE     : KY
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-MKY-REQUEST-ID        PIC X(6).
     03 CA-MKY-RETURN-CODE       PIC 9(2).
     03 CA-MKY-POLICY-NUM        PIC 9(10).
     03 CA-MKY-CUSTOMER-NUM      PIC 9(10).

          03 CA-MKY-ISSUE-DATE                PIC X(10).
          03 CA-MKY-EXPIRY-DATE               PIC X(10).
          03 CA-MKY-LASTCHANGED               PIC X(26).
          03 CA-MKY-BROKERID                  PIC 9(10).
          03 CA-MKY-BROKERSREF                PIC X(10).
          03 CA-MKY-PAYMENT                   PIC 9(6).
          03 CA-MKY-LIMIT-PER-PERSON          PIC 9(7).
          03 CA-MKY-PREMISES-COUNT            PIC 9(3).
          03 CA-MKY-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-MKY-CLASS-CODE                PIC X(4).
