******************************************************************
*  COPYBOOK  : GMMAC001
*  KIND      : COMMAREA
*  COVERAGE  : Medical Payments (MP)
*  STATE     : MA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-MMA-REQUEST-ID        PIC X(6).
     03 CA-MMA-RETURN-CODE       PIC 9(2).
     03 CA-MMA-POLICY-NUM        PIC 9(10).
     03 CA-MMA-CUSTOMER-NUM      PIC 9(10).

          03 CA-MMA-ISSUE-DATE                PIC X(10).
          03 CA-MMA-EXPIRY-DATE               PIC X(10).
          03 CA-MMA-LASTCHANGED               PIC X(26).
          03 CA-MMA-BROKERID                  PIC 9(10).
          03 CA-MMA-BROKERSREF                PIC X(10).
          03 CA-MMA-PAYMENT                   PIC 9(6).
          03 CA-MMA-LIMIT-PER-PERSON          PIC 9(7).
          03 CA-MMA-PREMISES-COUNT            PIC 9(3).
          03 CA-MMA-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-MMA-CLASS-CODE                PIC X(4).
