******************************************************************
*  COPYBOOK  : GMMEP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Medical Payments (MP)
*  STATE     : ME
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-MME-POLICY.

          03 DB2-MME-ISSUE-DATE               PIC X(10).
          03 DB2-MME-EXPIRY-DATE              PIC X(10).
          03 DB2-MME-LASTCHANGED              PIC X(26).
          03 DB2-MME-BROKERID                 PIC 9(10).
          03 DB2-MME-BROKERSREF               PIC X(10).
          03 DB2-MME-PAYMENT                  PIC 9(6).
          03 DB2-MME-LIMIT-PER-PERSON         PIC 9(7).
          03 DB2-MME-PREMISES-COUNT           PIC 9(3).
          03 DB2-MME-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-MME-CLASS-CODE               PIC X(4).
