******************************************************************
*  COPYBOOK  : GMMEC001
*  KIND      : COMMAREA
*  COVERAGE  : Medical Payments (MP)
*  STATE     : ME
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-MME-REQUEST-ID        PIC X(6).
     03 CA-MME-RETURN-CODE       PIC 9(2).
     03 CA-MME-POLICY-NUM        PIC 9(10).
     03 CA-MME-CUSTOMER-NUM      PIC 9(10).

          03 CA-MME-ISSUE-DATE                PIC X(10).
          03 CA-MME-EXPIRY-DATE               PIC X(10).
          03 CA-MME-LASTCHANGED               PIC X(26).
          03 CA-MME-BROKERID                  PIC 9(10).
          03 CA-MME-BROKERSREF                PIC X(10).
          03 CA-MME-PAYMENT                   PIC 9(6).
          03 CA-MME-LIMIT-PER-PERSON          PIC 9(7).
          03 CA-MME-PREMISES-COUNT            PIC 9(3).
          03 CA-MME-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-MME-CLASS-CODE                PIC X(4).
