******************************************************************
*  COPYBOOK  : GMMNC001
*  KIND      : COMMAREA
*  COVERAGE  : Medical Payments (MP)
*  STATE     : MN
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-MMN-REQUEST-ID        PIC X(6).
     03 CA-MMN-RETURN-CODE       PIC 9(2).
     03 CA-MMN-POLICY-NUM        PIC 9(10).
     03 CA-MMN-CUSTOMER-NUM      PIC 9(10).

          03 CA-MMN-ISSUE-DATE                PIC X(10).
          03 CA-MMN-EXPIRY-DATE               PIC X(10).
          03 CA-MMN-LASTCHANGED               PIC X(26).
          03 CA-MMN-BROKERID                  PIC 9(10).
          03 CA-MMN-BROKERSREF                PIC X(10).
          03 CA-MMN-PAYMENT                   PIC 9(6).
          03 CA-MMN-LIMIT-PER-PERSON          PIC 9(7).
          03 CA-MMN-PREMISES-COUNT            PIC 9(3).
          03 CA-MMN-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-MMN-CLASS-CODE                PIC X(4).
