******************************************************************
*  COPYBOOK  : GMMOC001
*  KIND      : COMMAREA
*  COVERAGE  : Medical Payments (MP)
*  STATE     : MO
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-MMO-REQUEST-ID        PIC X(6).
     03 CA-MMO-RETURN-CODE       PIC 9(2).
     03 CA-MMO-POLICY-NUM        PIC 9(10).
     03 CA-MMO-CUSTOMER-NUM      PIC 9(10).

          03 CA-MMO-ISSUE-DATE                PIC X(10).
          03 CA-MMO-EXPIRY-DATE               PIC X(10).
          03 CA-MMO-LASTCHANGED               PIC X(26).
          03 CA-MMO-BROKERID                  PIC 9(10).
          03 CA-MMO-BROKERSREF                PIC X(10).
          03 CA-MMO-PAYMENT                   PIC 9(6).
          03 CA-MMO-LIMIT-PER-PERSON          PIC 9(7).
          03 CA-MMO-PREMISES-COUNT            PIC 9(3).
          03 CA-MMO-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-MMO-CLASS-CODE                PIC X(4).
