******************************************************************
*  COPYBOOK  : GMMSP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Medical Payments (MP)
*  STATE     : MS
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-MMS-POLICY.

          03 DB2-MMS-ISSUE-DATE               PIC X(10).
          03 DB2-MMS-EXPIRY-DATE              PIC X(10).
          03 DB2-MMS-LASTCHANGED              PIC X(26).
          03 DB2-MMS-BROKERID                 PIC 9(10).
          03 DB2-MMS-BROKERSREF               PIC X(10).
          03 DB2-MMS-PAYMENT                  PIC 9(6).
          03 DB2-MMS-LIMIT-PER-PERSON         PIC 9(7).
          03 DB2-MMS-PREMISES-COUNT           PIC 9(3).
          03 DB2-MMS-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-MMS-CLASS-CODE               PIC X(4).
