******************************************************************
*  COPYBOOK  : GMMSC001
*  KIND      : COMMAREA
*  COVERAGE  : Medical Payments (MP)
*  STATE     : MS
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-MMS-REQUEST-ID        PIC X(6).
     03 CA-MMS-RETURN-CODE       PIC 9(2).
     03 CA-MMS-POLICY-NUM        PIC 9(10).
     03 CA-MMS-CUSTOMER-NUM      PIC 9(10).

          03 CA-MMS-ISSUE-DATE                PIC X(10).
          03 CA-MMS-EXPIRY-DATE               PIC X(10).
          03 CA-MMS-LASTCHANGED               PIC X(26).
          03 CA-MMS-BROKERID                  PIC 9(10).
          03 CA-MMS-BROKERSREF                PIC X(10).
          03 CA-MMS-PAYMENT                   PIC 9(6).
          03 CA-MMS-LIMIT-PER-PERSON          PIC 9(7).
          03 CA-MMS-PREMISES-COUNT            PIC 9(3).
          03 CA-MMS-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-MMS-CLASS-CODE                PIC X(4).
