******************************************************************
*  COPYBOOK  : GMNDP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Medical Payments (MP)
*  STATE     : ND
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-MND-POLICY.

          03 DB2-MND-ISSUE-DATE               PIC X(10).
          03 DB2-MND-EXPIRY-DATE              PIC X(10).
          03 DB2-MND-LASTCHANGED              PIC X(26).
          03 DB2-MND-BROKERID                 PIC 9(10).
          03 DB2-MND-BROKERSREF               PIC X(10).
          03 DB2-MND-PAYMENT                  PIC 9(6).
          03 DB2-MND-LIMIT-PER-PERSON         PIC 9(7).
          03 DB2-MND-PREMISES-COUNT           PIC 9(3).
          03 DB2-MND-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-MND-CLASS-CODE               PIC X(4).
