******************************************************************
*  COPYBOOK  : GMNEC001
*  KIND      : COMMAREA
*  COVERAGE  : Medical Payments (MP)
*  STATE     : NE
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-MNE-REQUEST-ID        PIC X(6).
     03 CA-MNE-RETURN-CODE       PIC 9(2).
     03 CA-MNE-POLICY-NUM        PIC 9(10).
     03 CA-MNE-CUSTOMER-NUM      PIC 9(10).

          03 CA-MNE-ISSUE-DATE                PIC X(10).
          03 CA-MNE-EXPIRY-DATE               PIC X(10).
          03 CA-MNE-LASTCHANGED               PIC X(26).
          03 CA-MNE-BROKERID                  PIC 9(10).
          03 CA-MNE-BROKERSREF                PIC X(10).
          03 CA-MNE-PAYMENT                   PIC 9(6).
          03 CA-MNE-LIMIT-PER-PERSON          PIC 9(7).
          03 CA-MNE-PREMISES-COUNT            PIC 9(3).
          03 CA-MNE-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-MNE-CLASS-CODE                PIC X(4).
