******************************************************************
*  COPYBOOK  : GMNHP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Medical Payments (MP)
*  STATE     : NH
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-MNH-POLICY.

          03 DB2-MNH-ISSUE-DATE               PIC X(10).
          03 DB2-MNH-EXPIRY-DATE              PIC X(10).
          03 DB2-MNH-LASTCHANGED              PIC X(26).
          03 DB2-MNH-BROKERID                 PIC 9(10).
          03 DB2-MNH-BROKERSREF               PIC X(10).
          03 DB2-MNH-PAYMENT                  PIC 9(6).
          03 DB2-MNH-LIMIT-PER-PERSON         PIC 9(7).
          03 DB2-MNH-PREMISES-COUNT           PIC 9(3).
          03 DB2-MNH-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-MNH-CLASS-CODE               PIC X(4).
