******************************************************************
*  COPYBOOK  : GMNJC001
*  KIND      : COMMAREA
*  COVERAGE  : Medical Payments (MP)
*  STATE     : NJ
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-MNJ-REQUEST-ID        PIC X(6).
     03 CA-MNJ-RETURN-CODE       PIC 9(2).
     03 CA-MNJ-POLICY-NUM        PIC 9(10).
     03 CA-MNJ-CUSTOMER-NUM      PIC 9(10).

          03 CA-MNJ-ISSUE-DATE                PIC X(10).
          03 CA-MNJ-EXPIRY-DATE               PIC X(10).
          03 CA-MNJ-LASTCHANGED               PIC X(26).
          03 CA-MNJ-BROKERID                  PIC 9(10).
          03 CA-MNJ-BROKERSREF                PIC X(10).
          03 CA-MNJ-PAYMENT                   PIC 9(6).
          03 CA-MNJ-LIMIT-PER-PERSON          PIC 9(7).
          03 CA-MNJ-PREMISES-COUNT            PIC 9(3).
          03 CA-MNJ-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-MNJ-CLASS-CODE                PIC X(4).
