******************************************************************
*  COPYBOOK  : GMNYC001
*  KIND      : COMMAREA
*  COVERAGE  : Medical Payments (MP)
*  STATE     : NY
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-MNY-REQUEST-ID        PIC X(6).
     03 CA-MNY-RETURN-CODE       PIC 9(2).
     03 CA-MNY-POLICY-NUM        PIC 9(10).
     03 CA-MNY-CUSTOMER-NUM      PIC 9(10).

          03 CA-MNY-ISSUE-DATE                PIC X(10).
          03 CA-MNY-EXPIRY-DATE               PIC X(10).
          03 CA-MNY-LASTCHANGED               PIC X(26).
          03 CA-MNY-BROKERID                  PIC 9(10).
          03 CA-MNY-BROKERSREF                PIC X(10).
          03 CA-MNY-PAYMENT                   PIC 9(6).
          03 CA-MNY-LIMIT-PER-PERSON          PIC 9(7).
          03 CA-MNY-PREMISES-COUNT            PIC 9(3).
          03 CA-MNY-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-MNY-CLASS-CODE                PIC X(4).
