******************************************************************
*  COPYBOOK  : GMNYP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Medical Payments (MP)
*  STATE     : NY
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-MNY-POLICY.

          03 DB2-MNY-ISSUE-DATE               PIC X(10).
          03 DB2-MNY-EXPIRY-DATE              PIC X(10).
          03 DB2-MNY-LASTCHANGED              PIC X(26).
          03 DB2-MNY-BROKERID                 PIC 9(10).
          03 DB2-MNY-BROKERSREF               PIC X(10).
          03 DB2-MNY-PAYMENT                  PIC 9(6).
          03 DB2-MNY-LIMIT-PER-PERSON         PIC 9(7).
          03 DB2-MNY-PREMISES-COUNT           PIC 9(3).
          03 DB2-MNY-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-MNY-CLASS-CODE               PIC X(4).
