******************************************************************
*  COPYBOOK  : GMOHP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Medical Payments (MP)
*  STATE     : OH
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-MOH-POLICY.

          03 DB2-MOH-ISSUE-DATE               PIC X(10).
          03 DB2-MOH-EXPIRY-DATE              PIC X(10).
          03 DB2-MOH-LASTCHANGED              PIC X(26).
          03 DB2-MOH-BROKERID                 PIC 9(10).
          03 DB2-MOH-BROKERSREF               PIC X(10).
          03 DB2-MOH-PAYMENT                  PIC 9(6).
          03 DB2-MOH-LIMIT-PER-PERSON         PIC 9(7).
          03 DB2-MOH-PREMISES-COUNT           PIC 9(3).
          03 DB2-MOH-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-MOH-CLASS-CODE               PIC X(4).
