******************************************************************
*  COPYBOOK  : GMRIC001
*  KIND      : COMMAREA
*  COVERAGE  : Medical Payments (MP)
*  STATE     : RI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-MRI-REQUEST-ID        PIC X(6).
     03 CA-MRI-RETURN-CODE       PIC 9(2).
     03 CA-MRI-POLICY-NUM        PIC 9(10).
     03 CA-MRI-CUSTOMER-NUM      PIC 9(10).

          03 CA-MRI-ISSUE-DATE                PIC X(10).
          03 CA-MRI-EXPIRY-DATE               PIC X(10).
          03 CA-MRI-LASTCHANGED               PIC X(26).
          03 CA-MRI-BROKERID                  PIC 9(10).
          03 CA-MRI-BROKERSREF                PIC X(10).
          03 CA-MRI-PAYMENT                   PIC 9(6).
          03 CA-MRI-LIMIT-PER-PERSON          PIC 9(7).
          03 CA-MRI-PREMISES-COUNT            PIC 9(3).
          03 CA-MRI-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-MRI-CLASS-CODE                PIC X(4).
