******************************************************************
*  COPYBOOK  : GMSCP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Medical Payments (MP)
*  STATE     : SC
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-MSC-POLICY.

          03 DB2-MSC-ISSUE-DATE               PIC X(10).
          03 DB2-MSC-EXPIRY-DATE              PIC X(10).
          03 DB2-MSC-LASTCHANGED              PIC X(26).
          03 DB2-MSC-BROKERID                 PIC 9(10).
          03 DB2-MSC-BROKERSREF               PIC X(10).
          03 DB2-MSC-PAYMENT                  PIC 9(6).
          03 DB2-MSC-LIMIT-PER-PERSON         PIC 9(7).
          03 DB2-MSC-PREMISES-COUNT           PIC 9(3).
          03 DB2-MSC-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-MSC-CLASS-CODE               PIC X(4).
