******************************************************************
*  COPYBOOK  : GMSDP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Medical Payments (MP)
*  STATE     : SD
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-MSD-POLICY.

          03 DB2-MSD-ISSUE-DATE               PIC X(10).
          03 DB2-MSD-EXPIRY-DATE              PIC X(10).
          03 DB2-MSD-LASTCHANGED              PIC X(26).
          03 DB2-MSD-BROKERID                 PIC 9(10).
          03 DB2-MSD-BROKERSREF               PIC X(10).
          03 DB2-MSD-PAYMENT                  PIC 9(6).
          03 DB2-MSD-LIMIT-PER-PERSON         PIC 9(7).
          03 DB2-MSD-PREMISES-COUNT           PIC 9(3).
          03 DB2-MSD-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-MSD-CLASS-CODE               PIC X(4).
