******************************************************************
*  COPYBOOK  : GMTNP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Medical Payments (MP)
*  STATE     : TN
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-MTN-POLICY.

          03 DB2-MTN-ISSUE-DATE               PIC X(10).
          03 DB2-MTN-EXPIRY-DATE              PIC X(10).
          03 DB2-MTN-LASTCHANGED              PIC X(26).
          03 DB2-MTN-BROKERID                 PIC 9(10).
          03 DB2-MTN-BROKERSREF               PIC X(10).
          03 DB2-MTN-PAYMENT                  PIC 9(6).
          03 DB2-MTN-LIMIT-PER-PERSON         PIC 9(7).
          03 DB2-MTN-PREMISES-COUNT           PIC 9(3).
          03 DB2-MTN-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-MTN-CLASS-CODE               PIC X(4).
