******************************************************************
*  COPYBOOK  : GMTNC001
*  KIND      : COMMAREA
*  COVERAGE  : Medical Payments (MP)
*  STATE     : TN
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-MTN-REQUEST-ID        PIC X(6).
     03 CA-MTN-RETURN-CODE       PIC 9(2).
     03 CA-MTN-POLICY-NUM        PIC 9(10).
     03 CA-MTN-CUSTOMER-NUM      PIC 9(10).

          03 CA-MTN-ISSUE-DATE                PIC X(10).
          03 CA-MTN-EXPIRY-DATE               PIC X(10).
          03 CA-MTN-LASTCHANGED               PIC X(26).
          03 CA-MTN-BROKERID                  PIC 9(10).
          03 CA-MTN-BROKERSREF                PIC X(10).
          03 CA-MTN-PAYMENT                   PIC 9(6).
          03 CA-MTN-LIMIT-PER-PERSON          PIC 9(7).
          03 CA-MTN-PREMISES-COUNT            PIC 9(3).
          03 CA-MTN-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-MTN-CLASS-CODE                PIC X(4).
