******************************************************************
*  COPYBOOK  : GMTXP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Medical Payments (MP)
*  STATE     : TX
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-MTX-POLICY.

          03 DB2-MTX-ISSUE-DATE               PIC X(10).
          03 DB2-MTX-EXPIRY-DATE              PIC X(10).
          03 DB2-MTX-LASTCHANGED              PIC X(26).
          03 DB2-MTX-BROKERID                 PIC 9(10).
          03 DB2-MTX-BROKERSREF               PIC X(10).
          03 DB2-MTX-PAYMENT                  PIC 9(6).
          03 DB2-MTX-LIMIT-PER-PERSON         PIC 9(7).
          03 DB2-MTX-PREMISES-COUNT           PIC 9(3).
          03 DB2-MTX-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-MTX-CLASS-CODE               PIC X(4).
