******************************************************************
*  COPYBOOK  : GMTXC001
*  KIND      : COMMAREA
*  COVERAGE  : Medical Payments (MP)
*  STATE     : TX
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-MTX-REQUEST-ID        PIC X(6).
     03 CA-MTX-RETURN-CODE       PIC 9(2).
     03 CA-MTX-POLICY-NUM        PIC 9(10).
     03 CA-MTX-CUSTOMER-NUM      PIC 9(10).

          03 CA-MTX-ISSUE-DATE                PIC X(10).
          03 CA-MTX-EXPIRY-DATE               PIC X(10).
          03 CA-MTX-LASTCHANGED               PIC X(26).
          03 CA-MTX-BROKERID                  PIC 9(10).
          03 CA-MTX-BROKERSREF                PIC X(10).
          03 CA-MTX-PAYMENT                   PIC 9(6).
          03 CA-MTX-LIMIT-PER-PERSON          PIC 9(7).
          03 CA-MTX-PREMISES-COUNT            PIC 9(3).
          03 CA-MTX-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-MTX-CLASS-CODE                PIC X(4).
