******************************************************************
*  COPYBOOK  : GMUTP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Medical Payments (MP)
*  STATE     : UT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-MUT-POLICY.

          03 DB2-MUT-ISSUE-DATE               PIC X(10).
          03 DB2-MUT-EXPIRY-DATE              PIC X(10).
          03 DB2-MUT-LASTCHANGED              PIC X(26).
          03 DB2-MUT-BROKERID                 PIC 9(10).
          03 DB2-MUT-BROKERSREF               PIC X(10).
          03 DB2-MUT-PAYMENT                  PIC 9(6).
          03 DB2-MUT-LIMIT-PER-PERSON         PIC 9(7).
          03 DB2-MUT-PREMISES-COUNT           PIC 9(3).
          03 DB2-MUT-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-MUT-CLASS-CODE               PIC X(4).
