******************************************************************
*  COPYBOOK  : GMUTC001
*  KIND      : COMMAREA
*  COVERAGE  : Medical Payments (MP)
*  STATE     : UT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-MUT-REQUEST-ID        PIC X(6).
     03 CA-MUT-RETURN-CODE       PIC 9(2).
     03 CA-MUT-POLICY-NUM        PIC 9(10).
     03 CA-MUT-CUSTOMER-NUM      PIC 9(10).

          03 CA-MUT-ISSUE-DATE                PIC X(10).
          03 CA-MUT-EXPIRY-DATE               PIC X(10).
          03 CA-MUT-LASTCHANGED               PIC X(26).
          03 CA-MUT-BROKERID                  PIC 9(10).
          03 CA-MUT-BROKERSREF                PIC X(10).
          03 CA-MUT-PAYMENT                   PIC 9(6).
          03 CA-MUT-LIMIT-PER-PERSON          PIC 9(7).
          03 CA-MUT-PREMISES-COUNT            PIC 9(3).
          03 CA-MUT-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-MUT-CLASS-CODE                PIC X(4).
