******************************************************************
*  COPYBOOK  : GMVAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Medical Payments (MP)
*  STATE     : VA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-MVA-POLICY.

          03 DB2-MVA-ISSUE-DATE               PIC X(10).
          03 DB2-MVA-EXPIRY-DATE              PIC X(10).
          03 DB2-MVA-LASTCHANGED              PIC X(26).
          03 DB2-MVA-BROKERID                 PIC 9(10).
          03 DB2-MVA-BROKERSREF               PIC X(10).
          03 DB2-MVA-PAYMENT                  PIC 9(6).
          03 DB2-MVA-LIMIT-PER-PERSON         PIC 9(7).
          03 DB2-MVA-PREMISES-COUNT           PIC 9(3).
          03 DB2-MVA-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-MVA-CLASS-CODE               PIC X(4).
