******************************************************************
*  COPYBOOK  : GMVAC001
*  KIND      : COMMAREA
*  COVERAGE  : Medical Payments (MP)
*  STATE     : VA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-MVA-REQUEST-ID        PIC X(6).
     03 CA-MVA-RETURN-CODE       PIC 9(2).
     03 CA-MVA-POLICY-NUM        PIC 9(10).
     03 CA-MVA-CUSTOMER-NUM      PIC 9(10).

          03 CA-MVA-ISSUE-DATE                PIC X(10).
          03 CA-MVA-EXPIRY-DATE               PIC X(10).
          03 CA-MVA-LASTCHANGED               PIC X(26).
          03 CA-MVA-BROKERID                  PIC 9(10).
          03 CA-MVA-BROKERSREF                PIC X(10).
          03 CA-MVA-PAYMENT                   PIC 9(6).
          03 CA-MVA-LIMIT-PER-PERSON          PIC 9(7).
          03 CA-MVA-PREMISES-COUNT            PIC 9(3).
          03 CA-MVA-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-MVA-CLASS-CODE                PIC X(4).
