******************************************************************
*  COPYBOOK  : GMVTC001
*  KIND      : COMMAREA
*  COVERAGE  : Medical Payments (MP)
*  STATE     : VT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-MVT-REQUEST-ID        PIC X(6).
     03 CA-MVT-RETURN-CODE       PIC 9(2).
     03 CA-MVT-POLICY-NUM        PIC 9(10).
     03 CA-MVT-CUSTOMER-NUM      PIC 9(10).

          03 CA-MVT-ISSUE-DATE                PIC X(10).
          03 CA-MVT-EXPIRY-DATE               PIC X(10).
          03 CA-MVT-LASTCHANGED               PIC X(26).
          03 CA-MVT-BROKERID                  PIC 9(10).
          03 CA-MVT-BROKERSREF                PIC X(10).
          03 CA-MVT-PAYMENT                   PIC 9(6).
          03 CA-MVT-LIMIT-PER-PERSON          PIC 9(7).
          03 CA-MVT-PREMISES-COUNT            PIC 9(3).
          03 CA-MVT-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-MVT-CLASS-CODE                PIC X(4).
