******************************************************************
*  COPYBOOK  : GMWAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Medical Payments (MP)
*  STATE     : WA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-MWA-POLICY.

          03 DB2-MWA-ISSUE-DATE               PIC X(10).
          03 DB2-MWA-EXPIRY-DATE              PIC X(10).
          03 DB2-MWA-LASTCHANGED              PIC X(26).
          03 DB2-MWA-BROKERID                 PIC 9(10).
          03 DB2-MWA-BROKERSREF               PIC X(10).
          03 DB2-MWA-PAYMENT                  PIC 9(6).
          03 DB2-MWA-LIMIT-PER-PERSON         PIC 9(7).
          03 DB2-MWA-PREMISES-COUNT           PIC 9(3).
          03 DB2-MWA-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-MWA-CLASS-CODE               PIC X(4).
