******************************************************************
*  COPYBOOK  : GAAKC001
*  KIND      : COMMAREA
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : AK
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-AAK-REQUEST-ID        PIC X(6).
     03 CA-AAK-RETURN-CODE       PIC 9(2).
     03 CA-AAK-POLICY-NUM        PIC 9(10).
     03 CA-AAK-CUSTOMER-NUM      PIC 9(10).

          03 CA-AAK-ISSUE-DATE                PIC X(10).
          03 CA-AAK-EXPIRY-DATE               PIC X(10).
          03 CA-AAK-LASTCHANGED               PIC X(26).
          03 CA-AAK-BROKERID                  PIC 9(10).
          03 CA-AAK-BROKERSREF                PIC X(10).
          03 CA-AAK-PAYMENT                   PIC 9(6).
          03 CA-AAK-MEDIA-EXPOSURE-IND        PIC X(1).
          03 CA-AAK-ADVERTISING-BUDGET        PIC 9(9).
          03 CA-AAK-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-AAK-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-AAK-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-AAK-TERRITORY-CODE            PIC X(3).
