******************************************************************
*  COPYBOOK  : GACAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : CA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-ACA-POLICY.

          03 DB2-ACA-ISSUE-DATE               PIC X(10).
          03 DB2-ACA-EXPIRY-DATE              PIC X(10).
          03 DB2-ACA-LASTCHANGED              PIC X(26).
          03 DB2-ACA-BROKERID                 PIC 9(10).
          03 DB2-ACA-BROKERSREF               PIC X(10).
          03 DB2-ACA-PAYMENT                  PIC 9(6).
          03 DB2-ACA-MEDIA-EXPOSURE-IND       PIC X(1).
          03 DB2-ACA-ADVERTISING-BUDGET       PIC 9(9).
          03 DB2-ACA-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-ACA-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-ACA-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-ACA-TERRITORY-CODE           PIC X(3).
