******************************************************************
*  COPYBOOK  : GACAC001
*  KIND      : COMMAREA
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : CA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-ACA-REQUEST-ID        PIC X(6).
     03 CA-ACA-RETURN-CODE       PIC 9(2).
     03 CA-ACA-POLICY-NUM        PIC 9(10).
     03 CA-ACA-CUSTOMER-NUM      PIC 9(10).

          03 CA-ACA-ISSUE-DATE                PIC X(10).
          03 CA-ACA-EXPIRY-DATE               PIC X(10).
          03 CA-ACA-LASTCHANGED               PIC X(26).
          03 CA-ACA-BROKERID                  PIC 9(10).
          03 CA-ACA-BROKERSREF                PIC X(10).
          03 CA-ACA-PAYMENT                   PIC 9(6).
          03 CA-ACA-MEDIA-EXPOSURE-IND        PIC X(1).
          03 CA-ACA-ADVERTISING-BUDGET        PIC 9(9).
          03 CA-ACA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-ACA-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-ACA-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-ACA-TERRITORY-CODE            PIC X(3).
