******************************************************************
*  COPYBOOK  : GACOP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : CO
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-ACO-POLICY.

          03 DB2-ACO-ISSUE-DATE               PIC X(10).
          03 DB2-ACO-EXPIRY-DATE              PIC X(10).
          03 DB2-ACO-LASTCHANGED              PIC X(26).
          03 DB2-ACO-BROKERID                 PIC 9(10).
          03 DB2-ACO-BROKERSREF               PIC X(10).
          03 DB2-ACO-PAYMENT                  PIC 9(6).
          03 DB2-ACO-MEDIA-EXPOSURE-IND       PIC X(1).
          03 DB2-ACO-ADVERTISING-BUDGET       PIC 9(9).
          03 DB2-ACO-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-ACO-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-ACO-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-ACO-TERRITORY-CODE           PIC X(3).
