******************************************************************
*  COPYBOOK  : GADEC001
*  KIND      : COMMAREA
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : DE
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-ADE-REQUEST-ID        PIC X(6).
     03 CA-ADE-RETURN-CODE       PIC 9(2).
     03 CA-ADE-POLICY-NUM        PIC 9(10).
     03 CA-ADE-CUSTOMER-NUM      PIC 9(10).

          03 CA-ADE-ISSUE-DATE                PIC X(10).
          03 CA-ADE-EXPIRY-DATE               PIC X(10).
          03 CA-ADE-LASTCHANGED               PIC X(26).
          03 CA-ADE-BROKERID                  PIC 9(10).
          03 CA-ADE-BROKERSREF                PIC X(10).
          03 CA-ADE-PAYMENT                   PIC 9(6).
          03 CA-ADE-MEDIA-EXPOSURE-IND        PIC X(1).
          03 CA-ADE-ADVERTISING-BUDGET        PIC 9(9).
          03 CA-ADE-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-ADE-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-ADE-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-ADE-TERRITORY-CODE            PIC X(3).
