******************************************************************
*  COPYBOOK  : GADEP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : DE
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-ADE-POLICY.

          03 DB2-ADE-ISSUE-DATE               PIC X(10).
          03 DB2-ADE-EXPIRY-DATE              PIC X(10).
          03 DB2-ADE-LASTCHANGED              PIC X(26).
          03 DB2-ADE-BROKERID                 PIC 9(10).
          03 DB2-ADE-BROKERSREF               PIC X(10).
          03 DB2-ADE-PAYMENT                  PIC 9(6).
          03 DB2-ADE-MEDIA-EXPOSURE-IND       PIC X(1).
          03 DB2-ADE-ADVERTISING-BUDGET       PIC 9(9).
          03 DB2-ADE-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-ADE-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-ADE-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-ADE-TERRITORY-CODE           PIC X(3).
