******************************************************************
*  COPYBOOK  : GAFLC001
*  KIND      : COMMAREA
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : FL
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-AFL-REQUEST-ID        PIC X(6).
     03 CA-AFL-RETURN-CODE       PIC 9(2).
     03 CA-AFL-POLICY-NUM        PIC 9(10).
     03 CA-AFL-CUSTOMER-NUM      PIC 9(10).

          03 CA-AFL-ISSUE-DATE                PIC X(10).
          03 CA-AFL-EXPIRY-DATE               PIC X(10).
          03 CA-AFL-LASTCHANGED               PIC X(26).
          03 CA-AFL-BROKERID                  PIC 9(10).
          03 CA-AFL-BROKERSREF                PIC X(10).
          03 CA-AFL-PAYMENT                   PIC 9(6).
          03 CA-AFL-MEDIA-EXPOSURE-IND        PIC X(1).
          03 CA-AFL-ADVERTISING-BUDGET        PIC 9(9).
          03 CA-AFL-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-AFL-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-AFL-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-AFL-TERRITORY-CODE            PIC X(3).
