******************************************************************
*  COPYBOOK  : GAGAC001
*  KIND      : COMMAREA
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : GA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-AGA-REQUEST-ID        PIC X(6).
     03 CA-AGA-RETURN-CODE       PIC 9(2).
     03 CA-AGA-POLICY-NUM        PIC 9(10).
     03 CA-AGA-CUSTOMER-NUM      PIC 9(10).

          03 CA-AGA-ISSUE-DATE                PIC X(10).
          03 CA-AGA-EXPIRY-DATE               PIC X(10).
          03 CA-AGA-LASTCHANGED               PIC X(26).
          03 CA-AGA-BROKERID                  PIC 9(10).
          03 CA-AGA-BROKERSREF                PIC X(10).
          03 CA-AGA-PAYMENT                   PIC 9(6).
          03 CA-AGA-MEDIA-EXPOSURE-IND        PIC X(1).
          03 CA-AGA-ADVERTISING-BUDGET        PIC 9(9).
          03 CA-AGA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-AGA-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-AGA-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-AGA-TERRITORY-CODE            PIC X(3).
