******************************************************************
*  COPYBOOK  : GAHIP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : HI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-AHI-POLICY.

          03 DB2-AHI-ISSUE-DATE               PIC X(10).
          03 DB2-AHI-EXPIRY-DATE              PIC X(10).
          03 DB2-AHI-LASTCHANGED              PIC X(26).
          03 DB2-AHI-BROKERID                 PIC 9(10).
          03 DB2-AHI-BROKERSREF               PIC X(10).
          03 DB2-AHI-PAYMENT                  PIC 9(6).
          03 DB2-AHI-MEDIA-EXPOSURE-IND       PIC X(1).
          03 DB2-AHI-ADVERTISING-BUDGET       PIC 9(9).
          03 DB2-AHI-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-AHI-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-AHI-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-AHI-TERRITORY-CODE           PIC X(3).
