******************************************************************
*  COPYBOOK  : GAIDP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : ID
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-AID-POLICY.

          03 DB2-AID-ISSUE-DATE               PIC X(10).
          03 DB2-AID-EXPIRY-DATE              PIC X(10).
          03 DB2-AID-LASTCHANGED              PIC X(26).
          03 DB2-AID-BROKERID                 PIC 9(10).
          03 DB2-AID-BROKERSREF               PIC X(10).
          03 DB2-AID-PAYMENT                  PIC 9(6).
          03 DB2-AID-MEDIA-EXPOSURE-IND       PIC X(1).
          03 DB2-AID-ADVERTISING-BUDGET       PIC 9(9).
          03 DB2-AID-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-AID-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-AID-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-AID-TERRITORY-CODE           PIC X(3).
