******************************************************************
*  COPYBOOK  : GAIDC001
*  KIND      : COMMAREA
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : ID
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-AID-REQUEST-ID        PIC X(6).
     03 CA-AID-RETURN-CODE       PIC 9(2).
     03 CA-AID-POLICY-NUM        PIC 9(10).
     03 CA-AID-CUSTOMER-NUM      PIC 9(10).

          03 CA-AID-ISSUE-DATE                PIC X(10).
          03 CA-AID-EXPIRY-DATE               PIC X(10).
          03 CA-AID-LASTCHANGED               PIC X(26).
          03 CA-AID-BROKERID                  PIC 9(10).
          03 CA-AID-BROKERSREF                PIC X(10).
          03 CA-AID-PAYMENT                   PIC 9(6).
          03 CA-AID-MEDIA-EXPOSURE-IND        PIC X(1).
          03 CA-AID-ADVERTISING-BUDGET        PIC 9(9).
          03 CA-AID-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-AID-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-AID-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-AID-TERRITORY-CODE            PIC X(3).
