******************************************************************
*  COPYBOOK  : GAINC001
*  KIND      : COMMAREA
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : IN
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-AIN-REQUEST-ID        PIC X(6).
     03 CA-AIN-RETURN-CODE       PIC 9(2).
     03 CA-AIN-POLICY-NUM        PIC 9(10).
     03 CA-AIN-CUSTOMER-NUM      PIC 9(10).

          03 CA-AIN-ISSUE-DATE                PIC X(10).
          03 CA-AIN-EXPIRY-DATE               PIC X(10).
          03 CA-AIN-LASTCHANGED               PIC X(26).
          03 CA-AIN-BROKERID                  PIC 9(10).
          03 CA-AIN-BROKERSREF                PIC X(10).
          03 CA-AIN-PAYMENT                   PIC 9(6).
          03 CA-AIN-MEDIA-EXPOSURE-IND        PIC X(1).
          03 CA-AIN-ADVERTISING-BUDGET        PIC 9(9).
          03 CA-AIN-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-AIN-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-AIN-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-AIN-TERRITORY-CODE            PIC X(3).
