******************************************************************
*  COPYBOOK  : GAKSP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : KS
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-AKS-POLICY.

          03 DB2-AKS-ISSUE-DATE               PIC X(10).
          03 DB2-AKS-EXPIRY-DATE              PIC X(10).
          03 DB2-AKS-LASTCHANGED              PIC X(26).
          03 DB2-AKS-BROKERID                 PIC 9(10).
          03 DB2-AKS-BROKERSREF               PIC X(10).
          03 DB2-AKS-PAYMENT                  PIC 9(6).
          03 DB2-AKS-MEDIA-EXPOSURE-IND       PIC X(1).
          03 DB2-AKS-ADVERTISING-BUDGET       PIC 9(9).
          03 DB2-AKS-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-AKS-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-AKS-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-AKS-TERRITORY-CODE           PIC X(3).
