******************************************************************
*  COPYBOOK  : GALAC001
*  KIND      : COMMAREA
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : LA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-ALA-REQUEST-ID        PIC X(6).
     03 CA-ALA-RETURN-CODE       PIC 9(2).
     03 CA-ALA-POLICY-NUM        PIC 9(10).
     03 CA-ALA-CUSTOMER-NUM      PIC 9(10).

          03 CA-ALA-ISSUE-DATE                PIC X(10).
          03 CA-ALA-EXPIRY-DATE               PIC X(10).
          03 CA-ALA-LASTCHANGED               PIC X(26).
          03 CA-ALA-BROKERID                  PIC 9(10).
          03 CA-ALA-BROKERSREF                PIC X(10).
          03 CA-ALA-PAYMENT                   PIC 9(6).
          03 CA-ALA-MEDIA-EXPOSURE-IND        PIC X(1).
          03 CA-ALA-ADVERTISING-BUDGET        PIC 9(9).
          03 CA-ALA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-ALA-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-ALA-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-ALA-TERRITORY-CODE            PIC X(3).
