******************************************************************
*  COPYBOOK  : GALAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : LA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-ALA-POLICY.

          03 DB2-ALA-ISSUE-DATE               PIC X(10).
          03 DB2-ALA-EXPIRY-DATE              PIC X(10).
          03 DB2-ALA-LASTCHANGED              PIC X(26).
          03 DB2-ALA-BROKERID                 PIC 9(10).
          03 DB2-ALA-BROKERSREF               PIC X(10).
          03 DB2-ALA-PAYMENT                  PIC 9(6).
          03 DB2-ALA-MEDIA-EXPOSURE-IND       PIC X(1).
          03 DB2-ALA-ADVERTISING-BUDGET       PIC 9(9).
          03 DB2-ALA-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-ALA-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-ALA-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-ALA-TERRITORY-CODE           PIC X(3).
