******************************************************************
*  COPYBOOK  : GAMAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : MA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-AMA-POLICY.

          03 DB2-AMA-ISSUE-DATE               PIC X(10).
          03 DB2-AMA-EXPIRY-DATE              PIC X(10).
          03 DB2-AMA-LASTCHANGED              PIC X(26).
          03 DB2-AMA-BROKERID                 PIC 9(10).
          03 DB2-AMA-BROKERSREF               PIC X(10).
          03 DB2-AMA-PAYMENT                  PIC 9(6).
          03 DB2-AMA-MEDIA-EXPOSURE-IND       PIC X(1).
          03 DB2-AMA-ADVERTISING-BUDGET       PIC 9(9).
          03 DB2-AMA-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-AMA-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-AMA-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-AMA-TERRITORY-CODE           PIC X(3).
