******************************************************************
*  COPYBOOK  : GAMEC001
*  KIND      : COMMAREA
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : ME
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-AME-REQUEST-ID        PIC X(6).
     03 CA-AME-RETURN-CODE       PIC 9(2).
     03 CA-AME-POLICY-NUM        PIC 9(10).
     03 CA-AME-CUSTOMER-NUM      PIC 9(10).

          03 CA-AME-ISSUE-DATE                PIC X(10).
          03 CA-AME-EXPIRY-DATE               PIC X(10).
          03 CA-AME-LASTCHANGED               PIC X(26).
          03 CA-AME-BROKERID                  PIC 9(10).
          03 CA-AME-BROKERSREF                PIC X(10).
          03 CA-AME-PAYMENT                   PIC 9(6).
          03 CA-AME-MEDIA-EXPOSURE-IND        PIC X(1).
          03 CA-AME-ADVERTISING-BUDGET        PIC 9(9).
          03 CA-AME-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-AME-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-AME-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-AME-TERRITORY-CODE            PIC X(3).
