******************************************************************
*  COPYBOOK  : GAMEP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : ME
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-AME-POLICY.

          03 DB2-AME-ISSUE-DATE               PIC X(10).
          03 DB2-AME-EXPIRY-DATE              PIC X(10).
          03 DB2-AME-LASTCHANGED              PIC X(26).
          03 DB2-AME-BROKERID                 PIC 9(10).
          03 DB2-AME-BROKERSREF               PIC X(10).
          03 DB2-AME-PAYMENT                  PIC 9(6).
          03 DB2-AME-MEDIA-EXPOSURE-IND       PIC X(1).
          03 DB2-AME-ADVERTISING-BUDGET       PIC 9(9).
          03 DB2-AME-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-AME-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-AME-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-AME-TERRITORY-CODE           PIC X(3).
