******************************************************************
*  COPYBOOK  : GAMNC001
*  KIND      : COMMAREA
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : MN
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-AMN-REQUEST-ID        PIC X(6).
     03 CA-AMN-RETURN-CODE       PIC 9(2).
     03 CA-AMN-POLICY-NUM        PIC 9(10).
     03 CA-AMN-CUSTOMER-NUM      PIC 9(10).

          03 CA-AMN-ISSUE-DATE                PIC X(10).
          03 CA-AMN-EXPIRY-DATE               PIC X(10).
          03 CA-AMN-LASTCHANGED               PIC X(26).
          03 CA-AMN-BROKERID                  PIC 9(10).
          03 CA-AMN-BROKERSREF                PIC X(10).
          03 CA-AMN-PAYMENT                   PIC 9(6).
          03 CA-AMN-MEDIA-EXPOSURE-IND        PIC X(1).
          03 CA-AMN-ADVERTISING-BUDGET        PIC 9(9).
          03 CA-AMN-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-AMN-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-AMN-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-AMN-TERRITORY-CODE            PIC X(3).
