******************************************************************
*  COPYBOOK  : GAMOC001
*  KIND      : COMMAREA
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : MO
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-AMO-REQUEST-ID        PIC X(6).
     03 CA-AMO-RETURN-CODE       PIC 9(2).
     03 CA-AMO-POLICY-NUM        PIC 9(10).
     03 CA-AMO-CUSTOMER-NUM      PIC 9(10).

          03 CA-AMO-ISSUE-DATE                PIC X(10).
          03 CA-AMO-EXPIRY-DATE               PIC X(10).
          03 CA-AMO-LASTCHANGED               PIC X(26).
          03 CA-AMO-BROKERID                  PIC 9(10).
          03 CA-AMO-BROKERSREF                PIC X(10).
          03 CA-AMO-PAYMENT                   PIC 9(6).
          03 CA-AMO-MEDIA-EXPOSURE-IND        PIC X(1).
          03 CA-AMO-ADVERTISING-BUDGET        PIC 9(9).
          03 CA-AMO-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-AMO-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-AMO-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-AMO-TERRITORY-CODE            PIC X(3).
