******************************************************************
*  COPYBOOK  : GANCP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : NC
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-ANC-POLICY.

          03 DB2-ANC-ISSUE-DATE               PIC X(10).
          03 DB2-ANC-EXPIRY-DATE              PIC X(10).
          03 DB2-ANC-LASTCHANGED              PIC X(26).
          03 DB2-ANC-BROKERID                 PIC 9(10).
          03 DB2-ANC-BROKERSREF               PIC X(10).
          03 DB2-ANC-PAYMENT                  PIC 9(6).
          03 DB2-ANC-MEDIA-EXPOSURE-IND       PIC X(1).
          03 DB2-ANC-ADVERTISING-BUDGET       PIC 9(9).
          03 DB2-ANC-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-ANC-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-ANC-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-ANC-TERRITORY-CODE           PIC X(3).
