******************************************************************
*  COPYBOOK  : GANDP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : ND
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-AND-POLICY.

          03 DB2-AND-ISSUE-DATE               PIC X(10).
          03 DB2-AND-EXPIRY-DATE              PIC X(10).
          03 DB2-AND-LASTCHANGED              PIC X(26).
          03 DB2-AND-BROKERID                 PIC 9(10).
          03 DB2-AND-BROKERSREF               PIC X(10).
          03 DB2-AND-PAYMENT                  PIC 9(6).
          03 DB2-AND-MEDIA-EXPOSURE-IND       PIC X(1).
          03 DB2-AND-ADVERTISING-BUDGET       PIC 9(9).
          03 DB2-AND-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-AND-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-AND-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-AND-TERRITORY-CODE           PIC X(3).
