******************************************************************
*  COPYBOOK  : GANEC001
*  KIND      : COMMAREA
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : NE
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-ANE-REQUEST-ID        PIC X(6).
     03 CA-ANE-RETURN-CODE       PIC 9(2).
     03 CA-ANE-POLICY-NUM        PIC 9(10).
     03 CA-ANE-CUSTOMER-NUM      PIC 9(10).

          03 CA-ANE-ISSUE-DATE                PIC X(10).
          03 CA-ANE-EXPIRY-DATE               PIC X(10).
          03 CA-ANE-LASTCHANGED               PIC X(26).
          03 CA-ANE-BROKERID                  PIC 9(10).
          03 CA-ANE-BROKERSREF                PIC X(10).
          03 CA-ANE-PAYMENT                   PIC 9(6).
          03 CA-ANE-MEDIA-EXPOSURE-IND        PIC X(1).
          03 CA-ANE-ADVERTISING-BUDGET        PIC 9(9).
          03 CA-ANE-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-ANE-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-ANE-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-ANE-TERRITORY-CODE            PIC X(3).
