******************************************************************
*  COPYBOOK  : GANHC001
*  KIND      : COMMAREA
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : NH
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-ANH-REQUEST-ID        PIC X(6).
     03 CA-ANH-RETURN-CODE       PIC 9(2).
     03 CA-ANH-POLICY-NUM        PIC 9(10).
     03 CA-ANH-CUSTOMER-NUM      PIC 9(10).

          03 CA-ANH-ISSUE-DATE                PIC X(10).
          03 CA-ANH-EXPIRY-DATE               PIC X(10).
          03 CA-ANH-LASTCHANGED               PIC X(26).
          03 CA-ANH-BROKERID                  PIC 9(10).
          03 CA-ANH-BROKERSREF                PIC X(10).
          03 CA-ANH-PAYMENT                   PIC 9(6).
          03 CA-ANH-MEDIA-EXPOSURE-IND        PIC X(1).
          03 CA-ANH-ADVERTISING-BUDGET        PIC 9(9).
          03 CA-ANH-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-ANH-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-ANH-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-ANH-TERRITORY-CODE            PIC X(3).
