******************************************************************
*  COPYBOOK  : GANJP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : NJ
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-ANJ-POLICY.

          03 DB2-ANJ-ISSUE-DATE               PIC X(10).
          03 DB2-ANJ-EXPIRY-DATE              PIC X(10).
          03 DB2-ANJ-LASTCHANGED              PIC X(26).
          03 DB2-ANJ-BROKERID                 PIC 9(10).
          03 DB2-ANJ-BROKERSREF               PIC X(10).
          03 DB2-ANJ-PAYMENT                  PIC 9(6).
          03 DB2-ANJ-MEDIA-EXPOSURE-IND       PIC X(1).
          03 DB2-ANJ-ADVERTISING-BUDGET       PIC 9(9).
          03 DB2-ANJ-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-ANJ-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-ANJ-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-ANJ-TERRITORY-CODE           PIC X(3).
