******************************************************************
*  COPYBOOK  : GANJC001
*  KIND      : COMMAREA
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : NJ
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-ANJ-REQUEST-ID        PIC X(6).
     03 CA-ANJ-RETURN-CODE       PIC 9(2).
     03 CA-ANJ-POLICY-NUM        PIC 9(10).
     03 CA-ANJ-CUSTOMER-NUM      PIC 9(10).

          03 CA-ANJ-ISSUE-DATE                PIC X(10).
          03 CA-ANJ-EXPIRY-DATE               PIC X(10).
          03 CA-ANJ-LASTCHANGED               PIC X(26).
          03 CA-ANJ-BROKERID                  PIC 9(10).
          03 CA-ANJ-BROKERSREF                PIC X(10).
          03 CA-ANJ-PAYMENT                   PIC 9(6).
          03 CA-ANJ-MEDIA-EXPOSURE-IND        PIC X(1).
          03 CA-ANJ-ADVERTISING-BUDGET        PIC 9(9).
          03 CA-ANJ-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-ANJ-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-ANJ-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-ANJ-TERRITORY-CODE            PIC X(3).
