******************************************************************
*  COPYBOOK  : GANMC001
*  KIND      : COMMAREA
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : NM
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-ANM-REQUEST-ID        PIC X(6).
     03 CA-ANM-RETURN-CODE       PIC 9(2).
     03 CA-ANM-POLICY-NUM        PIC 9(10).
     03 CA-ANM-CUSTOMER-NUM      PIC 9(10).

          03 CA-ANM-ISSUE-DATE                PIC X(10).
          03 CA-ANM-EXPIRY-DATE               PIC X(10).
          03 CA-ANM-LASTCHANGED               PIC X(26).
          03 CA-ANM-BROKERID                  PIC 9(10).
          03 CA-ANM-BROKERSREF                PIC X(10).
          03 CA-ANM-PAYMENT                   PIC 9(6).
          03 CA-ANM-MEDIA-EXPOSURE-IND        PIC X(1).
          03 CA-ANM-ADVERTISING-BUDGET        PIC 9(9).
          03 CA-ANM-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-ANM-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-ANM-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-ANM-TERRITORY-CODE            PIC X(3).
