******************************************************************
*  COPYBOOK  : GANVP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : NV
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-ANV-POLICY.

          03 DB2-ANV-ISSUE-DATE               PIC X(10).
          03 DB2-ANV-EXPIRY-DATE              PIC X(10).
          03 DB2-ANV-LASTCHANGED              PIC X(26).
          03 DB2-ANV-BROKERID                 PIC 9(10).
          03 DB2-ANV-BROKERSREF               PIC X(10).
          03 DB2-ANV-PAYMENT                  PIC 9(6).
          03 DB2-ANV-MEDIA-EXPOSURE-IND       PIC X(1).
          03 DB2-ANV-ADVERTISING-BUDGET       PIC 9(9).
          03 DB2-ANV-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-ANV-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-ANV-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-ANV-TERRITORY-CODE           PIC X(3).
