******************************************************************
*  COPYBOOK  : GANYC001
*  KIND      : COMMAREA
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : NY
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-ANY-REQUEST-ID        PIC X(6).
     03 CA-ANY-RETURN-CODE       PIC 9(2).
     03 CA-ANY-POLICY-NUM        PIC 9(10).
     03 CA-ANY-CUSTOMER-NUM      PIC 9(10).

          03 CA-ANY-ISSUE-DATE                PIC X(10).
          03 CA-ANY-EXPIRY-DATE               PIC X(10).
          03 CA-ANY-LASTCHANGED               PIC X(26).
          03 CA-ANY-BROKERID                  PIC 9(10).
          03 CA-ANY-BROKERSREF                PIC X(10).
          03 CA-ANY-PAYMENT                   PIC 9(6).
          03 CA-ANY-MEDIA-EXPOSURE-IND        PIC X(1).
          03 CA-ANY-ADVERTISING-BUDGET        PIC 9(9).
          03 CA-ANY-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-ANY-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-ANY-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-ANY-TERRITORY-CODE            PIC X(3).
