******************************************************************
*  COPYBOOK  : GARIP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : RI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-ARI-POLICY.

          03 DB2-ARI-ISSUE-DATE               PIC X(10).
          03 DB2-ARI-EXPIRY-DATE              PIC X(10).
          03 DB2-ARI-LASTCHANGED              PIC X(26).
          03 DB2-ARI-BROKERID                 PIC 9(10).
          03 DB2-ARI-BROKERSREF               PIC X(10).
          03 DB2-ARI-PAYMENT                  PIC 9(6).
          03 DB2-ARI-MEDIA-EXPOSURE-IND       PIC X(1).
          03 DB2-ARI-ADVERTISING-BUDGET       PIC 9(9).
          03 DB2-ARI-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-ARI-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-ARI-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-ARI-TERRITORY-CODE           PIC X(3).
