******************************************************************
*  COPYBOOK  : GASCC001
*  KIND      : COMMAREA
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : SC
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-ASC-REQUEST-ID        PIC X(6).
     03 CA-ASC-RETURN-CODE       PIC 9(2).
     03 CA-ASC-POLICY-NUM        PIC 9(10).
     03 CA-ASC-CUSTOMER-NUM      PIC 9(10).

          03 CA-ASC-ISSUE-DATE                PIC X(10).
          03 CA-ASC-EXPIRY-DATE               PIC X(10).
          03 CA-ASC-LASTCHANGED               PIC X(26).
          03 CA-ASC-BROKERID                  PIC 9(10).
          03 CA-ASC-BROKERSREF                PIC X(10).
          03 CA-ASC-PAYMENT                   PIC 9(6).
          03 CA-ASC-MEDIA-EXPOSURE-IND        PIC X(1).
          03 CA-ASC-ADVERTISING-BUDGET        PIC 9(9).
          03 CA-ASC-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-ASC-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-ASC-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-ASC-TERRITORY-CODE            PIC X(3).
