******************************************************************
*  COPYBOOK  : GASDC001
*  KIND      : COMMAREA
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : SD
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-ASD-REQUEST-ID        PIC X(6).
     03 CA-ASD-RETURN-CODE       PIC 9(2).
     03 CA-ASD-POLICY-NUM        PIC 9(10).
     03 CA-ASD-CUSTOMER-NUM      PIC 9(10).

          03 CA-ASD-ISSUE-DATE                PIC X(10).
          03 CA-ASD-EXPIRY-DATE               PIC X(10).
          03 CA-ASD-LASTCHANGED               PIC X(26).
          03 CA-ASD-BROKERID                  PIC 9(10).
          03 CA-ASD-BROKERSREF                PIC X(10).
          03 CA-ASD-PAYMENT                   PIC 9(6).
          03 CA-ASD-MEDIA-EXPOSURE-IND        PIC X(1).
          03 CA-ASD-ADVERTISING-BUDGET        PIC 9(9).
          03 CA-ASD-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-ASD-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-ASD-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-ASD-TERRITORY-CODE            PIC X(3).
