******************************************************************
*  COPYBOOK  : GATXC001
*  KIND      : COMMAREA
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : TX
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-ATX-REQUEST-ID        PIC X(6).
     03 CA-ATX-RETURN-CODE       PIC 9(2).
     03 CA-ATX-POLICY-NUM        PIC 9(10).
     03 CA-ATX-CUSTOMER-NUM      PIC 9(10).

          03 CA-ATX-ISSUE-DATE                PIC X(10).
          03 CA-ATX-EXPIRY-DATE               PIC X(10).
          03 CA-ATX-LASTCHANGED               PIC X(26).
          03 CA-ATX-BROKERID                  PIC 9(10).
          03 CA-ATX-BROKERSREF                PIC X(10).
          03 CA-ATX-PAYMENT                   PIC 9(6).
          03 CA-ATX-MEDIA-EXPOSURE-IND        PIC X(1).
          03 CA-ATX-ADVERTISING-BUDGET        PIC 9(9).
          03 CA-ATX-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-ATX-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-ATX-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-ATX-TERRITORY-CODE            PIC X(3).
