******************************************************************
*  COPYBOOK  : GAVTC001
*  KIND      : COMMAREA
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : VT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-AVT-REQUEST-ID        PIC X(6).
     03 CA-AVT-RETURN-CODE       PIC 9(2).
     03 CA-AVT-POLICY-NUM        PIC 9(10).
     03 CA-AVT-CUSTOMER-NUM      PIC 9(10).

          03 CA-AVT-ISSUE-DATE                PIC X(10).
          03 CA-AVT-EXPIRY-DATE               PIC X(10).
          03 CA-AVT-LASTCHANGED               PIC X(26).
          03 CA-AVT-BROKERID                  PIC 9(10).
          03 CA-AVT-BROKERSREF                PIC X(10).
          03 CA-AVT-PAYMENT                   PIC 9(6).
          03 CA-AVT-MEDIA-EXPOSURE-IND        PIC X(1).
          03 CA-AVT-ADVERTISING-BUDGET        PIC 9(9).
          03 CA-AVT-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-AVT-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-AVT-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-AVT-TERRITORY-CODE            PIC X(3).
