******************************************************************
*  COPYBOOK  : GAVTP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : VT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-AVT-POLICY.

          03 DB2-AVT-ISSUE-DATE               PIC X(10).
          03 DB2-AVT-EXPIRY-DATE              PIC X(10).
          03 DB2-AVT-LASTCHANGED              PIC X(26).
          03 DB2-AVT-BROKERID                 PIC 9(10).
          03 DB2-AVT-BROKERSREF               PIC X(10).
          03 DB2-AVT-PAYMENT                  PIC 9(6).
          03 DB2-AVT-MEDIA-EXPOSURE-IND       PIC X(1).
          03 DB2-AVT-ADVERTISING-BUDGET       PIC 9(9).
          03 DB2-AVT-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-AVT-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-AVT-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-AVT-TERRITORY-CODE           PIC X(3).
