******************************************************************
*  COPYBOOK  : GAWIP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : WI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-AWI-POLICY.

          03 DB2-AWI-ISSUE-DATE               PIC X(10).
          03 DB2-AWI-EXPIRY-DATE              PIC X(10).
          03 DB2-AWI-LASTCHANGED              PIC X(26).
          03 DB2-AWI-BROKERID                 PIC 9(10).
          03 DB2-AWI-BROKERSREF               PIC X(10).
          03 DB2-AWI-PAYMENT                  PIC 9(6).
          03 DB2-AWI-MEDIA-EXPOSURE-IND       PIC X(1).
          03 DB2-AWI-ADVERTISING-BUDGET       PIC 9(9).
          03 DB2-AWI-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-AWI-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-AWI-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-AWI-TERRITORY-CODE           PIC X(3).
