******************************************************************
*  COPYBOOK  : GAWIC001
*  KIND      : COMMAREA
*  COVERAGE  : Personal and Advertising Injury Liability (PA)
*  STATE     : WI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-AWI-REQUEST-ID        PIC X(6).
     03 CA-AWI-RETURN-CODE       PIC 9(2).
     03 CA-AWI-POLICY-NUM        PIC 9(10).
     03 CA-AWI-CUSTOMER-NUM      PIC 9(10).

          03 CA-AWI-ISSUE-DATE                PIC X(10).
          03 CA-AWI-EXPIRY-DATE               PIC X(10).
          03 CA-AWI-LASTCHANGED               PIC X(26).
          03 CA-AWI-BROKERID                  PIC 9(10).
          03 CA-AWI-BROKERSREF                PIC X(10).
          03 CA-AWI-PAYMENT                   PIC 9(6).
          03 CA-AWI-MEDIA-EXPOSURE-IND        PIC X(1).
          03 CA-AWI-ADVERTISING-BUDGET        PIC 9(9).
          03 CA-AWI-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-AWI-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-AWI-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-AWI-TERRITORY-CODE            PIC X(3).
