******************************************************************
*  COPYBOOK  : GUALP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : AL
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-UAL-POLICY.

          03 DB2-UAL-ISSUE-DATE               PIC X(10).
          03 DB2-UAL-EXPIRY-DATE              PIC X(10).
          03 DB2-UAL-LASTCHANGED              PIC X(26).
          03 DB2-UAL-BROKERID                 PIC 9(10).
          03 DB2-UAL-BROKERSREF               PIC X(10).
          03 DB2-UAL-PAYMENT                  PIC 9(6).
          03 DB2-UAL-ATTACHMENT-POINT         PIC 9(9).
          03 DB2-UAL-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-UAL-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-UAL-UNDERLYING-CARRIER       PIC X(20).
          03 DB2-UAL-BASE-RATE                PIC 9(4)V9(4).
