******************************************************************
*  COPYBOOK  : GUALC001
*  KIND      : COMMAREA
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : AL
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-UAL-REQUEST-ID        PIC X(6).
     03 CA-UAL-RETURN-CODE       PIC 9(2).
     03 CA-UAL-POLICY-NUM        PIC 9(10).
     03 CA-UAL-CUSTOMER-NUM      PIC 9(10).

          03 CA-UAL-ISSUE-DATE                PIC X(10).
          03 CA-UAL-EXPIRY-DATE               PIC X(10).
          03 CA-UAL-LASTCHANGED               PIC X(26).
          03 CA-UAL-BROKERID                  PIC 9(10).
          03 CA-UAL-BROKERSREF                PIC X(10).
          03 CA-UAL-PAYMENT                   PIC 9(6).
          03 CA-UAL-ATTACHMENT-POINT          PIC 9(9).
          03 CA-UAL-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-UAL-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-UAL-UNDERLYING-CARRIER        PIC X(20).
          03 CA-UAL-BASE-RATE                 PIC 9(4)V9(4).
