******************************************************************
*  COPYBOOK  : GUCAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : CA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-UCA-POLICY.

          03 DB2-UCA-ISSUE-DATE               PIC X(10).
          03 DB2-UCA-EXPIRY-DATE              PIC X(10).
          03 DB2-UCA-LASTCHANGED              PIC X(26).
          03 DB2-UCA-BROKERID                 PIC 9(10).
          03 DB2-UCA-BROKERSREF               PIC X(10).
          03 DB2-UCA-PAYMENT                  PIC 9(6).
          03 DB2-UCA-ATTACHMENT-POINT         PIC 9(9).
          03 DB2-UCA-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-UCA-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-UCA-UNDERLYING-CARRIER       PIC X(20).
          03 DB2-UCA-BASE-RATE                PIC 9(4)V9(4).
