******************************************************************
*  COPYBOOK  : GUDEP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : DE
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-UDE-POLICY.

          03 DB2-UDE-ISSUE-DATE               PIC X(10).
          03 DB2-UDE-EXPIRY-DATE              PIC X(10).
          03 DB2-UDE-LASTCHANGED              PIC X(26).
          03 DB2-UDE-BROKERID                 PIC 9(10).
          03 DB2-UDE-BROKERSREF               PIC X(10).
          03 DB2-UDE-PAYMENT                  PIC 9(6).
          03 DB2-UDE-ATTACHMENT-POINT         PIC 9(9).
          03 DB2-UDE-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-UDE-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-UDE-UNDERLYING-CARRIER       PIC X(20).
          03 DB2-UDE-BASE-RATE                PIC 9(4)V9(4).
