******************************************************************
*  COPYBOOK  : GUFLP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : FL
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-UFL-POLICY.

          03 DB2-UFL-ISSUE-DATE               PIC X(10).
          03 DB2-UFL-EXPIRY-DATE              PIC X(10).
          03 DB2-UFL-LASTCHANGED              PIC X(26).
          03 DB2-UFL-BROKERID                 PIC 9(10).
          03 DB2-UFL-BROKERSREF               PIC X(10).
          03 DB2-UFL-PAYMENT                  PIC 9(6).
          03 DB2-UFL-ATTACHMENT-POINT         PIC 9(9).
          03 DB2-UFL-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-UFL-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-UFL-UNDERLYING-CARRIER       PIC X(20).
          03 DB2-UFL-BASE-RATE                PIC 9(4)V9(4).
