******************************************************************
*  COPYBOOK  : GUFLC001
*  KIND      : COMMAREA
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : FL
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-UFL-REQUEST-ID        PIC X(6).
     03 CA-UFL-RETURN-CODE       PIC 9(2).
     03 CA-UFL-POLICY-NUM        PIC 9(10).
     03 CA-UFL-CUSTOMER-NUM      PIC 9(10).

          03 CA-UFL-ISSUE-DATE                PIC X(10).
          03 CA-UFL-EXPIRY-DATE               PIC X(10).
          03 CA-UFL-LASTCHANGED               PIC X(26).
          03 CA-UFL-BROKERID                  PIC 9(10).
          03 CA-UFL-BROKERSREF                PIC X(10).
          03 CA-UFL-PAYMENT                   PIC 9(6).
          03 CA-UFL-ATTACHMENT-POINT          PIC 9(9).
          03 CA-UFL-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-UFL-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-UFL-UNDERLYING-CARRIER        PIC X(20).
          03 CA-UFL-BASE-RATE                 PIC 9(4)V9(4).
