******************************************************************
*  COPYBOOK  : GUGAC001
*  KIND      : COMMAREA
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : GA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-UGA-REQUEST-ID        PIC X(6).
     03 CA-UGA-RETURN-CODE       PIC 9(2).
     03 CA-UGA-POLICY-NUM        PIC 9(10).
     03 CA-UGA-CUSTOMER-NUM      PIC 9(10).

          03 CA-UGA-ISSUE-DATE                PIC X(10).
          03 CA-UGA-EXPIRY-DATE               PIC X(10).
          03 CA-UGA-LASTCHANGED               PIC X(26).
          03 CA-UGA-BROKERID                  PIC 9(10).
          03 CA-UGA-BROKERSREF                PIC X(10).
          03 CA-UGA-PAYMENT                   PIC 9(6).
          03 CA-UGA-ATTACHMENT-POINT          PIC 9(9).
          03 CA-UGA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-UGA-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-UGA-UNDERLYING-CARRIER        PIC X(20).
          03 CA-UGA-BASE-RATE                 PIC 9(4)V9(4).
