******************************************************************
*  COPYBOOK  : GUHIC001
*  KIND      : COMMAREA
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : HI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-UHI-REQUEST-ID        PIC X(6).
     03 CA-UHI-RETURN-CODE       PIC 9(2).
     03 CA-UHI-POLICY-NUM        PIC 9(10).
     03 CA-UHI-CUSTOMER-NUM      PIC 9(10).

          03 CA-UHI-ISSUE-DATE                PIC X(10).
          03 CA-UHI-EXPIRY-DATE               PIC X(10).
          03 CA-UHI-LASTCHANGED               PIC X(26).
          03 CA-UHI-BROKERID                  PIC 9(10).
          03 CA-UHI-BROKERSREF                PIC X(10).
          03 CA-UHI-PAYMENT                   PIC 9(6).
          03 CA-UHI-ATTACHMENT-POINT          PIC 9(9).
          03 CA-UHI-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-UHI-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-UHI-UNDERLYING-CARRIER        PIC X(20).
          03 CA-UHI-BASE-RATE                 PIC 9(4)V9(4).
