******************************************************************
*  COPYBOOK  : GUIAC001
*  KIND      : COMMAREA
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : IA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-UIA-REQUEST-ID        PIC X(6).
     03 CA-UIA-RETURN-CODE       PIC 9(2).
     03 CA-UIA-POLICY-NUM        PIC 9(10).
     03 CA-UIA-CUSTOMER-NUM      PIC 9(10).

          03 CA-UIA-ISSUE-DATE                PIC X(10).
          03 CA-UIA-EXPIRY-DATE               PIC X(10).
          03 CA-UIA-LASTCHANGED               PIC X(26).
          03 CA-UIA-BROKERID                  PIC 9(10).
          03 CA-UIA-BROKERSREF                PIC X(10).
          03 CA-UIA-PAYMENT                   PIC 9(6).
          03 CA-UIA-ATTACHMENT-POINT          PIC 9(9).
          03 CA-UIA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-UIA-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-UIA-UNDERLYING-CARRIER        PIC X(20).
          03 CA-UIA-BASE-RATE                 PIC 9(4)V9(4).
