******************************************************************
*  COPYBOOK  : GUKSC001
*  KIND      : COMMAREA
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : KS
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-UKS-REQUEST-ID        PIC X(6).
     03 CA-UKS-RETURN-CODE       PIC 9(2).
     03 CA-UKS-POLICY-NUM        PIC 9(10).
     03 CA-UKS-CUSTOMER-NUM      PIC 9(10).

          03 CA-UKS-ISSUE-DATE                PIC X(10).
          03 CA-UKS-EXPIRY-DATE               PIC X(10).
          03 CA-UKS-LASTCHANGED               PIC X(26).
          03 CA-UKS-BROKERID                  PIC 9(10).
          03 CA-UKS-BROKERSREF                PIC X(10).
          03 CA-UKS-PAYMENT                   PIC 9(6).
          03 CA-UKS-ATTACHMENT-POINT          PIC 9(9).
          03 CA-UKS-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-UKS-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-UKS-UNDERLYING-CARRIER        PIC X(20).
          03 CA-UKS-BASE-RATE                 PIC 9(4)V9(4).
