******************************************************************
*  COPYBOOK  : GUKSP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : KS
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-UKS-POLICY.

          03 DB2-UKS-ISSUE-DATE               PIC X(10).
          03 DB2-UKS-EXPIRY-DATE              PIC X(10).
          03 DB2-UKS-LASTCHANGED              PIC X(26).
          03 DB2-UKS-BROKERID                 PIC 9(10).
          03 DB2-UKS-BROKERSREF               PIC X(10).
          03 DB2-UKS-PAYMENT                  PIC 9(6).
          03 DB2-UKS-ATTACHMENT-POINT         PIC 9(9).
          03 DB2-UKS-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-UKS-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-UKS-UNDERLYING-CARRIER       PIC X(20).
          03 DB2-UKS-BASE-RATE                PIC 9(4)V9(4).
