******************************************************************
*  COPYBOOK  : GULAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : LA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-ULA-POLICY.

          03 DB2-ULA-ISSUE-DATE               PIC X(10).
          03 DB2-ULA-EXPIRY-DATE              PIC X(10).
          03 DB2-ULA-LASTCHANGED              PIC X(26).
          03 DB2-ULA-BROKERID                 PIC 9(10).
          03 DB2-ULA-BROKERSREF               PIC X(10).
          03 DB2-ULA-PAYMENT                  PIC 9(6).
          03 DB2-ULA-ATTACHMENT-POINT         PIC 9(9).
          03 DB2-ULA-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-ULA-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-ULA-UNDERLYING-CARRIER       PIC X(20).
          03 DB2-ULA-BASE-RATE                PIC 9(4)V9(4).
