******************************************************************
*  COPYBOOK  : GUMDC001
*  KIND      : COMMAREA
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : MD
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-UMD-REQUEST-ID        PIC X(6).
     03 CA-UMD-RETURN-CODE       PIC 9(2).
     03 CA-UMD-POLICY-NUM        PIC 9(10).
     03 CA-UMD-CUSTOMER-NUM      PIC 9(10).

          03 CA-UMD-ISSUE-DATE                PIC X(10).
          03 CA-UMD-EXPIRY-DATE               PIC X(10).
          03 CA-UMD-LASTCHANGED               PIC X(26).
          03 CA-UMD-BROKERID                  PIC 9(10).
          03 CA-UMD-BROKERSREF                PIC X(10).
          03 CA-UMD-PAYMENT                   PIC 9(6).
          03 CA-UMD-ATTACHMENT-POINT          PIC 9(9).
          03 CA-UMD-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-UMD-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-UMD-UNDERLYING-CARRIER        PIC X(20).
          03 CA-UMD-BASE-RATE                 PIC 9(4)V9(4).
