******************************************************************
*  COPYBOOK  : GUMIP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : MI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-UMI-POLICY.

          03 DB2-UMI-ISSUE-DATE               PIC X(10).
          03 DB2-UMI-EXPIRY-DATE              PIC X(10).
          03 DB2-UMI-LASTCHANGED              PIC X(26).
          03 DB2-UMI-BROKERID                 PIC 9(10).
          03 DB2-UMI-BROKERSREF               PIC X(10).
          03 DB2-UMI-PAYMENT                  PIC 9(6).
          03 DB2-UMI-ATTACHMENT-POINT         PIC 9(9).
          03 DB2-UMI-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-UMI-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-UMI-UNDERLYING-CARRIER       PIC X(20).
          03 DB2-UMI-BASE-RATE                PIC 9(4)V9(4).
