******************************************************************
*  COPYBOOK  : GUNEP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : NE
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-UNE-POLICY.

          03 DB2-UNE-ISSUE-DATE               PIC X(10).
          03 DB2-UNE-EXPIRY-DATE              PIC X(10).
          03 DB2-UNE-LASTCHANGED              PIC X(26).
          03 DB2-UNE-BROKERID                 PIC 9(10).
          03 DB2-UNE-BROKERSREF               PIC X(10).
          03 DB2-UNE-PAYMENT                  PIC 9(6).
          03 DB2-UNE-ATTACHMENT-POINT         PIC 9(9).
          03 DB2-UNE-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-UNE-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-UNE-UNDERLYING-CARRIER       PIC X(20).
          03 DB2-UNE-BASE-RATE                PIC 9(4)V9(4).
