******************************************************************
*  COPYBOOK  : GUNEC001
*  KIND      : COMMAREA
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : NE
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-UNE-REQUEST-ID        PIC X(6).
     03 CA-UNE-RETURN-CODE       PIC 9(2).
     03 CA-UNE-POLICY-NUM        PIC 9(10).
     03 CA-UNE-CUSTOMER-NUM      PIC 9(10).

          03 CA-UNE-ISSUE-DATE                PIC X(10).
          03 CA-UNE-EXPIRY-DATE               PIC X(10).
          03 CA-UNE-LASTCHANGED               PIC X(26).
          03 CA-UNE-BROKERID                  PIC 9(10).
          03 CA-UNE-BROKERSREF                PIC X(10).
          03 CA-UNE-PAYMENT                   PIC 9(6).
          03 CA-UNE-ATTACHMENT-POINT          PIC 9(9).
          03 CA-UNE-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-UNE-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-UNE-UNDERLYING-CARRIER        PIC X(20).
          03 CA-UNE-BASE-RATE                 PIC 9(4)V9(4).
