******************************************************************
*  COPYBOOK  : GUNHP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : NH
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-UNH-POLICY.

          03 DB2-UNH-ISSUE-DATE               PIC X(10).
          03 DB2-UNH-EXPIRY-DATE              PIC X(10).
          03 DB2-UNH-LASTCHANGED              PIC X(26).
          03 DB2-UNH-BROKERID                 PIC 9(10).
          03 DB2-UNH-BROKERSREF               PIC X(10).
          03 DB2-UNH-PAYMENT                  PIC 9(6).
          03 DB2-UNH-ATTACHMENT-POINT         PIC 9(9).
          03 DB2-UNH-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-UNH-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-UNH-UNDERLYING-CARRIER       PIC X(20).
          03 DB2-UNH-BASE-RATE                PIC 9(4)V9(4).
