******************************************************************
*  COPYBOOK  : GUNVP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : NV
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-UNV-POLICY.

          03 DB2-UNV-ISSUE-DATE               PIC X(10).
          03 DB2-UNV-EXPIRY-DATE              PIC X(10).
          03 DB2-UNV-LASTCHANGED              PIC X(26).
          03 DB2-UNV-BROKERID                 PIC 9(10).
          03 DB2-UNV-BROKERSREF               PIC X(10).
          03 DB2-UNV-PAYMENT                  PIC 9(6).
          03 DB2-UNV-ATTACHMENT-POINT         PIC 9(9).
          03 DB2-UNV-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-UNV-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-UNV-UNDERLYING-CARRIER       PIC X(20).
          03 DB2-UNV-BASE-RATE                PIC 9(4)V9(4).
