******************************************************************
*  COPYBOOK  : GUNVC001
*  KIND      : COMMAREA
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : NV
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-UNV-REQUEST-ID        PIC X(6).
     03 CA-UNV-RETURN-CODE       PIC 9(2).
     03 CA-UNV-POLICY-NUM        PIC 9(10).
     03 CA-UNV-CUSTOMER-NUM      PIC 9(10).

          03 CA-UNV-ISSUE-DATE                PIC X(10).
          03 CA-UNV-EXPIRY-DATE               PIC X(10).
          03 CA-UNV-LASTCHANGED               PIC X(26).
          03 CA-UNV-BROKERID                  PIC 9(10).
          03 CA-UNV-BROKERSREF                PIC X(10).
          03 CA-UNV-PAYMENT                   PIC 9(6).
          03 CA-UNV-ATTACHMENT-POINT          PIC 9(9).
          03 CA-UNV-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-UNV-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-UNV-UNDERLYING-CARRIER        PIC X(20).
          03 CA-UNV-BASE-RATE                 PIC 9(4)V9(4).
