******************************************************************
*  COPYBOOK  : GUOHC001
*  KIND      : COMMAREA
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : OH
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-UOH-REQUEST-ID        PIC X(6).
     03 CA-UOH-RETURN-CODE       PIC 9(2).
     03 CA-UOH-POLICY-NUM        PIC 9(10).
     03 CA-UOH-CUSTOMER-NUM      PIC 9(10).

          03 CA-UOH-ISSUE-DATE                PIC X(10).
          03 CA-UOH-EXPIRY-DATE               PIC X(10).
          03 CA-UOH-LASTCHANGED               PIC X(26).
          03 CA-UOH-BROKERID                  PIC 9(10).
          03 CA-UOH-BROKERSREF                PIC X(10).
          03 CA-UOH-PAYMENT                   PIC 9(6).
          03 CA-UOH-ATTACHMENT-POINT          PIC 9(9).
          03 CA-UOH-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-UOH-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-UOH-UNDERLYING-CARRIER        PIC X(20).
          03 CA-UOH-BASE-RATE                 PIC 9(4)V9(4).
