******************************************************************
*  COPYBOOK  : GUORC001
*  KIND      : COMMAREA
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : OR
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-UOR-REQUEST-ID        PIC X(6).
     03 CA-UOR-RETURN-CODE       PIC 9(2).
     03 CA-UOR-POLICY-NUM        PIC 9(10).
     03 CA-UOR-CUSTOMER-NUM      PIC 9(10).

          03 CA-UOR-ISSUE-DATE                PIC X(10).
          03 CA-UOR-EXPIRY-DATE               PIC X(10).
          03 CA-UOR-LASTCHANGED               PIC X(26).
          03 CA-UOR-BROKERID                  PIC 9(10).
          03 CA-UOR-BROKERSREF                PIC X(10).
          03 CA-UOR-PAYMENT                   PIC 9(6).
          03 CA-UOR-ATTACHMENT-POINT          PIC 9(9).
          03 CA-UOR-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-UOR-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-UOR-UNDERLYING-CARRIER        PIC X(20).
          03 CA-UOR-BASE-RATE                 PIC 9(4)V9(4).
