******************************************************************
*  COPYBOOK  : GUPAC001
*  KIND      : COMMAREA
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : PA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-UPA-REQUEST-ID        PIC X(6).
     03 CA-UPA-RETURN-CODE       PIC 9(2).
     03 CA-UPA-POLICY-NUM        PIC 9(10).
     03 CA-UPA-CUSTOMER-NUM      PIC 9(10).

          03 CA-UPA-ISSUE-DATE                PIC X(10).
          03 CA-UPA-EXPIRY-DATE               PIC X(10).
          03 CA-UPA-LASTCHANGED               PIC X(26).
          03 CA-UPA-BROKERID                  PIC 9(10).
          03 CA-UPA-BROKERSREF                PIC X(10).
          03 CA-UPA-PAYMENT                   PIC 9(6).
          03 CA-UPA-ATTACHMENT-POINT          PIC 9(9).
          03 CA-UPA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-UPA-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-UPA-UNDERLYING-CARRIER        PIC X(20).
          03 CA-UPA-BASE-RATE                 PIC 9(4)V9(4).
