******************************************************************
*  COPYBOOK  : GURIC001
*  KIND      : COMMAREA
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : RI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-URI-REQUEST-ID        PIC X(6).
     03 CA-URI-RETURN-CODE       PIC 9(2).
     03 CA-URI-POLICY-NUM        PIC 9(10).
     03 CA-URI-CUSTOMER-NUM      PIC 9(10).

          03 CA-URI-ISSUE-DATE                PIC X(10).
          03 CA-URI-EXPIRY-DATE               PIC X(10).
          03 CA-URI-LASTCHANGED               PIC X(26).
          03 CA-URI-BROKERID                  PIC 9(10).
          03 CA-URI-BROKERSREF                PIC X(10).
          03 CA-URI-PAYMENT                   PIC 9(6).
          03 CA-URI-ATTACHMENT-POINT          PIC 9(9).
          03 CA-URI-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-URI-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-URI-UNDERLYING-CARRIER        PIC X(20).
          03 CA-URI-BASE-RATE                 PIC 9(4)V9(4).
