******************************************************************
*  COPYBOOK  : GURIP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : RI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-URI-POLICY.

          03 DB2-URI-ISSUE-DATE               PIC X(10).
          03 DB2-URI-EXPIRY-DATE              PIC X(10).
          03 DB2-URI-LASTCHANGED              PIC X(26).
          03 DB2-URI-BROKERID                 PIC 9(10).
          03 DB2-URI-BROKERSREF               PIC X(10).
          03 DB2-URI-PAYMENT                  PIC 9(6).
          03 DB2-URI-ATTACHMENT-POINT         PIC 9(9).
          03 DB2-URI-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-URI-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-URI-UNDERLYING-CARRIER       PIC X(20).
          03 DB2-URI-BASE-RATE                PIC 9(4)V9(4).
