******************************************************************
*  COPYBOOK  : GUSCC001
*  KIND      : COMMAREA
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : SC
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-USC-REQUEST-ID        PIC X(6).
     03 CA-USC-RETURN-CODE       PIC 9(2).
     03 CA-USC-POLICY-NUM        PIC 9(10).
     03 CA-USC-CUSTOMER-NUM      PIC 9(10).

          03 CA-USC-ISSUE-DATE                PIC X(10).
          03 CA-USC-EXPIRY-DATE               PIC X(10).
          03 CA-USC-LASTCHANGED               PIC X(26).
          03 CA-USC-BROKERID                  PIC 9(10).
          03 CA-USC-BROKERSREF                PIC X(10).
          03 CA-USC-PAYMENT                   PIC 9(6).
          03 CA-USC-ATTACHMENT-POINT          PIC 9(9).
          03 CA-USC-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-USC-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-USC-UNDERLYING-CARRIER        PIC X(20).
          03 CA-USC-BASE-RATE                 PIC 9(4)V9(4).
