******************************************************************
*  COPYBOOK  : GUSCP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : SC
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-USC-POLICY.

          03 DB2-USC-ISSUE-DATE               PIC X(10).
          03 DB2-USC-EXPIRY-DATE              PIC X(10).
          03 DB2-USC-LASTCHANGED              PIC X(26).
          03 DB2-USC-BROKERID                 PIC 9(10).
          03 DB2-USC-BROKERSREF               PIC X(10).
          03 DB2-USC-PAYMENT                  PIC 9(6).
          03 DB2-USC-ATTACHMENT-POINT         PIC 9(9).
          03 DB2-USC-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-USC-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-USC-UNDERLYING-CARRIER       PIC X(20).
          03 DB2-USC-BASE-RATE                PIC 9(4)V9(4).
