******************************************************************
*  COPYBOOK  : GUUTP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : UT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-UUT-POLICY.

          03 DB2-UUT-ISSUE-DATE               PIC X(10).
          03 DB2-UUT-EXPIRY-DATE              PIC X(10).
          03 DB2-UUT-LASTCHANGED              PIC X(26).
          03 DB2-UUT-BROKERID                 PIC 9(10).
          03 DB2-UUT-BROKERSREF               PIC X(10).
          03 DB2-UUT-PAYMENT                  PIC 9(6).
          03 DB2-UUT-ATTACHMENT-POINT         PIC 9(9).
          03 DB2-UUT-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-UUT-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-UUT-UNDERLYING-CARRIER       PIC X(20).
          03 DB2-UUT-BASE-RATE                PIC 9(4)V9(4).
