******************************************************************
*  COPYBOOK  : GUVAC001
*  KIND      : COMMAREA
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : VA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-UVA-REQUEST-ID        PIC X(6).
     03 CA-UVA-RETURN-CODE       PIC 9(2).
     03 CA-UVA-POLICY-NUM        PIC 9(10).
     03 CA-UVA-CUSTOMER-NUM      PIC 9(10).

          03 CA-UVA-ISSUE-DATE                PIC X(10).
          03 CA-UVA-EXPIRY-DATE               PIC X(10).
          03 CA-UVA-LASTCHANGED               PIC X(26).
          03 CA-UVA-BROKERID                  PIC 9(10).
          03 CA-UVA-BROKERSREF                PIC X(10).
          03 CA-UVA-PAYMENT                   PIC 9(6).
          03 CA-UVA-ATTACHMENT-POINT          PIC 9(9).
          03 CA-UVA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-UVA-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-UVA-UNDERLYING-CARRIER        PIC X(20).
          03 CA-UVA-BASE-RATE                 PIC 9(4)V9(4).
