******************************************************************
*  COPYBOOK  : GUVTP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : VT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-UVT-POLICY.

          03 DB2-UVT-ISSUE-DATE               PIC X(10).
          03 DB2-UVT-EXPIRY-DATE              PIC X(10).
          03 DB2-UVT-LASTCHANGED              PIC X(26).
          03 DB2-UVT-BROKERID                 PIC 9(10).
          03 DB2-UVT-BROKERSREF               PIC X(10).
          03 DB2-UVT-PAYMENT                  PIC 9(6).
          03 DB2-UVT-ATTACHMENT-POINT         PIC 9(9).
          03 DB2-UVT-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-UVT-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-UVT-UNDERLYING-CARRIER       PIC X(20).
          03 DB2-UVT-BASE-RATE                PIC 9(4)V9(4).
