******************************************************************
*  COPYBOOK  : GUWIC001
*  KIND      : COMMAREA
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : WI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-UWI-REQUEST-ID        PIC X(6).
     03 CA-UWI-RETURN-CODE       PIC 9(2).
     03 CA-UWI-POLICY-NUM        PIC 9(10).
     03 CA-UWI-CUSTOMER-NUM      PIC 9(10).

          03 CA-UWI-ISSUE-DATE                PIC X(10).
          03 CA-UWI-EXPIRY-DATE               PIC X(10).
          03 CA-UWI-LASTCHANGED               PIC X(26).
          03 CA-UWI-BROKERID                  PIC 9(10).
          03 CA-UWI-BROKERSREF                PIC X(10).
          03 CA-UWI-PAYMENT                   PIC 9(6).
          03 CA-UWI-ATTACHMENT-POINT          PIC 9(9).
          03 CA-UWI-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-UWI-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-UWI-UNDERLYING-CARRIER        PIC X(20).
          03 CA-UWI-BASE-RATE                 PIC 9(4)V9(4).
