******************************************************************
*  COPYBOOK  : GUWYP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Umbrella and Excess Liability (UM)
*  STATE     : WY
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-UWY-POLICY.

          03 DB2-UWY-ISSUE-DATE               PIC X(10).
          03 DB2-UWY-EXPIRY-DATE              PIC X(10).
          03 DB2-UWY-LASTCHANGED              PIC X(26).
          03 DB2-UWY-BROKERID                 PIC 9(10).
          03 DB2-UWY-BROKERSREF               PIC X(10).
          03 DB2-UWY-PAYMENT                  PIC 9(6).
          03 DB2-UWY-ATTACHMENT-POINT         PIC 9(9).
          03 DB2-UWY-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-UWY-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-UWY-UNDERLYING-CARRIER       PIC X(20).
          03 DB2-UWY-BASE-RATE                PIC 9(4)V9(4).
