******************************************************************
*  COPYBOOK  : GRARP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Products and Completed Operations Liability (PC)
*  STATE     : AR
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-RAR-POLICY.

          03 DB2-RAR-ISSUE-DATE               PIC X(10).
          03 DB2-RAR-EXPIRY-DATE              PIC X(10).
          03 DB2-RAR-LASTCHANGED              PIC X(26).
          03 DB2-RAR-BROKERID                 PIC 9(10).
          03 DB2-RAR-BROKERSREF               PIC X(10).
          03 DB2-RAR-PAYMENT                  PIC 9(6).
          03 DB2-RAR-PRODUCT-CLASS-CODE       PIC X(4).
          03 DB2-RAR-HAZARD-GROUP             PIC X(2).
          03 DB2-RAR-SALES-EXPOSURE-AMT       PIC 9(9).
          03 DB2-RAR-COMPLETED-OPS-IND        PIC X(1).
          03 DB2-RAR-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-RAR-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-RAR-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-RAR-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-RAR-PRIOR-CLAIMS-COUNT       PIC 9(3).
