******************************************************************
*  COPYBOOK  : GRARC001
*  KIND      : COMMAREA
*  COVERAGE  : Products and Completed Operations Liability (PC)
*  STATE     : AR
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-RAR-REQUEST-ID        PIC X(6).
     03 CA-RAR-RETURN-CODE       PIC 9(2).
     03 CA-RAR-POLICY-NUM        PIC 9(10).
     03 CA-RAR-CUSTOMER-NUM      PIC 9(10).

          03 CA-RAR-ISSUE-DATE                PIC X(10).
          03 CA-RAR-EXPIRY-DATE               PIC X(10).
          03 CA-RAR-LASTCHANGED               PIC X(26).
          03 CA-RAR-BROKERID                  PIC 9(10).
          03 CA-RAR-BROKERSREF                PIC X(10).
          03 CA-RAR-PAYMENT                   PIC 9(6).
          03 CA-RAR-PRODUCT-CLASS-CODE        PIC X(4).
          03 CA-RAR-HAZARD-GROUP              PIC X(2).
          03 CA-RAR-SALES-EXPOSURE-AMT        PIC 9(9).
          03 CA-RAR-COMPLETED-OPS-IND         PIC X(1).
          03 CA-RAR-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-RAR-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-RAR-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-RAR-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-RAR-PRIOR-CLAIMS-COUNT        PIC 9(3).
