******************************************************************
*  COPYBOOK  : GRCOP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Products and Completed Operations Liability (PC)
*  STATE     : CO
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-RCO-POLICY.

          03 DB2-RCO-ISSUE-DATE               PIC X(10).
          03 DB2-RCO-EXPIRY-DATE              PIC X(10).
          03 DB2-RCO-LASTCHANGED              PIC X(26).
          03 DB2-RCO-BROKERID                 PIC 9(10).
          03 DB2-RCO-BROKERSREF               PIC X(10).
          03 DB2-RCO-PAYMENT                  PIC 9(6).
          03 DB2-RCO-PRODUCT-CLASS-CODE       PIC X(4).
          03 DB2-RCO-HAZARD-GROUP             PIC X(2).
          03 DB2-RCO-SALES-EXPOSURE-AMT       PIC 9(9).
          03 DB2-RCO-COMPLETED-OPS-IND        PIC X(1).
          03 DB2-RCO-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-RCO-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-RCO-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-RCO-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-RCO-PRIOR-CLAIMS-COUNT       PIC 9(3).
