******************************************************************
*  COPYBOOK  : GRCOC001
*  KIND      : COMMAREA
*  COVERAGE  : Products and Completed Operations Liability (PC)
*  STATE     : CO
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-RCO-REQUEST-ID        PIC X(6).
     03 CA-RCO-RETURN-CODE       PIC 9(2).
     03 CA-RCO-POLICY-NUM        PIC 9(10).
     03 CA-RCO-CUSTOMER-NUM      PIC 9(10).

          03 CA-RCO-ISSUE-DATE                PIC X(10).
          03 CA-RCO-EXPIRY-DATE               PIC X(10).
          03 CA-RCO-LASTCHANGED               PIC X(26).
          03 CA-RCO-BROKERID                  PIC 9(10).
          03 CA-RCO-BROKERSREF                PIC X(10).
          03 CA-RCO-PAYMENT                   PIC 9(6).
          03 CA-RCO-PRODUCT-CLASS-CODE        PIC X(4).
          03 CA-RCO-HAZARD-GROUP              PIC X(2).
          03 CA-RCO-SALES-EXPOSURE-AMT        PIC 9(9).
          03 CA-RCO-COMPLETED-OPS-IND         PIC X(1).
          03 CA-RCO-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-RCO-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-RCO-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-RCO-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-RCO-PRIOR-CLAIMS-COUNT        PIC 9(3).
