******************************************************************
*  COPYBOOK  : GRCTP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Products and Completed Operations Liability (PC)
*  STATE     : CT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-RCT-POLICY.

          03 DB2-RCT-ISSUE-DATE               PIC X(10).
          03 DB2-RCT-EXPIRY-DATE              PIC X(10).
          03 DB2-RCT-LASTCHANGED              PIC X(26).
          03 DB2-RCT-BROKERID                 PIC 9(10).
          03 DB2-RCT-BROKERSREF               PIC X(10).
          03 DB2-RCT-PAYMENT                  PIC 9(6).
          03 DB2-RCT-PRODUCT-CLASS-CODE       PIC X(4).
          03 DB2-RCT-HAZARD-GROUP             PIC X(2).
          03 DB2-RCT-SALES-EXPOSURE-AMT       PIC 9(9).
          03 DB2-RCT-COMPLETED-OPS-IND        PIC X(1).
          03 DB2-RCT-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-RCT-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-RCT-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-RCT-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-RCT-PRIOR-CLAIMS-COUNT       PIC 9(3).
