******************************************************************
*  COPYBOOK  : GRDEC001
*  KIND      : COMMAREA
*  COVERAGE  : Products and Completed Operations Liability (PC)
*  STATE     : DE
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-RDE-REQUEST-ID        PIC X(6).
     03 CA-RDE-RETURN-CODE       PIC 9(2).
     03 CA-RDE-POLICY-NUM        PIC 9(10).
     03 CA-RDE-CUSTOMER-NUM      PIC 9(10).

          03 CA-RDE-ISSUE-DATE                PIC X(10).
          03 CA-RDE-EXPIRY-DATE               PIC X(10).
          03 CA-RDE-LASTCHANGED               PIC X(26).
          03 CA-RDE-BROKERID                  PIC 9(10).
          03 CA-RDE-BROKERSREF                PIC X(10).
          03 CA-RDE-PAYMENT                   PIC 9(6).
          03 CA-RDE-PRODUCT-CLASS-CODE        PIC X(4).
          03 CA-RDE-HAZARD-GROUP              PIC X(2).
          03 CA-RDE-SALES-EXPOSURE-AMT        PIC 9(9).
          03 CA-RDE-COMPLETED-OPS-IND         PIC X(1).
          03 CA-RDE-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-RDE-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-RDE-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-RDE-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-RDE-PRIOR-CLAIMS-COUNT        PIC 9(3).
