******************************************************************
*  COPYBOOK  : GRFLP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Products and Completed Operations Liability (PC)
*  STATE     : FL
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-RFL-POLICY.

          03 DB2-RFL-ISSUE-DATE               PIC X(10).
          03 DB2-RFL-EXPIRY-DATE              PIC X(10).
          03 DB2-RFL-LASTCHANGED              PIC X(26).
          03 DB2-RFL-BROKERID                 PIC 9(10).
          03 DB2-RFL-BROKERSREF               PIC X(10).
          03 DB2-RFL-PAYMENT                  PIC 9(6).
          03 DB2-RFL-PRODUCT-CLASS-CODE       PIC X(4).
          03 DB2-RFL-HAZARD-GROUP             PIC X(2).
          03 DB2-RFL-SALES-EXPOSURE-AMT       PIC 9(9).
          03 DB2-RFL-COMPLETED-OPS-IND        PIC X(1).
          03 DB2-RFL-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-RFL-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-RFL-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-RFL-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-RFL-PRIOR-CLAIMS-COUNT       PIC 9(3).
