******************************************************************
*  COPYBOOK  : GRMAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Products and Completed Operations Liability (PC)
*  STATE     : MA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-RMA-POLICY.

          03 DB2-RMA-ISSUE-DATE               PIC X(10).
          03 DB2-RMA-EXPIRY-DATE              PIC X(10).
          03 DB2-RMA-LASTCHANGED              PIC X(26).
          03 DB2-RMA-BROKERID                 PIC 9(10).
          03 DB2-RMA-BROKERSREF               PIC X(10).
          03 DB2-RMA-PAYMENT                  PIC 9(6).
          03 DB2-RMA-PRODUCT-CLASS-CODE       PIC X(4).
          03 DB2-RMA-HAZARD-GROUP             PIC X(2).
          03 DB2-RMA-SALES-EXPOSURE-AMT       PIC 9(9).
          03 DB2-RMA-COMPLETED-OPS-IND        PIC X(1).
          03 DB2-RMA-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-RMA-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-RMA-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-RMA-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-RMA-PRIOR-CLAIMS-COUNT       PIC 9(3).
