******************************************************************
*  COPYBOOK  : GRMEC001
*  KIND      : COMMAREA
*  COVERAGE  : Products and Completed Operations Liability (PC)
*  STATE     : ME
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-RME-REQUEST-ID        PIC X(6).
     03 CA-RME-RETURN-CODE       PIC 9(2).
     03 CA-RME-POLICY-NUM        PIC 9(10).
     03 CA-RME-CUSTOMER-NUM      PIC 9(10).

          03 CA-RME-ISSUE-DATE                PIC X(10).
          03 CA-RME-EXPIRY-DATE               PIC X(10).
          03 CA-RME-LASTCHANGED               PIC X(26).
          03 CA-RME-BROKERID                  PIC 9(10).
          03 CA-RME-BROKERSREF                PIC X(10).
          03 CA-RME-PAYMENT                   PIC 9(6).
          03 CA-RME-PRODUCT-CLASS-CODE        PIC X(4).
          03 CA-RME-HAZARD-GROUP              PIC X(2).
          03 CA-RME-SALES-EXPOSURE-AMT        PIC 9(9).
          03 CA-RME-COMPLETED-OPS-IND         PIC X(1).
          03 CA-RME-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-RME-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-RME-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-RME-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-RME-PRIOR-CLAIMS-COUNT        PIC 9(3).
