******************************************************************
*  COPYBOOK  : GRMOC001
*  KIND      : COMMAREA
*  COVERAGE  : Products and Completed Operations Liability (PC)
*  STATE     : MO
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-RMO-REQUEST-ID        PIC X(6).
     03 CA-RMO-RETURN-CODE       PIC 9(2).
     03 CA-RMO-POLICY-NUM        PIC 9(10).
     03 CA-RMO-CUSTOMER-NUM      PIC 9(10).

          03 CA-RMO-ISSUE-DATE                PIC X(10).
          03 CA-RMO-EXPIRY-DATE               PIC X(10).
          03 CA-RMO-LASTCHANGED               PIC X(26).
          03 CA-RMO-BROKERID                  PIC 9(10).
          03 CA-RMO-BROKERSREF                PIC X(10).
          03 CA-RMO-PAYMENT                   PIC 9(6).
          03 CA-RMO-PRODUCT-CLASS-CODE        PIC X(4).
          03 CA-RMO-HAZARD-GROUP              PIC X(2).
          03 CA-RMO-SALES-EXPOSURE-AMT        PIC 9(9).
          03 CA-RMO-COMPLETED-OPS-IND         PIC X(1).
          03 CA-RMO-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-RMO-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-RMO-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-RMO-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-RMO-PRIOR-CLAIMS-COUNT        PIC 9(3).
