******************************************************************
*  COPYBOOK  : GRMTC001
*  KIND      : COMMAREA
*  COVERAGE  : Products and Completed Operations Liability (PC)
*  STATE     : MT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-RMT-REQUEST-ID        PIC X(6).
     03 CA-RMT-RETURN-CODE       PIC 9(2).
     03 CA-RMT-POLICY-NUM        PIC 9(10).
     03 CA-RMT-CUSTOMER-NUM      PIC 9(10).

          03 CA-RMT-ISSUE-DATE                PIC X(10).
          03 CA-RMT-EXPIRY-DATE               PIC X(10).
          03 CA-RMT-LASTCHANGED               PIC X(26).
          03 CA-RMT-BROKERID                  PIC 9(10).
          03 CA-RMT-BROKERSREF                PIC X(10).
          03 CA-RMT-PAYMENT                   PIC 9(6).
          03 CA-RMT-PRODUCT-CLASS-CODE        PIC X(4).
          03 CA-RMT-HAZARD-GROUP              PIC X(2).
          03 CA-RMT-SALES-EXPOSURE-AMT        PIC 9(9).
          03 CA-RMT-COMPLETED-OPS-IND         PIC X(1).
          03 CA-RMT-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-RMT-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-RMT-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-RMT-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-RMT-PRIOR-CLAIMS-COUNT        PIC 9(3).
