******************************************************************
*  COPYBOOK  : GRNCP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Products and Completed Operations Liability (PC)
*  STATE     : NC
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-RNC-POLICY.

          03 DB2-RNC-ISSUE-DATE               PIC X(10).
          03 DB2-RNC-EXPIRY-DATE              PIC X(10).
          03 DB2-RNC-LASTCHANGED              PIC X(26).
          03 DB2-RNC-BROKERID                 PIC 9(10).
          03 DB2-RNC-BROKERSREF               PIC X(10).
          03 DB2-RNC-PAYMENT                  PIC 9(6).
          03 DB2-RNC-PRODUCT-CLASS-CODE       PIC X(4).
          03 DB2-RNC-HAZARD-GROUP             PIC X(2).
          03 DB2-RNC-SALES-EXPOSURE-AMT       PIC 9(9).
          03 DB2-RNC-COMPLETED-OPS-IND        PIC X(1).
          03 DB2-RNC-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-RNC-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-RNC-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-RNC-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-RNC-PRIOR-CLAIMS-COUNT       PIC 9(3).
