******************************************************************
*  COPYBOOK  : GRNMC001
*  KIND      : COMMAREA
*  COVERAGE  : Products and Completed Operations Liability (PC)
*  STATE     : NM
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-RNM-REQUEST-ID        PIC X(6).
     03 CA-RNM-RETURN-CODE       PIC 9(2).
     03 CA-RNM-POLICY-NUM        PIC 9(10).
     03 CA-RNM-CUSTOMER-NUM      PIC 9(10).

          03 CA-RNM-ISSUE-DATE                PIC X(10).
          03 CA-RNM-EXPIRY-DATE               PIC X(10).
          03 CA-RNM-LASTCHANGED               PIC X(26).
          03 CA-RNM-BROKERID                  PIC 9(10).
          03 CA-RNM-BROKERSREF                PIC X(10).
          03 CA-RNM-PAYMENT                   PIC 9(6).
          03 CA-RNM-PRODUCT-CLASS-CODE        PIC X(4).
          03 CA-RNM-HAZARD-GROUP              PIC X(2).
          03 CA-RNM-SALES-EXPOSURE-AMT        PIC 9(9).
          03 CA-RNM-COMPLETED-OPS-IND         PIC X(1).
          03 CA-RNM-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-RNM-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-RNM-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-RNM-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-RNM-PRIOR-CLAIMS-COUNT        PIC 9(3).
