******************************************************************
*  COPYBOOK  : GROHC001
*  KIND      : COMMAREA
*  COVERAGE  : Products and Completed Operations Liability (PC)
*  STATE     : OH
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-ROH-REQUEST-ID        PIC X(6).
     03 CA-ROH-RETURN-CODE       PIC 9(2).
     03 CA-ROH-POLICY-NUM        PIC 9(10).
     03 CA-ROH-CUSTOMER-NUM      PIC 9(10).

          03 CA-ROH-ISSUE-DATE                PIC X(10).
          03 CA-ROH-EXPIRY-DATE               PIC X(10).
          03 CA-ROH-LASTCHANGED               PIC X(26).
          03 CA-ROH-BROKERID                  PIC 9(10).
          03 CA-ROH-BROKERSREF                PIC X(10).
          03 CA-ROH-PAYMENT                   PIC 9(6).
          03 CA-ROH-PRODUCT-CLASS-CODE        PIC X(4).
          03 CA-ROH-HAZARD-GROUP              PIC X(2).
          03 CA-ROH-SALES-EXPOSURE-AMT        PIC 9(9).
          03 CA-ROH-COMPLETED-OPS-IND         PIC X(1).
          03 CA-ROH-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-ROH-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-ROH-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-ROH-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-ROH-PRIOR-CLAIMS-COUNT        PIC 9(3).
