******************************************************************
*  COPYBOOK  : GROKC001
*  KIND      : COMMAREA
*  COVERAGE  : Products and Completed Operations Liability (PC)
*  STATE     : OK
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-ROK-REQUEST-ID        PIC X(6).
     03 CA-ROK-RETURN-CODE       PIC 9(2).
     03 CA-ROK-POLICY-NUM        PIC 9(10).
     03 CA-ROK-CUSTOMER-NUM      PIC 9(10).

          03 CA-ROK-ISSUE-DATE                PIC X(10).
          03 CA-ROK-EXPIRY-DATE               PIC X(10).
          03 CA-ROK-LASTCHANGED               PIC X(26).
          03 CA-ROK-BROKERID                  PIC 9(10).
          03 CA-ROK-BROKERSREF                PIC X(10).
          03 CA-ROK-PAYMENT                   PIC 9(6).
          03 CA-ROK-PRODUCT-CLASS-CODE        PIC X(4).
          03 CA-ROK-HAZARD-GROUP              PIC X(2).
          03 CA-ROK-SALES-EXPOSURE-AMT        PIC 9(9).
          03 CA-ROK-COMPLETED-OPS-IND         PIC X(1).
          03 CA-ROK-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-ROK-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-ROK-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-ROK-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-ROK-PRIOR-CLAIMS-COUNT        PIC 9(3).
