******************************************************************
*  COPYBOOK  : GRRIP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Products and Completed Operations Liability (PC)
*  STATE     : RI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-RRI-POLICY.

          03 DB2-RRI-ISSUE-DATE               PIC X(10).
          03 DB2-RRI-EXPIRY-DATE              PIC X(10).
          03 DB2-RRI-LASTCHANGED              PIC X(26).
          03 DB2-RRI-BROKERID                 PIC 9(10).
          03 DB2-RRI-BROKERSREF               PIC X(10).
          03 DB2-RRI-PAYMENT                  PIC 9(6).
          03 DB2-RRI-PRODUCT-CLASS-CODE       PIC X(4).
          03 DB2-RRI-HAZARD-GROUP             PIC X(2).
          03 DB2-RRI-SALES-EXPOSURE-AMT       PIC 9(9).
          03 DB2-RRI-COMPLETED-OPS-IND        PIC X(1).
          03 DB2-RRI-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-RRI-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-RRI-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-RRI-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-RRI-PRIOR-CLAIMS-COUNT       PIC 9(3).
