******************************************************************
*  COPYBOOK  : GRSDC001
*  KIND      : COMMAREA
*  COVERAGE  : Products and Completed Operations Liability (PC)
*  STATE     : SD
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-RSD-REQUEST-ID        PIC X(6).
     03 CA-RSD-RETURN-CODE       PIC 9(2).
     03 CA-RSD-POLICY-NUM        PIC 9(10).
     03 CA-RSD-CUSTOMER-NUM      PIC 9(10).

          03 CA-RSD-ISSUE-DATE                PIC X(10).
          03 CA-RSD-EXPIRY-DATE               PIC X(10).
          03 CA-RSD-LASTCHANGED               PIC X(26).
          03 CA-RSD-BROKERID                  PIC 9(10).
          03 CA-RSD-BROKERSREF                PIC X(10).
          03 CA-RSD-PAYMENT                   PIC 9(6).
          03 CA-RSD-PRODUCT-CLASS-CODE        PIC X(4).
          03 CA-RSD-HAZARD-GROUP              PIC X(2).
          03 CA-RSD-SALES-EXPOSURE-AMT        PIC 9(9).
          03 CA-RSD-COMPLETED-OPS-IND         PIC X(1).
          03 CA-RSD-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-RSD-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-RSD-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-RSD-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-RSD-PRIOR-CLAIMS-COUNT        PIC 9(3).
