******************************************************************
*  COPYBOOK  : GRTXP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Products and Completed Operations Liability (PC)
*  STATE     : TX
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-RTX-POLICY.

          03 DB2-RTX-ISSUE-DATE               PIC X(10).
          03 DB2-RTX-EXPIRY-DATE              PIC X(10).
          03 DB2-RTX-LASTCHANGED              PIC X(26).
          03 DB2-RTX-BROKERID                 PIC 9(10).
          03 DB2-RTX-BROKERSREF               PIC X(10).
          03 DB2-RTX-PAYMENT                  PIC 9(6).
          03 DB2-RTX-PRODUCT-CLASS-CODE       PIC X(4).
          03 DB2-RTX-HAZARD-GROUP             PIC X(2).
          03 DB2-RTX-SALES-EXPOSURE-AMT       PIC 9(9).
          03 DB2-RTX-COMPLETED-OPS-IND        PIC X(1).
          03 DB2-RTX-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-RTX-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-RTX-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-RTX-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-RTX-PRIOR-CLAIMS-COUNT       PIC 9(3).
