******************************************************************
*  COPYBOOK  : GRTXC001
*  KIND      : COMMAREA
*  COVERAGE  : Products and Completed Operations Liability (PC)
*  STATE     : TX
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-RTX-REQUEST-ID        PIC X(6).
     03 CA-RTX-RETURN-CODE       PIC 9(2).
     03 CA-RTX-POLICY-NUM        PIC 9(10).
     03 CA-RTX-CUSTOMER-NUM      PIC 9(10).

          03 CA-RTX-ISSUE-DATE                PIC X(10).
          03 CA-RTX-EXPIRY-DATE               PIC X(10).
          03 CA-RTX-LASTCHANGED               PIC X(26).
          03 CA-RTX-BROKERID                  PIC 9(10).
          03 CA-RTX-BROKERSREF                PIC X(10).
          03 CA-RTX-PAYMENT                   PIC 9(6).
          03 CA-RTX-PRODUCT-CLASS-CODE        PIC X(4).
          03 CA-RTX-HAZARD-GROUP              PIC X(2).
          03 CA-RTX-SALES-EXPOSURE-AMT        PIC 9(9).
          03 CA-RTX-COMPLETED-OPS-IND         PIC X(1).
          03 CA-RTX-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-RTX-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-RTX-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-RTX-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-RTX-PRIOR-CLAIMS-COUNT        PIC 9(3).
