******************************************************************
*  COPYBOOK  : GRUTC001
*  KIND      : COMMAREA
*  COVERAGE  : Products and Completed Operations Liability (PC)
*  STATE     : UT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-RUT-REQUEST-ID        PIC X(6).
     03 CA-RUT-RETURN-CODE       PIC 9(2).
     03 CA-RUT-POLICY-NUM        PIC 9(10).
     03 CA-RUT-CUSTOMER-NUM      PIC 9(10).

          03 CA-RUT-ISSUE-DATE                PIC X(10).
          03 CA-RUT-EXPIRY-DATE               PIC X(10).
          03 CA-RUT-LASTCHANGED               PIC X(26).
          03 CA-RUT-BROKERID                  PIC 9(10).
          03 CA-RUT-BROKERSREF                PIC X(10).
          03 CA-RUT-PAYMENT                   PIC 9(6).
          03 CA-RUT-PRODUCT-CLASS-CODE        PIC X(4).
          03 CA-RUT-HAZARD-GROUP              PIC X(2).
          03 CA-RUT-SALES-EXPOSURE-AMT        PIC 9(9).
          03 CA-RUT-COMPLETED-OPS-IND         PIC X(1).
          03 CA-RUT-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-RUT-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-RUT-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-RUT-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-RUT-PRIOR-CLAIMS-COUNT        PIC 9(3).
