******************************************************************
*  COPYBOOK  : GRWAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Products and Completed Operations Liability (PC)
*  STATE     : WA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-RWA-POLICY.

          03 DB2-RWA-ISSUE-DATE               PIC X(10).
          03 DB2-RWA-EXPIRY-DATE              PIC X(10).
          03 DB2-RWA-LASTCHANGED              PIC X(26).
          03 DB2-RWA-BROKERID                 PIC 9(10).
          03 DB2-RWA-BROKERSREF               PIC X(10).
          03 DB2-RWA-PAYMENT                  PIC 9(6).
          03 DB2-RWA-PRODUCT-CLASS-CODE       PIC X(4).
          03 DB2-RWA-HAZARD-GROUP             PIC X(2).
          03 DB2-RWA-SALES-EXPOSURE-AMT       PIC 9(9).
          03 DB2-RWA-COMPLETED-OPS-IND        PIC X(1).
          03 DB2-RWA-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-RWA-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-RWA-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-RWA-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-RWA-PRIOR-CLAIMS-COUNT       PIC 9(3).
