******************************************************************
*  COPYBOOK  : GRWIC001
*  KIND      : COMMAREA
*  COVERAGE  : Products and Completed Operations Liability (PC)
*  STATE     : WI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-RWI-REQUEST-ID        PIC X(6).
     03 CA-RWI-RETURN-CODE       PIC 9(2).
     03 CA-RWI-POLICY-NUM        PIC 9(10).
     03 CA-RWI-CUSTOMER-NUM      PIC 9(10).

          03 CA-RWI-ISSUE-DATE                PIC X(10).
          03 CA-RWI-EXPIRY-DATE               PIC X(10).
          03 CA-RWI-LASTCHANGED               PIC X(26).
          03 CA-RWI-BROKERID                  PIC 9(10).
          03 CA-RWI-BROKERSREF                PIC X(10).
          03 CA-RWI-PAYMENT                   PIC 9(6).
          03 CA-RWI-PRODUCT-CLASS-CODE        PIC X(4).
          03 CA-RWI-HAZARD-GROUP              PIC X(2).
          03 CA-RWI-SALES-EXPOSURE-AMT        PIC 9(9).
          03 CA-RWI-COMPLETED-OPS-IND         PIC X(1).
          03 CA-RWI-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-RWI-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-RWI-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-RWI-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-RWI-PRIOR-CLAIMS-COUNT        PIC 9(3).
