******************************************************************
*  COPYBOOK  : GRWVC001
*  KIND      : COMMAREA
*  COVERAGE  : Products and Completed Operations Liability (PC)
*  STATE     : WV
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-RWV-REQUEST-ID        PIC X(6).
     03 CA-RWV-RETURN-CODE       PIC 9(2).
     03 CA-RWV-POLICY-NUM        PIC 9(10).
     03 CA-RWV-CUSTOMER-NUM      PIC 9(10).

          03 CA-RWV-ISSUE-DATE                PIC X(10).
          03 CA-RWV-EXPIRY-DATE               PIC X(10).
          03 CA-RWV-LASTCHANGED               PIC X(26).
          03 CA-RWV-BROKERID                  PIC 9(10).
          03 CA-RWV-BROKERSREF                PIC X(10).
          03 CA-RWV-PAYMENT                   PIC 9(6).
          03 CA-RWV-PRODUCT-CLASS-CODE        PIC X(4).
          03 CA-RWV-HAZARD-GROUP              PIC X(2).
          03 CA-RWV-SALES-EXPOSURE-AMT        PIC 9(9).
          03 CA-RWV-COMPLETED-OPS-IND         PIC X(1).
          03 CA-RWV-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-RWV-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-RWV-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-RWV-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-RWV-PRIOR-CLAIMS-COUNT        PIC 9(3).
