******************************************************************
*  COPYBOOK  : GCALC001
*  KIND      : COMMAREA
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : AL
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-CAL-REQUEST-ID        PIC X(6).
     03 CA-CAL-RETURN-CODE       PIC 9(2).
     03 CA-CAL-POLICY-NUM        PIC 9(10).
     03 CA-CAL-CUSTOMER-NUM      PIC 9(10).

          03 CA-CAL-ISSUE-DATE                PIC X(10).
          03 CA-CAL-EXPIRY-DATE               PIC X(10).
          03 CA-CAL-LASTCHANGED               PIC X(26).
          03 CA-CAL-BROKERID                  PIC 9(10).
          03 CA-CAL-BROKERSREF                PIC X(10).
          03 CA-CAL-PAYMENT                   PIC 9(6).
          03 CA-CAL-CONTRACT-TYPE-CODE        PIC X(3).
          03 CA-CAL-INDEMNITY-LIMIT           PIC 9(9).
          03 CA-CAL-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-CAL-TERRITORY-CODE            PIC X(3).
