******************************************************************
*  COPYBOOK  : GCARC001
*  KIND      : COMMAREA
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : AR
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-CAR-REQUEST-ID        PIC X(6).
     03 CA-CAR-RETURN-CODE       PIC 9(2).
     03 CA-CAR-POLICY-NUM        PIC 9(10).
     03 CA-CAR-CUSTOMER-NUM      PIC 9(10).

          03 CA-CAR-ISSUE-DATE                PIC X(10).
          03 CA-CAR-EXPIRY-DATE               PIC X(10).
          03 CA-CAR-LASTCHANGED               PIC X(26).
          03 CA-CAR-BROKERID                  PIC 9(10).
          03 CA-CAR-BROKERSREF                PIC X(10).
          03 CA-CAR-PAYMENT                   PIC 9(6).
          03 CA-CAR-CONTRACT-TYPE-CODE        PIC X(3).
          03 CA-CAR-INDEMNITY-LIMIT           PIC 9(9).
          03 CA-CAR-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-CAR-TERRITORY-CODE            PIC X(3).
