******************************************************************
*  COPYBOOK  : GCAZC001
*  KIND      : COMMAREA
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : AZ
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-CAZ-REQUEST-ID        PIC X(6).
     03 CA-CAZ-RETURN-CODE       PIC 9(2).
     03 CA-CAZ-POLICY-NUM        PIC 9(10).
     03 CA-CAZ-CUSTOMER-NUM      PIC 9(10).

          03 CA-CAZ-ISSUE-DATE                PIC X(10).
          03 CA-CAZ-EXPIRY-DATE               PIC X(10).
          03 CA-CAZ-LASTCHANGED               PIC X(26).
          03 CA-CAZ-BROKERID                  PIC 9(10).
          03 CA-CAZ-BROKERSREF                PIC X(10).
          03 CA-CAZ-PAYMENT                   PIC 9(6).
          03 CA-CAZ-CONTRACT-TYPE-CODE        PIC X(3).
          03 CA-CAZ-INDEMNITY-LIMIT           PIC 9(9).
          03 CA-CAZ-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-CAZ-TERRITORY-CODE            PIC X(3).
