******************************************************************
*  COPYBOOK  : GCCAC001
*  KIND      : COMMAREA
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : CA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-CCA-REQUEST-ID        PIC X(6).
     03 CA-CCA-RETURN-CODE       PIC 9(2).
     03 CA-CCA-POLICY-NUM        PIC 9(10).
     03 CA-CCA-CUSTOMER-NUM      PIC 9(10).

          03 CA-CCA-ISSUE-DATE                PIC X(10).
          03 CA-CCA-EXPIRY-DATE               PIC X(10).
          03 CA-CCA-LASTCHANGED               PIC X(26).
          03 CA-CCA-BROKERID                  PIC 9(10).
          03 CA-CCA-BROKERSREF                PIC X(10).
          03 CA-CCA-PAYMENT                   PIC 9(6).
          03 CA-CCA-CONTRACT-TYPE-CODE        PIC X(3).
          03 CA-CCA-INDEMNITY-LIMIT           PIC 9(9).
          03 CA-CCA-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-CCA-TERRITORY-CODE            PIC X(3).
