******************************************************************
*  COPYBOOK  : GCGAC001
*  KIND      : COMMAREA
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : GA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-CGA-REQUEST-ID        PIC X(6).
     03 CA-CGA-RETURN-CODE       PIC 9(2).
     03 CA-CGA-POLICY-NUM        PIC 9(10).
     03 CA-CGA-CUSTOMER-NUM      PIC 9(10).

          03 CA-CGA-ISSUE-DATE                PIC X(10).
          03 CA-CGA-EXPIRY-DATE               PIC X(10).
          03 CA-CGA-LASTCHANGED               PIC X(26).
          03 CA-CGA-BROKERID                  PIC 9(10).
          03 CA-CGA-BROKERSREF                PIC X(10).
          03 CA-CGA-PAYMENT                   PIC 9(6).
          03 CA-CGA-CONTRACT-TYPE-CODE        PIC X(3).
          03 CA-CGA-INDEMNITY-LIMIT           PIC 9(9).
          03 CA-CGA-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-CGA-TERRITORY-CODE            PIC X(3).
