******************************************************************
*  COPYBOOK  : GCHIP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : HI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-CHI-POLICY.

          03 DB2-CHI-ISSUE-DATE               PIC X(10).
          03 DB2-CHI-EXPIRY-DATE              PIC X(10).
          03 DB2-CHI-LASTCHANGED              PIC X(26).
          03 DB2-CHI-BROKERID                 PIC 9(10).
          03 DB2-CHI-BROKERSREF               PIC X(10).
          03 DB2-CHI-PAYMENT                  PIC 9(6).
          03 DB2-CHI-CONTRACT-TYPE-CODE       PIC X(3).
          03 DB2-CHI-INDEMNITY-LIMIT          PIC 9(9).
          03 DB2-CHI-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-CHI-TERRITORY-CODE           PIC X(3).
