******************************************************************
*  COPYBOOK  : GCIAC001
*  KIND      : COMMAREA
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : IA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-CIA-REQUEST-ID        PIC X(6).
     03 CA-CIA-RETURN-CODE       PIC 9(2).
     03 CA-CIA-POLICY-NUM        PIC 9(10).
     03 CA-CIA-CUSTOMER-NUM      PIC 9(10).

          03 CA-CIA-ISSUE-DATE                PIC X(10).
          03 CA-CIA-EXPIRY-DATE               PIC X(10).
          03 CA-CIA-LASTCHANGED               PIC X(26).
          03 CA-CIA-BROKERID                  PIC 9(10).
          03 CA-CIA-BROKERSREF                PIC X(10).
          03 CA-CIA-PAYMENT                   PIC 9(6).
          03 CA-CIA-CONTRACT-TYPE-CODE        PIC X(3).
          03 CA-CIA-INDEMNITY-LIMIT           PIC 9(9).
          03 CA-CIA-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-CIA-TERRITORY-CODE            PIC X(3).
