******************************************************************
*  COPYBOOK  : GCIDP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : ID
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-CID-POLICY.

          03 DB2-CID-ISSUE-DATE               PIC X(10).
          03 DB2-CID-EXPIRY-DATE              PIC X(10).
          03 DB2-CID-LASTCHANGED              PIC X(26).
          03 DB2-CID-BROKERID                 PIC 9(10).
          03 DB2-CID-BROKERSREF               PIC X(10).
          03 DB2-CID-PAYMENT                  PIC 9(6).
          03 DB2-CID-CONTRACT-TYPE-CODE       PIC X(3).
          03 DB2-CID-INDEMNITY-LIMIT          PIC 9(9).
          03 DB2-CID-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-CID-TERRITORY-CODE           PIC X(3).
