******************************************************************
*  COPYBOOK  : GCIDC001
*  KIND      : COMMAREA
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : ID
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-CID-REQUEST-ID        PIC X(6).
     03 CA-CID-RETURN-CODE       PIC 9(2).
     03 CA-CID-POLICY-NUM        PIC 9(10).
     03 CA-CID-CUSTOMER-NUM      PIC 9(10).

          03 CA-CID-ISSUE-DATE                PIC X(10).
          03 CA-CID-EXPIRY-DATE               PIC X(10).
          03 CA-CID-LASTCHANGED               PIC X(26).
          03 CA-CID-BROKERID                  PIC 9(10).
          03 CA-CID-BROKERSREF                PIC X(10).
          03 CA-CID-PAYMENT                   PIC 9(6).
          03 CA-CID-CONTRACT-TYPE-CODE        PIC X(3).
          03 CA-CID-INDEMNITY-LIMIT           PIC 9(9).
          03 CA-CID-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-CID-TERRITORY-CODE            PIC X(3).
