******************************************************************
*  COPYBOOK  : GCKYC001
*  KIND      : COMMAREA
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : KY
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-CKY-REQUEST-ID        PIC X(6).
     03 CA-CKY-RETURN-CODE       PIC 9(2).
     03 CA-CKY-POLICY-NUM        PIC 9(10).
     03 CA-CKY-CUSTOMER-NUM      PIC 9(10).

          03 CA-CKY-ISSUE-DATE                PIC X(10).
          03 CA-CKY-EXPIRY-DATE               PIC X(10).
          03 CA-CKY-LASTCHANGED               PIC X(26).
          03 CA-CKY-BROKERID                  PIC 9(10).
          03 CA-CKY-BROKERSREF                PIC X(10).
          03 CA-CKY-PAYMENT                   PIC 9(6).
          03 CA-CKY-CONTRACT-TYPE-CODE        PIC X(3).
          03 CA-CKY-INDEMNITY-LIMIT           PIC 9(9).
          03 CA-CKY-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-CKY-TERRITORY-CODE            PIC X(3).
