******************************************************************
*  COPYBOOK  : GCMDC001
*  KIND      : COMMAREA
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : MD
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-CMD-REQUEST-ID        PIC X(6).
     03 CA-CMD-RETURN-CODE       PIC 9(2).
     03 CA-CMD-POLICY-NUM        PIC 9(10).
     03 CA-CMD-CUSTOMER-NUM      PIC 9(10).

          03 CA-CMD-ISSUE-DATE                PIC X(10).
          03 CA-CMD-EXPIRY-DATE               PIC X(10).
          03 CA-CMD-LASTCHANGED               PIC X(26).
          03 CA-CMD-BROKERID                  PIC 9(10).
          03 CA-CMD-BROKERSREF                PIC X(10).
          03 CA-CMD-PAYMENT                   PIC 9(6).
          03 CA-CMD-CONTRACT-TYPE-CODE        PIC X(3).
          03 CA-CMD-INDEMNITY-LIMIT           PIC 9(9).
          03 CA-CMD-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-CMD-TERRITORY-CODE            PIC X(3).
