******************************************************************
*  COPYBOOK  : GCMTP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : MT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-CMT-POLICY.

          03 DB2-CMT-ISSUE-DATE               PIC X(10).
          03 DB2-CMT-EXPIRY-DATE              PIC X(10).
          03 DB2-CMT-LASTCHANGED              PIC X(26).
          03 DB2-CMT-BROKERID                 PIC 9(10).
          03 DB2-CMT-BROKERSREF               PIC X(10).
          03 DB2-CMT-PAYMENT                  PIC 9(6).
          03 DB2-CMT-CONTRACT-TYPE-CODE       PIC X(3).
          03 DB2-CMT-INDEMNITY-LIMIT          PIC 9(9).
          03 DB2-CMT-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-CMT-TERRITORY-CODE           PIC X(3).
