******************************************************************
*  COPYBOOK  : GCNCP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : NC
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-CNC-POLICY.

          03 DB2-CNC-ISSUE-DATE               PIC X(10).
          03 DB2-CNC-EXPIRY-DATE              PIC X(10).
          03 DB2-CNC-LASTCHANGED              PIC X(26).
          03 DB2-CNC-BROKERID                 PIC 9(10).
          03 DB2-CNC-BROKERSREF               PIC X(10).
          03 DB2-CNC-PAYMENT                  PIC 9(6).
          03 DB2-CNC-CONTRACT-TYPE-CODE       PIC X(3).
          03 DB2-CNC-INDEMNITY-LIMIT          PIC 9(9).
          03 DB2-CNC-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-CNC-TERRITORY-CODE           PIC X(3).
