******************************************************************
*  COPYBOOK  : GCNMP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : NM
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-CNM-POLICY.

          03 DB2-CNM-ISSUE-DATE               PIC X(10).
          03 DB2-CNM-EXPIRY-DATE              PIC X(10).
          03 DB2-CNM-LASTCHANGED              PIC X(26).
          03 DB2-CNM-BROKERID                 PIC 9(10).
          03 DB2-CNM-BROKERSREF               PIC X(10).
          03 DB2-CNM-PAYMENT                  PIC 9(6).
          03 DB2-CNM-CONTRACT-TYPE-CODE       PIC X(3).
          03 DB2-CNM-INDEMNITY-LIMIT          PIC 9(9).
          03 DB2-CNM-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-CNM-TERRITORY-CODE           PIC X(3).
