******************************************************************
*  COPYBOOK  : GCOKC001
*  KIND      : COMMAREA
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : OK
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-COK-REQUEST-ID        PIC X(6).
     03 CA-COK-RETURN-CODE       PIC 9(2).
     03 CA-COK-POLICY-NUM        PIC 9(10).
     03 CA-COK-CUSTOMER-NUM      PIC 9(10).

          03 CA-COK-ISSUE-DATE                PIC X(10).
          03 CA-COK-EXPIRY-DATE               PIC X(10).
          03 CA-COK-LASTCHANGED               PIC X(26).
          03 CA-COK-BROKERID                  PIC 9(10).
          03 CA-COK-BROKERSREF                PIC X(10).
          03 CA-COK-PAYMENT                   PIC 9(6).
          03 CA-COK-CONTRACT-TYPE-CODE        PIC X(3).
          03 CA-COK-INDEMNITY-LIMIT           PIC 9(9).
          03 CA-COK-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-COK-TERRITORY-CODE            PIC X(3).
