******************************************************************
*  COPYBOOK  : GCORC001
*  KIND      : COMMAREA
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : OR
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-COR-REQUEST-ID        PIC X(6).
     03 CA-COR-RETURN-CODE       PIC 9(2).
     03 CA-COR-POLICY-NUM        PIC 9(10).
     03 CA-COR-CUSTOMER-NUM      PIC 9(10).

          03 CA-COR-ISSUE-DATE                PIC X(10).
          03 CA-COR-EXPIRY-DATE               PIC X(10).
          03 CA-COR-LASTCHANGED               PIC X(26).
          03 CA-COR-BROKERID                  PIC 9(10).
          03 CA-COR-BROKERSREF                PIC X(10).
          03 CA-COR-PAYMENT                   PIC 9(6).
          03 CA-COR-CONTRACT-TYPE-CODE        PIC X(3).
          03 CA-COR-INDEMNITY-LIMIT           PIC 9(9).
          03 CA-COR-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-COR-TERRITORY-CODE            PIC X(3).
