******************************************************************
*  COPYBOOK  : GCPAC001
*  KIND      : COMMAREA
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : PA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-CPA-REQUEST-ID        PIC X(6).
     03 CA-CPA-RETURN-CODE       PIC 9(2).
     03 CA-CPA-POLICY-NUM        PIC 9(10).
     03 CA-CPA-CUSTOMER-NUM      PIC 9(10).

          03 CA-CPA-ISSUE-DATE                PIC X(10).
          03 CA-CPA-EXPIRY-DATE               PIC X(10).
          03 CA-CPA-LASTCHANGED               PIC X(26).
          03 CA-CPA-BROKERID                  PIC 9(10).
          03 CA-CPA-BROKERSREF                PIC X(10).
          03 CA-CPA-PAYMENT                   PIC 9(6).
          03 CA-CPA-CONTRACT-TYPE-CODE        PIC X(3).
          03 CA-CPA-INDEMNITY-LIMIT           PIC 9(9).
          03 CA-CPA-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-CPA-TERRITORY-CODE            PIC X(3).
