******************************************************************
*  COPYBOOK  : GCRIC001
*  KIND      : COMMAREA
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : RI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-CRI-REQUEST-ID        PIC X(6).
     03 CA-CRI-RETURN-CODE       PIC 9(2).
     03 CA-CRI-POLICY-NUM        PIC 9(10).
     03 CA-CRI-CUSTOMER-NUM      PIC 9(10).

          03 CA-CRI-ISSUE-DATE                PIC X(10).
          03 CA-CRI-EXPIRY-DATE               PIC X(10).
          03 CA-CRI-LASTCHANGED               PIC X(26).
          03 CA-CRI-BROKERID                  PIC 9(10).
          03 CA-CRI-BROKERSREF                PIC X(10).
          03 CA-CRI-PAYMENT                   PIC 9(6).
          03 CA-CRI-CONTRACT-TYPE-CODE        PIC X(3).
          03 CA-CRI-INDEMNITY-LIMIT           PIC 9(9).
          03 CA-CRI-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-CRI-TERRITORY-CODE            PIC X(3).
