******************************************************************
*  COPYBOOK  : GCSCP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : SC
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-CSC-POLICY.

          03 DB2-CSC-ISSUE-DATE               PIC X(10).
          03 DB2-CSC-EXPIRY-DATE              PIC X(10).
          03 DB2-CSC-LASTCHANGED              PIC X(26).
          03 DB2-CSC-BROKERID                 PIC 9(10).
          03 DB2-CSC-BROKERSREF               PIC X(10).
          03 DB2-CSC-PAYMENT                  PIC 9(6).
          03 DB2-CSC-CONTRACT-TYPE-CODE       PIC X(3).
          03 DB2-CSC-INDEMNITY-LIMIT          PIC 9(9).
          03 DB2-CSC-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-CSC-TERRITORY-CODE           PIC X(3).
