******************************************************************
*  COPYBOOK  : GCSCC001
*  KIND      : COMMAREA
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : SC
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-CSC-REQUEST-ID        PIC X(6).
     03 CA-CSC-RETURN-CODE       PIC 9(2).
     03 CA-CSC-POLICY-NUM        PIC 9(10).
     03 CA-CSC-CUSTOMER-NUM      PIC 9(10).

          03 CA-CSC-ISSUE-DATE                PIC X(10).
          03 CA-CSC-EXPIRY-DATE               PIC X(10).
          03 CA-CSC-LASTCHANGED               PIC X(26).
          03 CA-CSC-BROKERID                  PIC 9(10).
          03 CA-CSC-BROKERSREF                PIC X(10).
          03 CA-CSC-PAYMENT                   PIC 9(6).
          03 CA-CSC-CONTRACT-TYPE-CODE        PIC X(3).
          03 CA-CSC-INDEMNITY-LIMIT           PIC 9(9).
          03 CA-CSC-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-CSC-TERRITORY-CODE            PIC X(3).
