******************************************************************
*  COPYBOOK  : GCTXP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : TX
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-CTX-POLICY.

          03 DB2-CTX-ISSUE-DATE               PIC X(10).
          03 DB2-CTX-EXPIRY-DATE              PIC X(10).
          03 DB2-CTX-LASTCHANGED              PIC X(26).
          03 DB2-CTX-BROKERID                 PIC 9(10).
          03 DB2-CTX-BROKERSREF               PIC X(10).
          03 DB2-CTX-PAYMENT                  PIC 9(6).
          03 DB2-CTX-CONTRACT-TYPE-CODE       PIC X(3).
          03 DB2-CTX-INDEMNITY-LIMIT          PIC 9(9).
          03 DB2-CTX-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-CTX-TERRITORY-CODE           PIC X(3).
