******************************************************************
*  COPYBOOK  : GCTXC001
*  KIND      : COMMAREA
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : TX
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-CTX-REQUEST-ID        PIC X(6).
     03 CA-CTX-RETURN-CODE       PIC 9(2).
     03 CA-CTX-POLICY-NUM        PIC 9(10).
     03 CA-CTX-CUSTOMER-NUM      PIC 9(10).

          03 CA-CTX-ISSUE-DATE                PIC X(10).
          03 CA-CTX-EXPIRY-DATE               PIC X(10).
          03 CA-CTX-LASTCHANGED               PIC X(26).
          03 CA-CTX-BROKERID                  PIC 9(10).
          03 CA-CTX-BROKERSREF                PIC X(10).
          03 CA-CTX-PAYMENT                   PIC 9(6).
          03 CA-CTX-CONTRACT-TYPE-CODE        PIC X(3).
          03 CA-CTX-INDEMNITY-LIMIT           PIC 9(9).
          03 CA-CTX-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-CTX-TERRITORY-CODE            PIC X(3).
