******************************************************************
*  COPYBOOK  : GCVAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : VA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-CVA-POLICY.

          03 DB2-CVA-ISSUE-DATE               PIC X(10).
          03 DB2-CVA-EXPIRY-DATE              PIC X(10).
          03 DB2-CVA-LASTCHANGED              PIC X(26).
          03 DB2-CVA-BROKERID                 PIC 9(10).
          03 DB2-CVA-BROKERSREF               PIC X(10).
          03 DB2-CVA-PAYMENT                  PIC 9(6).
          03 DB2-CVA-CONTRACT-TYPE-CODE       PIC X(3).
          03 DB2-CVA-INDEMNITY-LIMIT          PIC 9(9).
          03 DB2-CVA-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-CVA-TERRITORY-CODE           PIC X(3).
