******************************************************************
*  COPYBOOK  : GCVTP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : VT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-CVT-POLICY.

          03 DB2-CVT-ISSUE-DATE               PIC X(10).
          03 DB2-CVT-EXPIRY-DATE              PIC X(10).
          03 DB2-CVT-LASTCHANGED              PIC X(26).
          03 DB2-CVT-BROKERID                 PIC 9(10).
          03 DB2-CVT-BROKERSREF               PIC X(10).
          03 DB2-CVT-PAYMENT                  PIC 9(6).
          03 DB2-CVT-CONTRACT-TYPE-CODE       PIC X(3).
          03 DB2-CVT-INDEMNITY-LIMIT          PIC 9(9).
          03 DB2-CVT-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-CVT-TERRITORY-CODE           PIC X(3).
