******************************************************************
*  COPYBOOK  : GCWAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : WA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-CWA-POLICY.

          03 DB2-CWA-ISSUE-DATE               PIC X(10).
          03 DB2-CWA-EXPIRY-DATE              PIC X(10).
          03 DB2-CWA-LASTCHANGED              PIC X(26).
          03 DB2-CWA-BROKERID                 PIC 9(10).
          03 DB2-CWA-BROKERSREF               PIC X(10).
          03 DB2-CWA-PAYMENT                  PIC 9(6).
          03 DB2-CWA-CONTRACT-TYPE-CODE       PIC X(3).
          03 DB2-CWA-INDEMNITY-LIMIT          PIC 9(9).
          03 DB2-CWA-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-CWA-TERRITORY-CODE           PIC X(3).
