******************************************************************
*  COPYBOOK  : GCWIC001
*  KIND      : COMMAREA
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : WI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-CWI-REQUEST-ID        PIC X(6).
     03 CA-CWI-RETURN-CODE       PIC 9(2).
     03 CA-CWI-POLICY-NUM        PIC 9(10).
     03 CA-CWI-CUSTOMER-NUM      PIC 9(10).

          03 CA-CWI-ISSUE-DATE                PIC X(10).
          03 CA-CWI-EXPIRY-DATE               PIC X(10).
          03 CA-CWI-LASTCHANGED               PIC X(26).
          03 CA-CWI-BROKERID                  PIC 9(10).
          03 CA-CWI-BROKERSREF                PIC X(10).
          03 CA-CWI-PAYMENT                   PIC 9(6).
          03 CA-CWI-CONTRACT-TYPE-CODE        PIC X(3).
          03 CA-CWI-INDEMNITY-LIMIT           PIC 9(9).
          03 CA-CWI-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-CWI-TERRITORY-CODE            PIC X(3).
