******************************************************************
*  COPYBOOK  : GCWVP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : WV
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-CWV-POLICY.

          03 DB2-CWV-ISSUE-DATE               PIC X(10).
          03 DB2-CWV-EXPIRY-DATE              PIC X(10).
          03 DB2-CWV-LASTCHANGED              PIC X(26).
          03 DB2-CWV-BROKERID                 PIC 9(10).
          03 DB2-CWV-BROKERSREF               PIC X(10).
          03 DB2-CWV-PAYMENT                  PIC 9(6).
          03 DB2-CWV-CONTRACT-TYPE-CODE       PIC X(3).
          03 DB2-CWV-INDEMNITY-LIMIT          PIC 9(9).
          03 DB2-CWV-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-CWV-TERRITORY-CODE           PIC X(3).
