******************************************************************
*  COPYBOOK  : GCWVC001
*  KIND      : COMMAREA
*  COVERAGE  : Contractual Liability (CL)
*  STATE     : WV
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-CWV-REQUEST-ID        PIC X(6).
     03 CA-CWV-RETURN-CODE       PIC 9(2).
     03 CA-CWV-POLICY-NUM        PIC 9(10).
     03 CA-CWV-CUSTOMER-NUM      PIC 9(10).

          03 CA-CWV-ISSUE-DATE                PIC X(10).
          03 CA-CWV-EXPIRY-DATE               PIC X(10).
          03 CA-CWV-LASTCHANGED               PIC X(26).
          03 CA-CWV-BROKERID                  PIC 9(10).
          03 CA-CWV-BROKERSREF                PIC X(10).
          03 CA-CWV-PAYMENT                   PIC 9(6).
          03 CA-CWV-CONTRACT-TYPE-CODE        PIC X(3).
          03 CA-CWV-INDEMNITY-LIMIT           PIC 9(9).
          03 CA-CWV-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-CWV-TERRITORY-CODE            PIC X(3).
