******************************************************************
*  COPYBOOK  : GNAZC001
*  KIND      : COMMAREA
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : AZ
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-NAZ-REQUEST-ID        PIC X(6).
     03 CA-NAZ-RETURN-CODE       PIC 9(2).
     03 CA-NAZ-POLICY-NUM        PIC 9(10).
     03 CA-NAZ-CUSTOMER-NUM      PIC 9(10).

          03 CA-NAZ-ISSUE-DATE                PIC X(10).
          03 CA-NAZ-EXPIRY-DATE               PIC X(10).
          03 CA-NAZ-LASTCHANGED               PIC X(26).
          03 CA-NAZ-BROKERID                  PIC 9(10).
          03 CA-NAZ-BROKERSREF                PIC X(10).
          03 CA-NAZ-PAYMENT                   PIC 9(6).
          03 CA-NAZ-POLLUTANT-TYPE-CODE       PIC X(3).
          03 CA-NAZ-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-NAZ-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-NAZ-CLEANUP-COST-LIMIT        PIC 9(9).
          03 CA-NAZ-BASE-RATE                 PIC 9(4)V9(4).
