******************************************************************
*  COPYBOOK  : GNCAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : CA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-NCA-POLICY.

          03 DB2-NCA-ISSUE-DATE               PIC X(10).
          03 DB2-NCA-EXPIRY-DATE              PIC X(10).
          03 DB2-NCA-LASTCHANGED              PIC X(26).
          03 DB2-NCA-BROKERID                 PIC 9(10).
          03 DB2-NCA-BROKERSREF               PIC X(10).
          03 DB2-NCA-PAYMENT                  PIC 9(6).
          03 DB2-NCA-POLLUTANT-TYPE-CODE      PIC X(3).
          03 DB2-NCA-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-NCA-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-NCA-CLEANUP-COST-LIMIT       PIC 9(9).
          03 DB2-NCA-BASE-RATE                PIC 9(4)V9(4).
