******************************************************************
*  COPYBOOK  : GNCOP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : CO
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-NCO-POLICY.

          03 DB2-NCO-ISSUE-DATE               PIC X(10).
          03 DB2-NCO-EXPIRY-DATE              PIC X(10).
          03 DB2-NCO-LASTCHANGED              PIC X(26).
          03 DB2-NCO-BROKERID                 PIC 9(10).
          03 DB2-NCO-BROKERSREF               PIC X(10).
          03 DB2-NCO-PAYMENT                  PIC 9(6).
          03 DB2-NCO-POLLUTANT-TYPE-CODE      PIC X(3).
          03 DB2-NCO-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-NCO-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-NCO-CLEANUP-COST-LIMIT       PIC 9(9).
          03 DB2-NCO-BASE-RATE                PIC 9(4)V9(4).
