******************************************************************
*  COPYBOOK  : GNDCC001
*  KIND      : COMMAREA
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : DC
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-NDC-REQUEST-ID        PIC X(6).
     03 CA-NDC-RETURN-CODE       PIC 9(2).
     03 CA-NDC-POLICY-NUM        PIC 9(10).
     03 CA-NDC-CUSTOMER-NUM      PIC 9(10).

          03 CA-NDC-ISSUE-DATE                PIC X(10).
          03 CA-NDC-EXPIRY-DATE               PIC X(10).
          03 CA-NDC-LASTCHANGED               PIC X(26).
          03 CA-NDC-BROKERID                  PIC 9(10).
          03 CA-NDC-BROKERSREF                PIC X(10).
          03 CA-NDC-PAYMENT                   PIC 9(6).
          03 CA-NDC-POLLUTANT-TYPE-CODE       PIC X(3).
          03 CA-NDC-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-NDC-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-NDC-CLEANUP-COST-LIMIT        PIC 9(9).
          03 CA-NDC-BASE-RATE                 PIC 9(4)V9(4).
