******************************************************************
*  COPYBOOK  : GNFLC001
*  KIND      : COMMAREA
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : FL
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-NFL-REQUEST-ID        PIC X(6).
     03 CA-NFL-RETURN-CODE       PIC 9(2).
     03 CA-NFL-POLICY-NUM        PIC 9(10).
     03 CA-NFL-CUSTOMER-NUM      PIC 9(10).

          03 CA-NFL-ISSUE-DATE                PIC X(10).
          03 CA-NFL-EXPIRY-DATE               PIC X(10).
          03 CA-NFL-LASTCHANGED               PIC X(26).
          03 CA-NFL-BROKERID                  PIC 9(10).
          03 CA-NFL-BROKERSREF                PIC X(10).
          03 CA-NFL-PAYMENT                   PIC 9(6).
          03 CA-NFL-POLLUTANT-TYPE-CODE       PIC X(3).
          03 CA-NFL-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-NFL-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-NFL-CLEANUP-COST-LIMIT        PIC 9(9).
          03 CA-NFL-BASE-RATE                 PIC 9(4)V9(4).
