******************************************************************
*  COPYBOOK  : GNGAC001
*  KIND      : COMMAREA
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : GA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-NGA-REQUEST-ID        PIC X(6).
     03 CA-NGA-RETURN-CODE       PIC 9(2).
     03 CA-NGA-POLICY-NUM        PIC 9(10).
     03 CA-NGA-CUSTOMER-NUM      PIC 9(10).

          03 CA-NGA-ISSUE-DATE                PIC X(10).
          03 CA-NGA-EXPIRY-DATE               PIC X(10).
          03 CA-NGA-LASTCHANGED               PIC X(26).
          03 CA-NGA-BROKERID                  PIC 9(10).
          03 CA-NGA-BROKERSREF                PIC X(10).
          03 CA-NGA-PAYMENT                   PIC 9(6).
          03 CA-NGA-POLLUTANT-TYPE-CODE       PIC X(3).
          03 CA-NGA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-NGA-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-NGA-CLEANUP-COST-LIMIT        PIC 9(9).
          03 CA-NGA-BASE-RATE                 PIC 9(4)V9(4).
