******************************************************************
*  COPYBOOK  : GNINP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : IN
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-NIN-POLICY.

          03 DB2-NIN-ISSUE-DATE               PIC X(10).
          03 DB2-NIN-EXPIRY-DATE              PIC X(10).
          03 DB2-NIN-LASTCHANGED              PIC X(26).
          03 DB2-NIN-BROKERID                 PIC 9(10).
          03 DB2-NIN-BROKERSREF               PIC X(10).
          03 DB2-NIN-PAYMENT                  PIC 9(6).
          03 DB2-NIN-POLLUTANT-TYPE-CODE      PIC X(3).
          03 DB2-NIN-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-NIN-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-NIN-CLEANUP-COST-LIMIT       PIC 9(9).
          03 DB2-NIN-BASE-RATE                PIC 9(4)V9(4).
