******************************************************************
*  COPYBOOK  : GNMIC001
*  KIND      : COMMAREA
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : MI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-NMI-REQUEST-ID        PIC X(6).
     03 CA-NMI-RETURN-CODE       PIC 9(2).
     03 CA-NMI-POLICY-NUM        PIC 9(10).
     03 CA-NMI-CUSTOMER-NUM      PIC 9(10).

          03 CA-NMI-ISSUE-DATE                PIC X(10).
          03 CA-NMI-EXPIRY-DATE               PIC X(10).
          03 CA-NMI-LASTCHANGED               PIC X(26).
          03 CA-NMI-BROKERID                  PIC 9(10).
          03 CA-NMI-BROKERSREF                PIC X(10).
          03 CA-NMI-PAYMENT                   PIC 9(6).
          03 CA-NMI-POLLUTANT-TYPE-CODE       PIC X(3).
          03 CA-NMI-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-NMI-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-NMI-CLEANUP-COST-LIMIT        PIC 9(9).
          03 CA-NMI-BASE-RATE                 PIC 9(4)V9(4).
