******************************************************************
*  COPYBOOK  : GNMOC001
*  KIND      : COMMAREA
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : MO
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-NMO-REQUEST-ID        PIC X(6).
     03 CA-NMO-RETURN-CODE       PIC 9(2).
     03 CA-NMO-POLICY-NUM        PIC 9(10).
     03 CA-NMO-CUSTOMER-NUM      PIC 9(10).

          03 CA-NMO-ISSUE-DATE                PIC X(10).
          03 CA-NMO-EXPIRY-DATE               PIC X(10).
          03 CA-NMO-LASTCHANGED               PIC X(26).
          03 CA-NMO-BROKERID                  PIC 9(10).
          03 CA-NMO-BROKERSREF                PIC X(10).
          03 CA-NMO-PAYMENT                   PIC 9(6).
          03 CA-NMO-POLLUTANT-TYPE-CODE       PIC X(3).
          03 CA-NMO-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-NMO-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-NMO-CLEANUP-COST-LIMIT        PIC 9(9).
          03 CA-NMO-BASE-RATE                 PIC 9(4)V9(4).
