******************************************************************
*  COPYBOOK  : GNMOP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : MO
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-NMO-POLICY.

          03 DB2-NMO-ISSUE-DATE               PIC X(10).
          03 DB2-NMO-EXPIRY-DATE              PIC X(10).
          03 DB2-NMO-LASTCHANGED              PIC X(26).
          03 DB2-NMO-BROKERID                 PIC 9(10).
          03 DB2-NMO-BROKERSREF               PIC X(10).
          03 DB2-NMO-PAYMENT                  PIC 9(6).
          03 DB2-NMO-POLLUTANT-TYPE-CODE      PIC X(3).
          03 DB2-NMO-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-NMO-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-NMO-CLEANUP-COST-LIMIT       PIC 9(9).
          03 DB2-NMO-BASE-RATE                PIC 9(4)V9(4).
