******************************************************************
*  COPYBOOK  : GNMSP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : MS
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-NMS-POLICY.

          03 DB2-NMS-ISSUE-DATE               PIC X(10).
          03 DB2-NMS-EXPIRY-DATE              PIC X(10).
          03 DB2-NMS-LASTCHANGED              PIC X(26).
          03 DB2-NMS-BROKERID                 PIC 9(10).
          03 DB2-NMS-BROKERSREF               PIC X(10).
          03 DB2-NMS-PAYMENT                  PIC 9(6).
          03 DB2-NMS-POLLUTANT-TYPE-CODE      PIC X(3).
          03 DB2-NMS-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-NMS-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-NMS-CLEANUP-COST-LIMIT       PIC 9(9).
          03 DB2-NMS-BASE-RATE                PIC 9(4)V9(4).
