******************************************************************
*  COPYBOOK  : GNNDC001
*  KIND      : COMMAREA
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : ND
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-NND-REQUEST-ID        PIC X(6).
     03 CA-NND-RETURN-CODE       PIC 9(2).
     03 CA-NND-POLICY-NUM        PIC 9(10).
     03 CA-NND-CUSTOMER-NUM      PIC 9(10).

          03 CA-NND-ISSUE-DATE                PIC X(10).
          03 CA-NND-EXPIRY-DATE               PIC X(10).
          03 CA-NND-LASTCHANGED               PIC X(26).
          03 CA-NND-BROKERID                  PIC 9(10).
          03 CA-NND-BROKERSREF                PIC X(10).
          03 CA-NND-PAYMENT                   PIC 9(6).
          03 CA-NND-POLLUTANT-TYPE-CODE       PIC X(3).
          03 CA-NND-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-NND-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-NND-CLEANUP-COST-LIMIT        PIC 9(9).
          03 CA-NND-BASE-RATE                 PIC 9(4)V9(4).
