******************************************************************
*  COPYBOOK  : GNNEP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : NE
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-NNE-POLICY.

          03 DB2-NNE-ISSUE-DATE               PIC X(10).
          03 DB2-NNE-EXPIRY-DATE              PIC X(10).
          03 DB2-NNE-LASTCHANGED              PIC X(26).
          03 DB2-NNE-BROKERID                 PIC 9(10).
          03 DB2-NNE-BROKERSREF               PIC X(10).
          03 DB2-NNE-PAYMENT                  PIC 9(6).
          03 DB2-NNE-POLLUTANT-TYPE-CODE      PIC X(3).
          03 DB2-NNE-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-NNE-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-NNE-CLEANUP-COST-LIMIT       PIC 9(9).
          03 DB2-NNE-BASE-RATE                PIC 9(4)V9(4).
