******************************************************************
*  COPYBOOK  : GNNHC001
*  KIND      : COMMAREA
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : NH
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-NNH-REQUEST-ID        PIC X(6).
     03 CA-NNH-RETURN-CODE       PIC 9(2).
     03 CA-NNH-POLICY-NUM        PIC 9(10).
     03 CA-NNH-CUSTOMER-NUM      PIC 9(10).

          03 CA-NNH-ISSUE-DATE                PIC X(10).
          03 CA-NNH-EXPIRY-DATE               PIC X(10).
          03 CA-NNH-LASTCHANGED               PIC X(26).
          03 CA-NNH-BROKERID                  PIC 9(10).
          03 CA-NNH-BROKERSREF                PIC X(10).
          03 CA-NNH-PAYMENT                   PIC 9(6).
          03 CA-NNH-POLLUTANT-TYPE-CODE       PIC X(3).
          03 CA-NNH-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-NNH-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-NNH-CLEANUP-COST-LIMIT        PIC 9(9).
          03 CA-NNH-BASE-RATE                 PIC 9(4)V9(4).
