******************************************************************
*  COPYBOOK  : GNNMC001
*  KIND      : COMMAREA
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : NM
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-NNM-REQUEST-ID        PIC X(6).
     03 CA-NNM-RETURN-CODE       PIC 9(2).
     03 CA-NNM-POLICY-NUM        PIC 9(10).
     03 CA-NNM-CUSTOMER-NUM      PIC 9(10).

          03 CA-NNM-ISSUE-DATE                PIC X(10).
          03 CA-NNM-EXPIRY-DATE               PIC X(10).
          03 CA-NNM-LASTCHANGED               PIC X(26).
          03 CA-NNM-BROKERID                  PIC 9(10).
          03 CA-NNM-BROKERSREF                PIC X(10).
          03 CA-NNM-PAYMENT                   PIC 9(6).
          03 CA-NNM-POLLUTANT-TYPE-CODE       PIC X(3).
          03 CA-NNM-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-NNM-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-NNM-CLEANUP-COST-LIMIT        PIC 9(9).
          03 CA-NNM-BASE-RATE                 PIC 9(4)V9(4).
