******************************************************************
*  COPYBOOK  : GNNMP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : NM
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-NNM-POLICY.

          03 DB2-NNM-ISSUE-DATE               PIC X(10).
          03 DB2-NNM-EXPIRY-DATE              PIC X(10).
          03 DB2-NNM-LASTCHANGED              PIC X(26).
          03 DB2-NNM-BROKERID                 PIC 9(10).
          03 DB2-NNM-BROKERSREF               PIC X(10).
          03 DB2-NNM-PAYMENT                  PIC 9(6).
          03 DB2-NNM-POLLUTANT-TYPE-CODE      PIC X(3).
          03 DB2-NNM-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-NNM-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-NNM-CLEANUP-COST-LIMIT       PIC 9(9).
          03 DB2-NNM-BASE-RATE                PIC 9(4)V9(4).
