******************************************************************
*  COPYBOOK  : GNNYP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : NY
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-NNY-POLICY.

          03 DB2-NNY-ISSUE-DATE               PIC X(10).
          03 DB2-NNY-EXPIRY-DATE              PIC X(10).
          03 DB2-NNY-LASTCHANGED              PIC X(26).
          03 DB2-NNY-BROKERID                 PIC 9(10).
          03 DB2-NNY-BROKERSREF               PIC X(10).
          03 DB2-NNY-PAYMENT                  PIC 9(6).
          03 DB2-NNY-POLLUTANT-TYPE-CODE      PIC X(3).
          03 DB2-NNY-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-NNY-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-NNY-CLEANUP-COST-LIMIT       PIC 9(9).
          03 DB2-NNY-BASE-RATE                PIC 9(4)V9(4).
