******************************************************************
*  COPYBOOK  : GNOKP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : OK
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-NOK-POLICY.

          03 DB2-NOK-ISSUE-DATE               PIC X(10).
          03 DB2-NOK-EXPIRY-DATE              PIC X(10).
          03 DB2-NOK-LASTCHANGED              PIC X(26).
          03 DB2-NOK-BROKERID                 PIC 9(10).
          03 DB2-NOK-BROKERSREF               PIC X(10).
          03 DB2-NOK-PAYMENT                  PIC 9(6).
          03 DB2-NOK-POLLUTANT-TYPE-CODE      PIC X(3).
          03 DB2-NOK-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-NOK-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-NOK-CLEANUP-COST-LIMIT       PIC 9(9).
          03 DB2-NOK-BASE-RATE                PIC 9(4)V9(4).
