******************************************************************
*  COPYBOOK  : GNOKC001
*  KIND      : COMMAREA
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : OK
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-NOK-REQUEST-ID        PIC X(6).
     03 CA-NOK-RETURN-CODE       PIC 9(2).
     03 CA-NOK-POLICY-NUM        PIC 9(10).
     03 CA-NOK-CUSTOMER-NUM      PIC 9(10).

          03 CA-NOK-ISSUE-DATE                PIC X(10).
          03 CA-NOK-EXPIRY-DATE               PIC X(10).
          03 CA-NOK-LASTCHANGED               PIC X(26).
          03 CA-NOK-BROKERID                  PIC 9(10).
          03 CA-NOK-BROKERSREF                PIC X(10).
          03 CA-NOK-PAYMENT                   PIC 9(6).
          03 CA-NOK-POLLUTANT-TYPE-CODE       PIC X(3).
          03 CA-NOK-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-NOK-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-NOK-CLEANUP-COST-LIMIT        PIC 9(9).
          03 CA-NOK-BASE-RATE                 PIC 9(4)V9(4).
