******************************************************************
*  COPYBOOK  : GNPAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : PA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-NPA-POLICY.

          03 DB2-NPA-ISSUE-DATE               PIC X(10).
          03 DB2-NPA-EXPIRY-DATE              PIC X(10).
          03 DB2-NPA-LASTCHANGED              PIC X(26).
          03 DB2-NPA-BROKERID                 PIC 9(10).
          03 DB2-NPA-BROKERSREF               PIC X(10).
          03 DB2-NPA-PAYMENT                  PIC 9(6).
          03 DB2-NPA-POLLUTANT-TYPE-CODE      PIC X(3).
          03 DB2-NPA-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-NPA-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-NPA-CLEANUP-COST-LIMIT       PIC 9(9).
          03 DB2-NPA-BASE-RATE                PIC 9(4)V9(4).
