******************************************************************
*  COPYBOOK  : GNPAC001
*  KIND      : COMMAREA
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : PA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-NPA-REQUEST-ID        PIC X(6).
     03 CA-NPA-RETURN-CODE       PIC 9(2).
     03 CA-NPA-POLICY-NUM        PIC 9(10).
     03 CA-NPA-CUSTOMER-NUM      PIC 9(10).

          03 CA-NPA-ISSUE-DATE                PIC X(10).
          03 CA-NPA-EXPIRY-DATE               PIC X(10).
          03 CA-NPA-LASTCHANGED               PIC X(26).
          03 CA-NPA-BROKERID                  PIC 9(10).
          03 CA-NPA-BROKERSREF                PIC X(10).
          03 CA-NPA-PAYMENT                   PIC 9(6).
          03 CA-NPA-POLLUTANT-TYPE-CODE       PIC X(3).
          03 CA-NPA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-NPA-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-NPA-CLEANUP-COST-LIMIT        PIC 9(9).
          03 CA-NPA-BASE-RATE                 PIC 9(4)V9(4).
