******************************************************************
*  COPYBOOK  : GNRIC001
*  KIND      : COMMAREA
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : RI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-NRI-REQUEST-ID        PIC X(6).
     03 CA-NRI-RETURN-CODE       PIC 9(2).
     03 CA-NRI-POLICY-NUM        PIC 9(10).
     03 CA-NRI-CUSTOMER-NUM      PIC 9(10).

          03 CA-NRI-ISSUE-DATE                PIC X(10).
          03 CA-NRI-EXPIRY-DATE               PIC X(10).
          03 CA-NRI-LASTCHANGED               PIC X(26).
          03 CA-NRI-BROKERID                  PIC 9(10).
          03 CA-NRI-BROKERSREF                PIC X(10).
          03 CA-NRI-PAYMENT                   PIC 9(6).
          03 CA-NRI-POLLUTANT-TYPE-CODE       PIC X(3).
          03 CA-NRI-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-NRI-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-NRI-CLEANUP-COST-LIMIT        PIC 9(9).
          03 CA-NRI-BASE-RATE                 PIC 9(4)V9(4).
