******************************************************************
*  COPYBOOK  : GNVAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : VA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-NVA-POLICY.

          03 DB2-NVA-ISSUE-DATE               PIC X(10).
          03 DB2-NVA-EXPIRY-DATE              PIC X(10).
          03 DB2-NVA-LASTCHANGED              PIC X(26).
          03 DB2-NVA-BROKERID                 PIC 9(10).
          03 DB2-NVA-BROKERSREF               PIC X(10).
          03 DB2-NVA-PAYMENT                  PIC 9(6).
          03 DB2-NVA-POLLUTANT-TYPE-CODE      PIC X(3).
          03 DB2-NVA-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-NVA-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-NVA-CLEANUP-COST-LIMIT       PIC 9(9).
          03 DB2-NVA-BASE-RATE                PIC 9(4)V9(4).
