******************************************************************
*  COPYBOOK  : GNVTC001
*  KIND      : COMMAREA
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : VT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-NVT-REQUEST-ID        PIC X(6).
     03 CA-NVT-RETURN-CODE       PIC 9(2).
     03 CA-NVT-POLICY-NUM        PIC 9(10).
     03 CA-NVT-CUSTOMER-NUM      PIC 9(10).

          03 CA-NVT-ISSUE-DATE                PIC X(10).
          03 CA-NVT-EXPIRY-DATE               PIC X(10).
          03 CA-NVT-LASTCHANGED               PIC X(26).
          03 CA-NVT-BROKERID                  PIC 9(10).
          03 CA-NVT-BROKERSREF                PIC X(10).
          03 CA-NVT-PAYMENT                   PIC 9(6).
          03 CA-NVT-POLLUTANT-TYPE-CODE       PIC X(3).
          03 CA-NVT-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-NVT-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-NVT-CLEANUP-COST-LIMIT        PIC 9(9).
          03 CA-NVT-BASE-RATE                 PIC 9(4)V9(4).
