******************************************************************
*  COPYBOOK  : GNVTP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : VT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-NVT-POLICY.

          03 DB2-NVT-ISSUE-DATE               PIC X(10).
          03 DB2-NVT-EXPIRY-DATE              PIC X(10).
          03 DB2-NVT-LASTCHANGED              PIC X(26).
          03 DB2-NVT-BROKERID                 PIC 9(10).
          03 DB2-NVT-BROKERSREF               PIC X(10).
          03 DB2-NVT-PAYMENT                  PIC 9(6).
          03 DB2-NVT-POLLUTANT-TYPE-CODE      PIC X(3).
          03 DB2-NVT-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-NVT-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-NVT-CLEANUP-COST-LIMIT       PIC 9(9).
          03 DB2-NVT-BASE-RATE                PIC 9(4)V9(4).
