******************************************************************
*  COPYBOOK  : GNWAC001
*  KIND      : COMMAREA
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : WA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-NWA-REQUEST-ID        PIC X(6).
     03 CA-NWA-RETURN-CODE       PIC 9(2).
     03 CA-NWA-POLICY-NUM        PIC 9(10).
     03 CA-NWA-CUSTOMER-NUM      PIC 9(10).

          03 CA-NWA-ISSUE-DATE                PIC X(10).
          03 CA-NWA-EXPIRY-DATE               PIC X(10).
          03 CA-NWA-LASTCHANGED               PIC X(26).
          03 CA-NWA-BROKERID                  PIC 9(10).
          03 CA-NWA-BROKERSREF                PIC X(10).
          03 CA-NWA-PAYMENT                   PIC 9(6).
          03 CA-NWA-POLLUTANT-TYPE-CODE       PIC X(3).
          03 CA-NWA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-NWA-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-NWA-CLEANUP-COST-LIMIT        PIC 9(9).
          03 CA-NWA-BASE-RATE                 PIC 9(4)V9(4).
