******************************************************************
*  COPYBOOK  : GNWIP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : WI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-NWI-POLICY.

          03 DB2-NWI-ISSUE-DATE               PIC X(10).
          03 DB2-NWI-EXPIRY-DATE              PIC X(10).
          03 DB2-NWI-LASTCHANGED              PIC X(26).
          03 DB2-NWI-BROKERID                 PIC 9(10).
          03 DB2-NWI-BROKERSREF               PIC X(10).
          03 DB2-NWI-PAYMENT                  PIC 9(6).
          03 DB2-NWI-POLLUTANT-TYPE-CODE      PIC X(3).
          03 DB2-NWI-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-NWI-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-NWI-CLEANUP-COST-LIMIT       PIC 9(9).
          03 DB2-NWI-BASE-RATE                PIC 9(4)V9(4).
