******************************************************************
*  COPYBOOK  : GNWYP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : WY
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-NWY-POLICY.

          03 DB2-NWY-ISSUE-DATE               PIC X(10).
          03 DB2-NWY-EXPIRY-DATE              PIC X(10).
          03 DB2-NWY-LASTCHANGED              PIC X(26).
          03 DB2-NWY-BROKERID                 PIC 9(10).
          03 DB2-NWY-BROKERSREF               PIC X(10).
          03 DB2-NWY-PAYMENT                  PIC 9(6).
          03 DB2-NWY-POLLUTANT-TYPE-CODE      PIC X(3).
          03 DB2-NWY-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-NWY-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-NWY-CLEANUP-COST-LIMIT       PIC 9(9).
          03 DB2-NWY-BASE-RATE                PIC 9(4)V9(4).
