******************************************************************
*  COPYBOOK  : GNWYC001
*  KIND      : COMMAREA
*  COVERAGE  : Limited Pollution Liability (PL)
*  STATE     : WY
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-NWY-REQUEST-ID        PIC X(6).
     03 CA-NWY-RETURN-CODE       PIC 9(2).
     03 CA-NWY-POLICY-NUM        PIC 9(10).
     03 CA-NWY-CUSTOMER-NUM      PIC 9(10).

          03 CA-NWY-ISSUE-DATE                PIC X(10).
          03 CA-NWY-EXPIRY-DATE               PIC X(10).
          03 CA-NWY-LASTCHANGED               PIC X(26).
          03 CA-NWY-BROKERID                  PIC 9(10).
          03 CA-NWY-BROKERSREF                PIC X(10).
          03 CA-NWY-PAYMENT                   PIC 9(6).
          03 CA-NWY-POLLUTANT-TYPE-CODE       PIC X(3).
          03 CA-NWY-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-NWY-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-NWY-CLEANUP-COST-LIMIT        PIC 9(9).
          03 CA-NWY-BASE-RATE                 PIC 9(4)V9(4).
