******************************************************************
*  COPYBOOK  : GPALC001
*  KIND      : COMMAREA
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : AL
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-PAL-REQUEST-ID        PIC X(6).
     03 CA-PAL-RETURN-CODE       PIC 9(2).
     03 CA-PAL-POLICY-NUM        PIC 9(10).
     03 CA-PAL-CUSTOMER-NUM      PIC 9(10).

          03 CA-PAL-ISSUE-DATE                PIC X(10).
          03 CA-PAL-EXPIRY-DATE               PIC X(10).
          03 CA-PAL-LASTCHANGED               PIC X(26).
          03 CA-PAL-BROKERID                  PIC 9(10).
          03 CA-PAL-BROKERSREF                PIC X(10).
          03 CA-PAL-PAYMENT                   PIC 9(6).
          03 CA-PAL-CLASS-CODE                PIC X(4).
          03 CA-PAL-TERRITORY-CODE            PIC X(3).
          03 CA-PAL-EXPOSURE-BASIS            PIC X(1).
          03 CA-PAL-EXPOSURE-AMOUNT           PIC 9(9).
          03 CA-PAL-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-PAL-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-PAL-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-PAL-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-PAL-PREMISES-COUNT            PIC 9(3).
          03 CA-PAL-EXPERIENCE-MOD            PIC 9(1)V9(3).
