******************************************************************
*  COPYBOOK  : GPCAC001
*  KIND      : COMMAREA
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : CA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-PCA-REQUEST-ID        PIC X(6).
     03 CA-PCA-RETURN-CODE       PIC 9(2).
     03 CA-PCA-POLICY-NUM        PIC 9(10).
     03 CA-PCA-CUSTOMER-NUM      PIC 9(10).

          03 CA-PCA-ISSUE-DATE                PIC X(10).
          03 CA-PCA-EXPIRY-DATE               PIC X(10).
          03 CA-PCA-LASTCHANGED               PIC X(26).
          03 CA-PCA-BROKERID                  PIC 9(10).
          03 CA-PCA-BROKERSREF                PIC X(10).
          03 CA-PCA-PAYMENT                   PIC 9(6).
          03 CA-PCA-CLASS-CODE                PIC X(4).
          03 CA-PCA-TERRITORY-CODE            PIC X(3).
          03 CA-PCA-EXPOSURE-BASIS            PIC X(1).
          03 CA-PCA-EXPOSURE-AMOUNT           PIC 9(9).
          03 CA-PCA-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-PCA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-PCA-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-PCA-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-PCA-PREMISES-COUNT            PIC 9(3).
          03 CA-PCA-EXPERIENCE-MOD            PIC 9(1)V9(3).
