******************************************************************
*  COPYBOOK  : GPCOP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : CO
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-PCO-POLICY.

          03 DB2-PCO-ISSUE-DATE               PIC X(10).
          03 DB2-PCO-EXPIRY-DATE              PIC X(10).
          03 DB2-PCO-LASTCHANGED              PIC X(26).
          03 DB2-PCO-BROKERID                 PIC 9(10).
          03 DB2-PCO-BROKERSREF               PIC X(10).
          03 DB2-PCO-PAYMENT                  PIC 9(6).
          03 DB2-PCO-CLASS-CODE               PIC X(4).
          03 DB2-PCO-TERRITORY-CODE           PIC X(3).
          03 DB2-PCO-EXPOSURE-BASIS           PIC X(1).
          03 DB2-PCO-EXPOSURE-AMOUNT          PIC 9(9).
          03 DB2-PCO-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-PCO-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-PCO-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-PCO-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-PCO-PREMISES-COUNT           PIC 9(3).
          03 DB2-PCO-EXPERIENCE-MOD           PIC 9(1)V9(3).
