******************************************************************
*  COPYBOOK  : GPCTC001
*  KIND      : COMMAREA
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : CT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-PCT-REQUEST-ID        PIC X(6).
     03 CA-PCT-RETURN-CODE       PIC 9(2).
     03 CA-PCT-POLICY-NUM        PIC 9(10).
     03 CA-PCT-CUSTOMER-NUM      PIC 9(10).

          03 CA-PCT-ISSUE-DATE                PIC X(10).
          03 CA-PCT-EXPIRY-DATE               PIC X(10).
          03 CA-PCT-LASTCHANGED               PIC X(26).
          03 CA-PCT-BROKERID                  PIC 9(10).
          03 CA-PCT-BROKERSREF                PIC X(10).
          03 CA-PCT-PAYMENT                   PIC 9(6).
          03 CA-PCT-CLASS-CODE                PIC X(4).
          03 CA-PCT-TERRITORY-CODE            PIC X(3).
          03 CA-PCT-EXPOSURE-BASIS            PIC X(1).
          03 CA-PCT-EXPOSURE-AMOUNT           PIC 9(9).
          03 CA-PCT-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-PCT-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-PCT-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-PCT-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-PCT-PREMISES-COUNT            PIC 9(3).
          03 CA-PCT-EXPERIENCE-MOD            PIC 9(1)V9(3).
