******************************************************************
*  COPYBOOK  : GPDCP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : DC
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-PDC-POLICY.

          03 DB2-PDC-ISSUE-DATE               PIC X(10).
          03 DB2-PDC-EXPIRY-DATE              PIC X(10).
          03 DB2-PDC-LASTCHANGED              PIC X(26).
          03 DB2-PDC-BROKERID                 PIC 9(10).
          03 DB2-PDC-BROKERSREF               PIC X(10).
          03 DB2-PDC-PAYMENT                  PIC 9(6).
          03 DB2-PDC-CLASS-CODE               PIC X(4).
          03 DB2-PDC-TERRITORY-CODE           PIC X(3).
          03 DB2-PDC-EXPOSURE-BASIS           PIC X(1).
          03 DB2-PDC-EXPOSURE-AMOUNT          PIC 9(9).
          03 DB2-PDC-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-PDC-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-PDC-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-PDC-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-PDC-PREMISES-COUNT           PIC 9(3).
          03 DB2-PDC-EXPERIENCE-MOD           PIC 9(1)V9(3).
