******************************************************************
*  COPYBOOK  : GPFLC001
*  KIND      : COMMAREA
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : FL
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-PFL-REQUEST-ID        PIC X(6).
     03 CA-PFL-RETURN-CODE       PIC 9(2).
     03 CA-PFL-POLICY-NUM        PIC 9(10).
     03 CA-PFL-CUSTOMER-NUM      PIC 9(10).

          03 CA-PFL-ISSUE-DATE                PIC X(10).
          03 CA-PFL-EXPIRY-DATE               PIC X(10).
          03 CA-PFL-LASTCHANGED               PIC X(26).
          03 CA-PFL-BROKERID                  PIC 9(10).
          03 CA-PFL-BROKERSREF                PIC X(10).
          03 CA-PFL-PAYMENT                   PIC 9(6).
          03 CA-PFL-CLASS-CODE                PIC X(4).
          03 CA-PFL-TERRITORY-CODE            PIC X(3).
          03 CA-PFL-EXPOSURE-BASIS            PIC X(1).
          03 CA-PFL-EXPOSURE-AMOUNT           PIC 9(9).
          03 CA-PFL-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-PFL-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-PFL-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-PFL-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-PFL-PREMISES-COUNT            PIC 9(3).
          03 CA-PFL-EXPERIENCE-MOD            PIC 9(1)V9(3).
