******************************************************************
*  COPYBOOK  : GPGAC001
*  KIND      : COMMAREA
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : GA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-PGA-REQUEST-ID        PIC X(6).
     03 CA-PGA-RETURN-CODE       PIC 9(2).
     03 CA-PGA-POLICY-NUM        PIC 9(10).
     03 CA-PGA-CUSTOMER-NUM      PIC 9(10).

          03 CA-PGA-ISSUE-DATE                PIC X(10).
          03 CA-PGA-EXPIRY-DATE               PIC X(10).
          03 CA-PGA-LASTCHANGED               PIC X(26).
          03 CA-PGA-BROKERID                  PIC 9(10).
          03 CA-PGA-BROKERSREF                PIC X(10).
          03 CA-PGA-PAYMENT                   PIC 9(6).
          03 CA-PGA-CLASS-CODE                PIC X(4).
          03 CA-PGA-TERRITORY-CODE            PIC X(3).
          03 CA-PGA-EXPOSURE-BASIS            PIC X(1).
          03 CA-PGA-EXPOSURE-AMOUNT           PIC 9(9).
          03 CA-PGA-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-PGA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-PGA-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-PGA-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-PGA-PREMISES-COUNT            PIC 9(3).
          03 CA-PGA-EXPERIENCE-MOD            PIC 9(1)V9(3).
