******************************************************************
*  COPYBOOK  : GPHIC001
*  KIND      : COMMAREA
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : HI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-PHI-REQUEST-ID        PIC X(6).
     03 CA-PHI-RETURN-CODE       PIC 9(2).
     03 CA-PHI-POLICY-NUM        PIC 9(10).
     03 CA-PHI-CUSTOMER-NUM      PIC 9(10).

          03 CA-PHI-ISSUE-DATE                PIC X(10).
          03 CA-PHI-EXPIRY-DATE               PIC X(10).
          03 CA-PHI-LASTCHANGED               PIC X(26).
          03 CA-PHI-BROKERID                  PIC 9(10).
          03 CA-PHI-BROKERSREF                PIC X(10).
          03 CA-PHI-PAYMENT                   PIC 9(6).
          03 CA-PHI-CLASS-CODE                PIC X(4).
          03 CA-PHI-TERRITORY-CODE            PIC X(3).
          03 CA-PHI-EXPOSURE-BASIS            PIC X(1).
          03 CA-PHI-EXPOSURE-AMOUNT           PIC 9(9).
          03 CA-PHI-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-PHI-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-PHI-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-PHI-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-PHI-PREMISES-COUNT            PIC 9(3).
          03 CA-PHI-EXPERIENCE-MOD            PIC 9(1)V9(3).
