******************************************************************
*  COPYBOOK  : GPIDC001
*  KIND      : COMMAREA
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : ID
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-PID-REQUEST-ID        PIC X(6).
     03 CA-PID-RETURN-CODE       PIC 9(2).
     03 CA-PID-POLICY-NUM        PIC 9(10).
     03 CA-PID-CUSTOMER-NUM      PIC 9(10).

          03 CA-PID-ISSUE-DATE                PIC X(10).
          03 CA-PID-EXPIRY-DATE               PIC X(10).
          03 CA-PID-LASTCHANGED               PIC X(26).
          03 CA-PID-BROKERID                  PIC 9(10).
          03 CA-PID-BROKERSREF                PIC X(10).
          03 CA-PID-PAYMENT                   PIC 9(6).
          03 CA-PID-CLASS-CODE                PIC X(4).
          03 CA-PID-TERRITORY-CODE            PIC X(3).
          03 CA-PID-EXPOSURE-BASIS            PIC X(1).
          03 CA-PID-EXPOSURE-AMOUNT           PIC 9(9).
          03 CA-PID-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-PID-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-PID-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-PID-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-PID-PREMISES-COUNT            PIC 9(3).
          03 CA-PID-EXPERIENCE-MOD            PIC 9(1)V9(3).
