******************************************************************
*  COPYBOOK  : GPINP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : IN
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-PIN-POLICY.

          03 DB2-PIN-ISSUE-DATE               PIC X(10).
          03 DB2-PIN-EXPIRY-DATE              PIC X(10).
          03 DB2-PIN-LASTCHANGED              PIC X(26).
          03 DB2-PIN-BROKERID                 PIC 9(10).
          03 DB2-PIN-BROKERSREF               PIC X(10).
          03 DB2-PIN-PAYMENT                  PIC 9(6).
          03 DB2-PIN-CLASS-CODE               PIC X(4).
          03 DB2-PIN-TERRITORY-CODE           PIC X(3).
          03 DB2-PIN-EXPOSURE-BASIS           PIC X(1).
          03 DB2-PIN-EXPOSURE-AMOUNT          PIC 9(9).
          03 DB2-PIN-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-PIN-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-PIN-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-PIN-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-PIN-PREMISES-COUNT           PIC 9(3).
          03 DB2-PIN-EXPERIENCE-MOD           PIC 9(1)V9(3).
