******************************************************************
*  COPYBOOK  : GPKSP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : KS
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-PKS-POLICY.

          03 DB2-PKS-ISSUE-DATE               PIC X(10).
          03 DB2-PKS-EXPIRY-DATE              PIC X(10).
          03 DB2-PKS-LASTCHANGED              PIC X(26).
          03 DB2-PKS-BROKERID                 PIC 9(10).
          03 DB2-PKS-BROKERSREF               PIC X(10).
          03 DB2-PKS-PAYMENT                  PIC 9(6).
          03 DB2-PKS-CLASS-CODE               PIC X(4).
          03 DB2-PKS-TERRITORY-CODE           PIC X(3).
          03 DB2-PKS-EXPOSURE-BASIS           PIC X(1).
          03 DB2-PKS-EXPOSURE-AMOUNT          PIC 9(9).
          03 DB2-PKS-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-PKS-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-PKS-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-PKS-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-PKS-PREMISES-COUNT           PIC 9(3).
          03 DB2-PKS-EXPERIENCE-MOD           PIC 9(1)V9(3).
