******************************************************************
*  COPYBOOK  : GPMDP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : MD
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-PMD-POLICY.

          03 DB2-PMD-ISSUE-DATE               PIC X(10).
          03 DB2-PMD-EXPIRY-DATE              PIC X(10).
          03 DB2-PMD-LASTCHANGED              PIC X(26).
          03 DB2-PMD-BROKERID                 PIC 9(10).
          03 DB2-PMD-BROKERSREF               PIC X(10).
          03 DB2-PMD-PAYMENT                  PIC 9(6).
          03 DB2-PMD-CLASS-CODE               PIC X(4).
          03 DB2-PMD-TERRITORY-CODE           PIC X(3).
          03 DB2-PMD-EXPOSURE-BASIS           PIC X(1).
          03 DB2-PMD-EXPOSURE-AMOUNT          PIC 9(9).
          03 DB2-PMD-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-PMD-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-PMD-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-PMD-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-PMD-PREMISES-COUNT           PIC 9(3).
          03 DB2-PMD-EXPERIENCE-MOD           PIC 9(1)V9(3).
