******************************************************************
*  COPYBOOK  : GPMEP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : ME
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-PME-POLICY.

          03 DB2-PME-ISSUE-DATE               PIC X(10).
          03 DB2-PME-EXPIRY-DATE              PIC X(10).
          03 DB2-PME-LASTCHANGED              PIC X(26).
          03 DB2-PME-BROKERID                 PIC 9(10).
          03 DB2-PME-BROKERSREF               PIC X(10).
          03 DB2-PME-PAYMENT                  PIC 9(6).
          03 DB2-PME-CLASS-CODE               PIC X(4).
          03 DB2-PME-TERRITORY-CODE           PIC X(3).
          03 DB2-PME-EXPOSURE-BASIS           PIC X(1).
          03 DB2-PME-EXPOSURE-AMOUNT          PIC 9(9).
          03 DB2-PME-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-PME-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-PME-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-PME-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-PME-PREMISES-COUNT           PIC 9(3).
          03 DB2-PME-EXPERIENCE-MOD           PIC 9(1)V9(3).
