******************************************************************
*  COPYBOOK  : GPMIP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : MI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-PMI-POLICY.

          03 DB2-PMI-ISSUE-DATE               PIC X(10).
          03 DB2-PMI-EXPIRY-DATE              PIC X(10).
          03 DB2-PMI-LASTCHANGED              PIC X(26).
          03 DB2-PMI-BROKERID                 PIC 9(10).
          03 DB2-PMI-BROKERSREF               PIC X(10).
          03 DB2-PMI-PAYMENT                  PIC 9(6).
          03 DB2-PMI-CLASS-CODE               PIC X(4).
          03 DB2-PMI-TERRITORY-CODE           PIC X(3).
          03 DB2-PMI-EXPOSURE-BASIS           PIC X(1).
          03 DB2-PMI-EXPOSURE-AMOUNT          PIC 9(9).
          03 DB2-PMI-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-PMI-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-PMI-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-PMI-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-PMI-PREMISES-COUNT           PIC 9(3).
          03 DB2-PMI-EXPERIENCE-MOD           PIC 9(1)V9(3).
