******************************************************************
*  COPYBOOK  : GPMOC001
*  KIND      : COMMAREA
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : MO
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-PMO-REQUEST-ID        PIC X(6).
     03 CA-PMO-RETURN-CODE       PIC 9(2).
     03 CA-PMO-POLICY-NUM        PIC 9(10).
     03 CA-PMO-CUSTOMER-NUM      PIC 9(10).

          03 CA-PMO-ISSUE-DATE                PIC X(10).
          03 CA-PMO-EXPIRY-DATE               PIC X(10).
          03 CA-PMO-LASTCHANGED               PIC X(26).
          03 CA-PMO-BROKERID                  PIC 9(10).
          03 CA-PMO-BROKERSREF                PIC X(10).
          03 CA-PMO-PAYMENT                   PIC 9(6).
          03 CA-PMO-CLASS-CODE                PIC X(4).
          03 CA-PMO-TERRITORY-CODE            PIC X(3).
          03 CA-PMO-EXPOSURE-BASIS            PIC X(1).
          03 CA-PMO-EXPOSURE-AMOUNT           PIC 9(9).
          03 CA-PMO-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-PMO-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-PMO-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-PMO-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-PMO-PREMISES-COUNT            PIC 9(3).
          03 CA-PMO-EXPERIENCE-MOD            PIC 9(1)V9(3).
