******************************************************************
*  COPYBOOK  : GPMSC001
*  KIND      : COMMAREA
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : MS
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-PMS-REQUEST-ID        PIC X(6).
     03 CA-PMS-RETURN-CODE       PIC 9(2).
     03 CA-PMS-POLICY-NUM        PIC 9(10).
     03 CA-PMS-CUSTOMER-NUM      PIC 9(10).

          03 CA-PMS-ISSUE-DATE                PIC X(10).
          03 CA-PMS-EXPIRY-DATE               PIC X(10).
          03 CA-PMS-LASTCHANGED               PIC X(26).
          03 CA-PMS-BROKERID                  PIC 9(10).
          03 CA-PMS-BROKERSREF                PIC X(10).
          03 CA-PMS-PAYMENT                   PIC 9(6).
          03 CA-PMS-CLASS-CODE                PIC X(4).
          03 CA-PMS-TERRITORY-CODE            PIC X(3).
          03 CA-PMS-EXPOSURE-BASIS            PIC X(1).
          03 CA-PMS-EXPOSURE-AMOUNT           PIC 9(9).
          03 CA-PMS-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-PMS-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-PMS-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-PMS-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-PMS-PREMISES-COUNT            PIC 9(3).
          03 CA-PMS-EXPERIENCE-MOD            PIC 9(1)V9(3).
