******************************************************************
*  COPYBOOK  : GPMSP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : MS
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-PMS-POLICY.

          03 DB2-PMS-ISSUE-DATE               PIC X(10).
          03 DB2-PMS-EXPIRY-DATE              PIC X(10).
          03 DB2-PMS-LASTCHANGED              PIC X(26).
          03 DB2-PMS-BROKERID                 PIC 9(10).
          03 DB2-PMS-BROKERSREF               PIC X(10).
          03 DB2-PMS-PAYMENT                  PIC 9(6).
          03 DB2-PMS-CLASS-CODE               PIC X(4).
          03 DB2-PMS-TERRITORY-CODE           PIC X(3).
          03 DB2-PMS-EXPOSURE-BASIS           PIC X(1).
          03 DB2-PMS-EXPOSURE-AMOUNT          PIC 9(9).
          03 DB2-PMS-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-PMS-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-PMS-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-PMS-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-PMS-PREMISES-COUNT           PIC 9(3).
          03 DB2-PMS-EXPERIENCE-MOD           PIC 9(1)V9(3).
