******************************************************************
*  COPYBOOK  : GPMTP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : MT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-PMT-POLICY.

          03 DB2-PMT-ISSUE-DATE               PIC X(10).
          03 DB2-PMT-EXPIRY-DATE              PIC X(10).
          03 DB2-PMT-LASTCHANGED              PIC X(26).
          03 DB2-PMT-BROKERID                 PIC 9(10).
          03 DB2-PMT-BROKERSREF               PIC X(10).
          03 DB2-PMT-PAYMENT                  PIC 9(6).
          03 DB2-PMT-CLASS-CODE               PIC X(4).
          03 DB2-PMT-TERRITORY-CODE           PIC X(3).
          03 DB2-PMT-EXPOSURE-BASIS           PIC X(1).
          03 DB2-PMT-EXPOSURE-AMOUNT          PIC 9(9).
          03 DB2-PMT-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-PMT-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-PMT-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-PMT-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-PMT-PREMISES-COUNT           PIC 9(3).
          03 DB2-PMT-EXPERIENCE-MOD           PIC 9(1)V9(3).
