******************************************************************
*  COPYBOOK  : GPNEC001
*  KIND      : COMMAREA
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : NE
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-PNE-REQUEST-ID        PIC X(6).
     03 CA-PNE-RETURN-CODE       PIC 9(2).
     03 CA-PNE-POLICY-NUM        PIC 9(10).
     03 CA-PNE-CUSTOMER-NUM      PIC 9(10).

          03 CA-PNE-ISSUE-DATE                PIC X(10).
          03 CA-PNE-EXPIRY-DATE               PIC X(10).
          03 CA-PNE-LASTCHANGED               PIC X(26).
          03 CA-PNE-BROKERID                  PIC 9(10).
          03 CA-PNE-BROKERSREF                PIC X(10).
          03 CA-PNE-PAYMENT                   PIC 9(6).
          03 CA-PNE-CLASS-CODE                PIC X(4).
          03 CA-PNE-TERRITORY-CODE            PIC X(3).
          03 CA-PNE-EXPOSURE-BASIS            PIC X(1).
          03 CA-PNE-EXPOSURE-AMOUNT           PIC 9(9).
          03 CA-PNE-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-PNE-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-PNE-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-PNE-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-PNE-PREMISES-COUNT            PIC 9(3).
          03 CA-PNE-EXPERIENCE-MOD            PIC 9(1)V9(3).
