******************************************************************
*  COPYBOOK  : GPNHC001
*  KIND      : COMMAREA
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : NH
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-PNH-REQUEST-ID        PIC X(6).
     03 CA-PNH-RETURN-CODE       PIC 9(2).
     03 CA-PNH-POLICY-NUM        PIC 9(10).
     03 CA-PNH-CUSTOMER-NUM      PIC 9(10).

          03 CA-PNH-ISSUE-DATE                PIC X(10).
          03 CA-PNH-EXPIRY-DATE               PIC X(10).
          03 CA-PNH-LASTCHANGED               PIC X(26).
          03 CA-PNH-BROKERID                  PIC 9(10).
          03 CA-PNH-BROKERSREF                PIC X(10).
          03 CA-PNH-PAYMENT                   PIC 9(6).
          03 CA-PNH-CLASS-CODE                PIC X(4).
          03 CA-PNH-TERRITORY-CODE            PIC X(3).
          03 CA-PNH-EXPOSURE-BASIS            PIC X(1).
          03 CA-PNH-EXPOSURE-AMOUNT           PIC 9(9).
          03 CA-PNH-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-PNH-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-PNH-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-PNH-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-PNH-PREMISES-COUNT            PIC 9(3).
          03 CA-PNH-EXPERIENCE-MOD            PIC 9(1)V9(3).
