******************************************************************
*  COPYBOOK  : GPNHP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : NH
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-PNH-POLICY.

          03 DB2-PNH-ISSUE-DATE               PIC X(10).
          03 DB2-PNH-EXPIRY-DATE              PIC X(10).
          03 DB2-PNH-LASTCHANGED              PIC X(26).
          03 DB2-PNH-BROKERID                 PIC 9(10).
          03 DB2-PNH-BROKERSREF               PIC X(10).
          03 DB2-PNH-PAYMENT                  PIC 9(6).
          03 DB2-PNH-CLASS-CODE               PIC X(4).
          03 DB2-PNH-TERRITORY-CODE           PIC X(3).
          03 DB2-PNH-EXPOSURE-BASIS           PIC X(1).
          03 DB2-PNH-EXPOSURE-AMOUNT          PIC 9(9).
          03 DB2-PNH-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-PNH-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-PNH-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-PNH-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-PNH-PREMISES-COUNT           PIC 9(3).
          03 DB2-PNH-EXPERIENCE-MOD           PIC 9(1)V9(3).
