******************************************************************
*  COPYBOOK  : GPNJC001
*  KIND      : COMMAREA
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : NJ
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-PNJ-REQUEST-ID        PIC X(6).
     03 CA-PNJ-RETURN-CODE       PIC 9(2).
     03 CA-PNJ-POLICY-NUM        PIC 9(10).
     03 CA-PNJ-CUSTOMER-NUM      PIC 9(10).

          03 CA-PNJ-ISSUE-DATE                PIC X(10).
          03 CA-PNJ-EXPIRY-DATE               PIC X(10).
          03 CA-PNJ-LASTCHANGED               PIC X(26).
          03 CA-PNJ-BROKERID                  PIC 9(10).
          03 CA-PNJ-BROKERSREF                PIC X(10).
          03 CA-PNJ-PAYMENT                   PIC 9(6).
          03 CA-PNJ-CLASS-CODE                PIC X(4).
          03 CA-PNJ-TERRITORY-CODE            PIC X(3).
          03 CA-PNJ-EXPOSURE-BASIS            PIC X(1).
          03 CA-PNJ-EXPOSURE-AMOUNT           PIC 9(9).
          03 CA-PNJ-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-PNJ-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-PNJ-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-PNJ-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-PNJ-PREMISES-COUNT            PIC 9(3).
          03 CA-PNJ-EXPERIENCE-MOD            PIC 9(1)V9(3).
