******************************************************************
*  COPYBOOK  : GPNVC001
*  KIND      : COMMAREA
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : NV
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-PNV-REQUEST-ID        PIC X(6).
     03 CA-PNV-RETURN-CODE       PIC 9(2).
     03 CA-PNV-POLICY-NUM        PIC 9(10).
     03 CA-PNV-CUSTOMER-NUM      PIC 9(10).

          03 CA-PNV-ISSUE-DATE                PIC X(10).
          03 CA-PNV-EXPIRY-DATE               PIC X(10).
          03 CA-PNV-LASTCHANGED               PIC X(26).
          03 CA-PNV-BROKERID                  PIC 9(10).
          03 CA-PNV-BROKERSREF                PIC X(10).
          03 CA-PNV-PAYMENT                   PIC 9(6).
          03 CA-PNV-CLASS-CODE                PIC X(4).
          03 CA-PNV-TERRITORY-CODE            PIC X(3).
          03 CA-PNV-EXPOSURE-BASIS            PIC X(1).
          03 CA-PNV-EXPOSURE-AMOUNT           PIC 9(9).
          03 CA-PNV-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-PNV-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-PNV-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-PNV-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-PNV-PREMISES-COUNT            PIC 9(3).
          03 CA-PNV-EXPERIENCE-MOD            PIC 9(1)V9(3).
