******************************************************************
*  COPYBOOK  : GPOHP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : OH
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-POH-POLICY.

          03 DB2-POH-ISSUE-DATE               PIC X(10).
          03 DB2-POH-EXPIRY-DATE              PIC X(10).
          03 DB2-POH-LASTCHANGED              PIC X(26).
          03 DB2-POH-BROKERID                 PIC 9(10).
          03 DB2-POH-BROKERSREF               PIC X(10).
          03 DB2-POH-PAYMENT                  PIC 9(6).
          03 DB2-POH-CLASS-CODE               PIC X(4).
          03 DB2-POH-TERRITORY-CODE           PIC X(3).
          03 DB2-POH-EXPOSURE-BASIS           PIC X(1).
          03 DB2-POH-EXPOSURE-AMOUNT          PIC 9(9).
          03 DB2-POH-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-POH-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-POH-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-POH-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-POH-PREMISES-COUNT           PIC 9(3).
          03 DB2-POH-EXPERIENCE-MOD           PIC 9(1)V9(3).
