******************************************************************
*  COPYBOOK  : GPOKP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : OK
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-POK-POLICY.

          03 DB2-POK-ISSUE-DATE               PIC X(10).
          03 DB2-POK-EXPIRY-DATE              PIC X(10).
          03 DB2-POK-LASTCHANGED              PIC X(26).
          03 DB2-POK-BROKERID                 PIC 9(10).
          03 DB2-POK-BROKERSREF               PIC X(10).
          03 DB2-POK-PAYMENT                  PIC 9(6).
          03 DB2-POK-CLASS-CODE               PIC X(4).
          03 DB2-POK-TERRITORY-CODE           PIC X(3).
          03 DB2-POK-EXPOSURE-BASIS           PIC X(1).
          03 DB2-POK-EXPOSURE-AMOUNT          PIC 9(9).
          03 DB2-POK-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-POK-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-POK-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-POK-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-POK-PREMISES-COUNT           PIC 9(3).
          03 DB2-POK-EXPERIENCE-MOD           PIC 9(1)V9(3).
