******************************************************************
*  COPYBOOK  : GPORP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : OR
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-POR-POLICY.

          03 DB2-POR-ISSUE-DATE               PIC X(10).
          03 DB2-POR-EXPIRY-DATE              PIC X(10).
          03 DB2-POR-LASTCHANGED              PIC X(26).
          03 DB2-POR-BROKERID                 PIC 9(10).
          03 DB2-POR-BROKERSREF               PIC X(10).
          03 DB2-POR-PAYMENT                  PIC 9(6).
          03 DB2-POR-CLASS-CODE               PIC X(4).
          03 DB2-POR-TERRITORY-CODE           PIC X(3).
          03 DB2-POR-EXPOSURE-BASIS           PIC X(1).
          03 DB2-POR-EXPOSURE-AMOUNT          PIC 9(9).
          03 DB2-POR-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-POR-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-POR-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-POR-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-POR-PREMISES-COUNT           PIC 9(3).
          03 DB2-POR-EXPERIENCE-MOD           PIC 9(1)V9(3).
