******************************************************************
*  COPYBOOK  : GPPAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : PA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-PPA-POLICY.

          03 DB2-PPA-ISSUE-DATE               PIC X(10).
          03 DB2-PPA-EXPIRY-DATE              PIC X(10).
          03 DB2-PPA-LASTCHANGED              PIC X(26).
          03 DB2-PPA-BROKERID                 PIC 9(10).
          03 DB2-PPA-BROKERSREF               PIC X(10).
          03 DB2-PPA-PAYMENT                  PIC 9(6).
          03 DB2-PPA-CLASS-CODE               PIC X(4).
          03 DB2-PPA-TERRITORY-CODE           PIC X(3).
          03 DB2-PPA-EXPOSURE-BASIS           PIC X(1).
          03 DB2-PPA-EXPOSURE-AMOUNT          PIC 9(9).
          03 DB2-PPA-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-PPA-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-PPA-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-PPA-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-PPA-PREMISES-COUNT           PIC 9(3).
          03 DB2-PPA-EXPERIENCE-MOD           PIC 9(1)V9(3).
