******************************************************************
*  COPYBOOK  : GPSCP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : SC
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-PSC-POLICY.

          03 DB2-PSC-ISSUE-DATE               PIC X(10).
          03 DB2-PSC-EXPIRY-DATE              PIC X(10).
          03 DB2-PSC-LASTCHANGED              PIC X(26).
          03 DB2-PSC-BROKERID                 PIC 9(10).
          03 DB2-PSC-BROKERSREF               PIC X(10).
          03 DB2-PSC-PAYMENT                  PIC 9(6).
          03 DB2-PSC-CLASS-CODE               PIC X(4).
          03 DB2-PSC-TERRITORY-CODE           PIC X(3).
          03 DB2-PSC-EXPOSURE-BASIS           PIC X(1).
          03 DB2-PSC-EXPOSURE-AMOUNT          PIC 9(9).
          03 DB2-PSC-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-PSC-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-PSC-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-PSC-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-PSC-PREMISES-COUNT           PIC 9(3).
          03 DB2-PSC-EXPERIENCE-MOD           PIC 9(1)V9(3).
