******************************************************************
*  COPYBOOK  : GPTXP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : TX
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-PTX-POLICY.

          03 DB2-PTX-ISSUE-DATE               PIC X(10).
          03 DB2-PTX-EXPIRY-DATE              PIC X(10).
          03 DB2-PTX-LASTCHANGED              PIC X(26).
          03 DB2-PTX-BROKERID                 PIC 9(10).
          03 DB2-PTX-BROKERSREF               PIC X(10).
          03 DB2-PTX-PAYMENT                  PIC 9(6).
          03 DB2-PTX-CLASS-CODE               PIC X(4).
          03 DB2-PTX-TERRITORY-CODE           PIC X(3).
          03 DB2-PTX-EXPOSURE-BASIS           PIC X(1).
          03 DB2-PTX-EXPOSURE-AMOUNT          PIC 9(9).
          03 DB2-PTX-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-PTX-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-PTX-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-PTX-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-PTX-PREMISES-COUNT           PIC 9(3).
          03 DB2-PTX-EXPERIENCE-MOD           PIC 9(1)V9(3).
