******************************************************************
*  COPYBOOK  : GPUTC001
*  KIND      : COMMAREA
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : UT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-PUT-REQUEST-ID        PIC X(6).
     03 CA-PUT-RETURN-CODE       PIC 9(2).
     03 CA-PUT-POLICY-NUM        PIC 9(10).
     03 CA-PUT-CUSTOMER-NUM      PIC 9(10).

          03 CA-PUT-ISSUE-DATE                PIC X(10).
          03 CA-PUT-EXPIRY-DATE               PIC X(10).
          03 CA-PUT-LASTCHANGED               PIC X(26).
          03 CA-PUT-BROKERID                  PIC 9(10).
          03 CA-PUT-BROKERSREF                PIC X(10).
          03 CA-PUT-PAYMENT                   PIC 9(6).
          03 CA-PUT-CLASS-CODE                PIC X(4).
          03 CA-PUT-TERRITORY-CODE            PIC X(3).
          03 CA-PUT-EXPOSURE-BASIS            PIC X(1).
          03 CA-PUT-EXPOSURE-AMOUNT           PIC 9(9).
          03 CA-PUT-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-PUT-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-PUT-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-PUT-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-PUT-PREMISES-COUNT            PIC 9(3).
          03 CA-PUT-EXPERIENCE-MOD            PIC 9(1)V9(3).
