******************************************************************
*  COPYBOOK  : GPUTP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : UT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-PUT-POLICY.

          03 DB2-PUT-ISSUE-DATE               PIC X(10).
          03 DB2-PUT-EXPIRY-DATE              PIC X(10).
          03 DB2-PUT-LASTCHANGED              PIC X(26).
          03 DB2-PUT-BROKERID                 PIC 9(10).
          03 DB2-PUT-BROKERSREF               PIC X(10).
          03 DB2-PUT-PAYMENT                  PIC 9(6).
          03 DB2-PUT-CLASS-CODE               PIC X(4).
          03 DB2-PUT-TERRITORY-CODE           PIC X(3).
          03 DB2-PUT-EXPOSURE-BASIS           PIC X(1).
          03 DB2-PUT-EXPOSURE-AMOUNT          PIC 9(9).
          03 DB2-PUT-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-PUT-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-PUT-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-PUT-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-PUT-PREMISES-COUNT           PIC 9(3).
          03 DB2-PUT-EXPERIENCE-MOD           PIC 9(1)V9(3).
