******************************************************************
*  COPYBOOK  : GPWAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : WA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-PWA-POLICY.

          03 DB2-PWA-ISSUE-DATE               PIC X(10).
          03 DB2-PWA-EXPIRY-DATE              PIC X(10).
          03 DB2-PWA-LASTCHANGED              PIC X(26).
          03 DB2-PWA-BROKERID                 PIC 9(10).
          03 DB2-PWA-BROKERSREF               PIC X(10).
          03 DB2-PWA-PAYMENT                  PIC 9(6).
          03 DB2-PWA-CLASS-CODE               PIC X(4).
          03 DB2-PWA-TERRITORY-CODE           PIC X(3).
          03 DB2-PWA-EXPOSURE-BASIS           PIC X(1).
          03 DB2-PWA-EXPOSURE-AMOUNT          PIC 9(9).
          03 DB2-PWA-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-PWA-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-PWA-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-PWA-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-PWA-PREMISES-COUNT           PIC 9(3).
          03 DB2-PWA-EXPERIENCE-MOD           PIC 9(1)V9(3).
