******************************************************************
*  COPYBOOK  : GPWIC001
*  KIND      : COMMAREA
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : WI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-PWI-REQUEST-ID        PIC X(6).
     03 CA-PWI-RETURN-CODE       PIC 9(2).
     03 CA-PWI-POLICY-NUM        PIC 9(10).
     03 CA-PWI-CUSTOMER-NUM      PIC 9(10).

          03 CA-PWI-ISSUE-DATE                PIC X(10).
          03 CA-PWI-EXPIRY-DATE               PIC X(10).
          03 CA-PWI-LASTCHANGED               PIC X(26).
          03 CA-PWI-BROKERID                  PIC 9(10).
          03 CA-PWI-BROKERSREF                PIC X(10).
          03 CA-PWI-PAYMENT                   PIC 9(6).
          03 CA-PWI-CLASS-CODE                PIC X(4).
          03 CA-PWI-TERRITORY-CODE            PIC X(3).
          03 CA-PWI-EXPOSURE-BASIS            PIC X(1).
          03 CA-PWI-EXPOSURE-AMOUNT           PIC 9(9).
          03 CA-PWI-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-PWI-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-PWI-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-PWI-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-PWI-PREMISES-COUNT            PIC 9(3).
          03 CA-PWI-EXPERIENCE-MOD            PIC 9(1)V9(3).
