******************************************************************
*  COPYBOOK  : GPWYC001
*  KIND      : COMMAREA
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : WY
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-PWY-REQUEST-ID        PIC X(6).
     03 CA-PWY-RETURN-CODE       PIC 9(2).
     03 CA-PWY-POLICY-NUM        PIC 9(10).
     03 CA-PWY-CUSTOMER-NUM      PIC 9(10).

          03 CA-PWY-ISSUE-DATE                PIC X(10).
          03 CA-PWY-EXPIRY-DATE               PIC X(10).
          03 CA-PWY-LASTCHANGED               PIC X(26).
          03 CA-PWY-BROKERID                  PIC 9(10).
          03 CA-PWY-BROKERSREF                PIC X(10).
          03 CA-PWY-PAYMENT                   PIC 9(6).
          03 CA-PWY-CLASS-CODE                PIC X(4).
          03 CA-PWY-TERRITORY-CODE            PIC X(3).
          03 CA-PWY-EXPOSURE-BASIS            PIC X(1).
          03 CA-PWY-EXPOSURE-AMOUNT           PIC 9(9).
          03 CA-PWY-BASE-RATE                 PIC 9(4)V9(4).
          03 CA-PWY-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-PWY-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-PWY-DEDUCTIBLE-AMOUNT         PIC 9(7).
          03 CA-PWY-PREMISES-COUNT            PIC 9(3).
          03 CA-PWY-EXPERIENCE-MOD            PIC 9(1)V9(3).
