******************************************************************
*  COPYBOOK  : GPWYP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Premises and Operations Liability (PR)
*  STATE     : WY
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-PWY-POLICY.

          03 DB2-PWY-ISSUE-DATE               PIC X(10).
          03 DB2-PWY-EXPIRY-DATE              PIC X(10).
          03 DB2-PWY-LASTCHANGED              PIC X(26).
          03 DB2-PWY-BROKERID                 PIC 9(10).
          03 DB2-PWY-BROKERSREF               PIC X(10).
          03 DB2-PWY-PAYMENT                  PIC 9(6).
          03 DB2-PWY-CLASS-CODE               PIC X(4).
          03 DB2-PWY-TERRITORY-CODE           PIC X(3).
          03 DB2-PWY-EXPOSURE-BASIS           PIC X(1).
          03 DB2-PWY-EXPOSURE-AMOUNT          PIC 9(9).
          03 DB2-PWY-BASE-RATE                PIC 9(4)V9(4).
          03 DB2-PWY-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-PWY-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-PWY-DEDUCTIBLE-AMOUNT        PIC 9(7).
          03 DB2-PWY-PREMISES-COUNT           PIC 9(3).
          03 DB2-PWY-EXPERIENCE-MOD           PIC 9(1)V9(3).
