******************************************************************
*  PROGRAM   : GQCAAV01
*  LAYER     : VSAM ACCESS (Write File against KQCAPOL)
*  OPERATION : ADD
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : CA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGAPVS01.cbl (github.com/cicsdev/cics-genapp).
******************************************************************
 IDENTIFICATION DIVISION.
 PROGRAM-ID. GQCAAV01.
 ENVIRONMENT DIVISION.
 CONFIGURATION SECTION.
 DATA DIVISION.
 WORKING-STORAGE SECTION.

 01  WS-RESP                     PIC S9(8) COMP.
 01  WS-RESP2                    PIC S9(8) COMP.

 01  WF-POLICY-INFO.
     03  WF-POLICY-KEY.
         05  WF-CUSTOMER-NUM     PIC X(10).
         05  WF-POLICY-NUM       PIC X(10).
     03  WF-POLICY-DATA          PIC X(44).

 77  EYECATCHER                  PIC X(16) VALUE 'Program GQCAAV01'.

 LINKAGE SECTION.
 01  DFHCOMMAREA.
     COPY GQCAC001.

 PROCEDURE DIVISION.
 MAINLINE SECTION.
     MOVE CA-POLICY-NUM   TO WF-POLICY-NUM.
     MOVE CA-CUSTOMER-NUM TO WF-CUSTOMER-NUM.

       EXEC CICS WRITE FILE('KQCAPOL')
                 FROM(WF-POLICY-INFO)
                 LENGTH(64)
                 RIDFLD(WF-POLICY-KEY)
                 KEYLENGTH(20)
                 RESP(WS-RESP)
       END-EXEC.
    IF WS-RESP NOT = DFHRESP(NORMAL)
      MOVE EIBRESP2 TO WS-RESP2
      MOVE '80' TO CA-RETURN-CODE
      EXEC CICS RETURN END-EXEC
    END-IF.

MAINLINE-EXIT.
    EXIT.
    GOBACK.
