******************************************************************
*  COPYBOOK  : GQALP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : AL
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-QAL-POLICY.

          03 DB2-QAL-ISSUE-DATE               PIC X(10).
          03 DB2-QAL-EXPIRY-DATE              PIC X(10).
          03 DB2-QAL-LASTCHANGED              PIC X(26).
          03 DB2-QAL-BROKERID                 PIC 9(10).
          03 DB2-QAL-BROKERSREF               PIC X(10).
          03 DB2-QAL-PAYMENT                  PIC 9(6).
          03 DB2-QAL-LIQUOR-SALES-PCT         PIC 9(3)V9(2).
          03 DB2-QAL-LIQUOR-RECEIPTS-AMT      PIC 9(9).
          03 DB2-QAL-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-QAL-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-QAL-BASE-RATE                PIC 9(4)V9(4).
