******************************************************************
*  COPYBOOK  : GQAZP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : AZ
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-QAZ-POLICY.

          03 DB2-QAZ-ISSUE-DATE               PIC X(10).
          03 DB2-QAZ-EXPIRY-DATE              PIC X(10).
          03 DB2-QAZ-LASTCHANGED              PIC X(26).
          03 DB2-QAZ-BROKERID                 PIC 9(10).
          03 DB2-QAZ-BROKERSREF               PIC X(10).
          03 DB2-QAZ-PAYMENT                  PIC 9(6).
          03 DB2-QAZ-LIQUOR-SALES-PCT         PIC 9(3)V9(2).
          03 DB2-QAZ-LIQUOR-RECEIPTS-AMT      PIC 9(9).
          03 DB2-QAZ-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-QAZ-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-QAZ-BASE-RATE                PIC 9(4)V9(4).
