******************************************************************
*  COPYBOOK  : GQCAC001
*  KIND      : COMMAREA
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : CA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-QCA-REQUEST-ID        PIC X(6).
     03 CA-QCA-RETURN-CODE       PIC 9(2).
     03 CA-QCA-POLICY-NUM        PIC 9(10).
     03 CA-QCA-CUSTOMER-NUM      PIC 9(10).

          03 CA-QCA-ISSUE-DATE                PIC X(10).
          03 CA-QCA-EXPIRY-DATE               PIC X(10).
          03 CA-QCA-LASTCHANGED               PIC X(26).
          03 CA-QCA-BROKERID                  PIC 9(10).
          03 CA-QCA-BROKERSREF                PIC X(10).
          03 CA-QCA-PAYMENT                   PIC 9(6).
          03 CA-QCA-LIQUOR-SALES-PCT          PIC 9(3)V9(2).
          03 CA-QCA-LIQUOR-RECEIPTS-AMT       PIC 9(9).
          03 CA-QCA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-QCA-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-QCA-BASE-RATE                 PIC 9(4)V9(4).
