******************************************************************
*  COPYBOOK  : GQCOC001
*  KIND      : COMMAREA
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : CO
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-QCO-REQUEST-ID        PIC X(6).
     03 CA-QCO-RETURN-CODE       PIC 9(2).
     03 CA-QCO-POLICY-NUM        PIC 9(10).
     03 CA-QCO-CUSTOMER-NUM      PIC 9(10).

          03 CA-QCO-ISSUE-DATE                PIC X(10).
          03 CA-QCO-EXPIRY-DATE               PIC X(10).
          03 CA-QCO-LASTCHANGED               PIC X(26).
          03 CA-QCO-BROKERID                  PIC 9(10).
          03 CA-QCO-BROKERSREF                PIC X(10).
          03 CA-QCO-PAYMENT                   PIC 9(6).
          03 CA-QCO-LIQUOR-SALES-PCT          PIC 9(3)V9(2).
          03 CA-QCO-LIQUOR-RECEIPTS-AMT       PIC 9(9).
          03 CA-QCO-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-QCO-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-QCO-BASE-RATE                 PIC 9(4)V9(4).
