******************************************************************
*  COPYBOOK  : GQCTC001
*  KIND      : COMMAREA
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : CT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-QCT-REQUEST-ID        PIC X(6).
     03 CA-QCT-RETURN-CODE       PIC 9(2).
     03 CA-QCT-POLICY-NUM        PIC 9(10).
     03 CA-QCT-CUSTOMER-NUM      PIC 9(10).

          03 CA-QCT-ISSUE-DATE                PIC X(10).
          03 CA-QCT-EXPIRY-DATE               PIC X(10).
          03 CA-QCT-LASTCHANGED               PIC X(26).
          03 CA-QCT-BROKERID                  PIC 9(10).
          03 CA-QCT-BROKERSREF                PIC X(10).
          03 CA-QCT-PAYMENT                   PIC 9(6).
          03 CA-QCT-LIQUOR-SALES-PCT          PIC 9(3)V9(2).
          03 CA-QCT-LIQUOR-RECEIPTS-AMT       PIC 9(9).
          03 CA-QCT-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-QCT-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-QCT-BASE-RATE                 PIC 9(4)V9(4).
