******************************************************************
*  COPYBOOK  : GQGAC001
*  KIND      : COMMAREA
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : GA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-QGA-REQUEST-ID        PIC X(6).
     03 CA-QGA-RETURN-CODE       PIC 9(2).
     03 CA-QGA-POLICY-NUM        PIC 9(10).
     03 CA-QGA-CUSTOMER-NUM      PIC 9(10).

          03 CA-QGA-ISSUE-DATE                PIC X(10).
          03 CA-QGA-EXPIRY-DATE               PIC X(10).
          03 CA-QGA-LASTCHANGED               PIC X(26).
          03 CA-QGA-BROKERID                  PIC 9(10).
          03 CA-QGA-BROKERSREF                PIC X(10).
          03 CA-QGA-PAYMENT                   PIC 9(6).
          03 CA-QGA-LIQUOR-SALES-PCT          PIC 9(3)V9(2).
          03 CA-QGA-LIQUOR-RECEIPTS-AMT       PIC 9(9).
          03 CA-QGA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-QGA-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-QGA-BASE-RATE                 PIC 9(4)V9(4).
