******************************************************************
*  COPYBOOK  : GQIAC001
*  KIND      : COMMAREA
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : IA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-QIA-REQUEST-ID        PIC X(6).
     03 CA-QIA-RETURN-CODE       PIC 9(2).
     03 CA-QIA-POLICY-NUM        PIC 9(10).
     03 CA-QIA-CUSTOMER-NUM      PIC 9(10).

          03 CA-QIA-ISSUE-DATE                PIC X(10).
          03 CA-QIA-EXPIRY-DATE               PIC X(10).
          03 CA-QIA-LASTCHANGED               PIC X(26).
          03 CA-QIA-BROKERID                  PIC 9(10).
          03 CA-QIA-BROKERSREF                PIC X(10).
          03 CA-QIA-PAYMENT                   PIC 9(6).
          03 CA-QIA-LIQUOR-SALES-PCT          PIC 9(3)V9(2).
          03 CA-QIA-LIQUOR-RECEIPTS-AMT       PIC 9(9).
          03 CA-QIA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-QIA-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-QIA-BASE-RATE                 PIC 9(4)V9(4).
