******************************************************************
*  COPYBOOK  : GQIDP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : ID
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-QID-POLICY.

          03 DB2-QID-ISSUE-DATE               PIC X(10).
          03 DB2-QID-EXPIRY-DATE              PIC X(10).
          03 DB2-QID-LASTCHANGED              PIC X(26).
          03 DB2-QID-BROKERID                 PIC 9(10).
          03 DB2-QID-BROKERSREF               PIC X(10).
          03 DB2-QID-PAYMENT                  PIC 9(6).
          03 DB2-QID-LIQUOR-SALES-PCT         PIC 9(3)V9(2).
          03 DB2-QID-LIQUOR-RECEIPTS-AMT      PIC 9(9).
          03 DB2-QID-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-QID-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-QID-BASE-RATE                PIC 9(4)V9(4).
