******************************************************************
*  COPYBOOK  : GQINC001
*  KIND      : COMMAREA
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : IN
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-QIN-REQUEST-ID        PIC X(6).
     03 CA-QIN-RETURN-CODE       PIC 9(2).
     03 CA-QIN-POLICY-NUM        PIC 9(10).
     03 CA-QIN-CUSTOMER-NUM      PIC 9(10).

          03 CA-QIN-ISSUE-DATE                PIC X(10).
          03 CA-QIN-EXPIRY-DATE               PIC X(10).
          03 CA-QIN-LASTCHANGED               PIC X(26).
          03 CA-QIN-BROKERID                  PIC 9(10).
          03 CA-QIN-BROKERSREF                PIC X(10).
          03 CA-QIN-PAYMENT                   PIC 9(6).
          03 CA-QIN-LIQUOR-SALES-PCT          PIC 9(3)V9(2).
          03 CA-QIN-LIQUOR-RECEIPTS-AMT       PIC 9(9).
          03 CA-QIN-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-QIN-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-QIN-BASE-RATE                 PIC 9(4)V9(4).
