******************************************************************
*  COPYBOOK  : GQKYC001
*  KIND      : COMMAREA
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : KY
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-QKY-REQUEST-ID        PIC X(6).
     03 CA-QKY-RETURN-CODE       PIC 9(2).
     03 CA-QKY-POLICY-NUM        PIC 9(10).
     03 CA-QKY-CUSTOMER-NUM      PIC 9(10).

          03 CA-QKY-ISSUE-DATE                PIC X(10).
          03 CA-QKY-EXPIRY-DATE               PIC X(10).
          03 CA-QKY-LASTCHANGED               PIC X(26).
          03 CA-QKY-BROKERID                  PIC 9(10).
          03 CA-QKY-BROKERSREF                PIC X(10).
          03 CA-QKY-PAYMENT                   PIC 9(6).
          03 CA-QKY-LIQUOR-SALES-PCT          PIC 9(3)V9(2).
          03 CA-QKY-LIQUOR-RECEIPTS-AMT       PIC 9(9).
          03 CA-QKY-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-QKY-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-QKY-BASE-RATE                 PIC 9(4)V9(4).
