******************************************************************
*  COPYBOOK  : GQMAC001
*  KIND      : COMMAREA
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : MA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-QMA-REQUEST-ID        PIC X(6).
     03 CA-QMA-RETURN-CODE       PIC 9(2).
     03 CA-QMA-POLICY-NUM        PIC 9(10).
     03 CA-QMA-CUSTOMER-NUM      PIC 9(10).

          03 CA-QMA-ISSUE-DATE                PIC X(10).
          03 CA-QMA-EXPIRY-DATE               PIC X(10).
          03 CA-QMA-LASTCHANGED               PIC X(26).
          03 CA-QMA-BROKERID                  PIC 9(10).
          03 CA-QMA-BROKERSREF                PIC X(10).
          03 CA-QMA-PAYMENT                   PIC 9(6).
          03 CA-QMA-LIQUOR-SALES-PCT          PIC 9(3)V9(2).
          03 CA-QMA-LIQUOR-RECEIPTS-AMT       PIC 9(9).
          03 CA-QMA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-QMA-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-QMA-BASE-RATE                 PIC 9(4)V9(4).
