******************************************************************
*  COPYBOOK  : GQMDP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : MD
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-QMD-POLICY.

          03 DB2-QMD-ISSUE-DATE               PIC X(10).
          03 DB2-QMD-EXPIRY-DATE              PIC X(10).
          03 DB2-QMD-LASTCHANGED              PIC X(26).
          03 DB2-QMD-BROKERID                 PIC 9(10).
          03 DB2-QMD-BROKERSREF               PIC X(10).
          03 DB2-QMD-PAYMENT                  PIC 9(6).
          03 DB2-QMD-LIQUOR-SALES-PCT         PIC 9(3)V9(2).
          03 DB2-QMD-LIQUOR-RECEIPTS-AMT      PIC 9(9).
          03 DB2-QMD-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-QMD-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-QMD-BASE-RATE                PIC 9(4)V9(4).
