******************************************************************
*  COPYBOOK  : GQMEC001
*  KIND      : COMMAREA
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : ME
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-QME-REQUEST-ID        PIC X(6).
     03 CA-QME-RETURN-CODE       PIC 9(2).
     03 CA-QME-POLICY-NUM        PIC 9(10).
     03 CA-QME-CUSTOMER-NUM      PIC 9(10).

          03 CA-QME-ISSUE-DATE                PIC X(10).
          03 CA-QME-EXPIRY-DATE               PIC X(10).
          03 CA-QME-LASTCHANGED               PIC X(26).
          03 CA-QME-BROKERID                  PIC 9(10).
          03 CA-QME-BROKERSREF                PIC X(10).
          03 CA-QME-PAYMENT                   PIC 9(6).
          03 CA-QME-LIQUOR-SALES-PCT          PIC 9(3)V9(2).
          03 CA-QME-LIQUOR-RECEIPTS-AMT       PIC 9(9).
          03 CA-QME-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-QME-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-QME-BASE-RATE                 PIC 9(4)V9(4).
