******************************************************************
*  COPYBOOK  : GQMOC001
*  KIND      : COMMAREA
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : MO
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-QMO-REQUEST-ID        PIC X(6).
     03 CA-QMO-RETURN-CODE       PIC 9(2).
     03 CA-QMO-POLICY-NUM        PIC 9(10).
     03 CA-QMO-CUSTOMER-NUM      PIC 9(10).

          03 CA-QMO-ISSUE-DATE                PIC X(10).
          03 CA-QMO-EXPIRY-DATE               PIC X(10).
          03 CA-QMO-LASTCHANGED               PIC X(26).
          03 CA-QMO-BROKERID                  PIC 9(10).
          03 CA-QMO-BROKERSREF                PIC X(10).
          03 CA-QMO-PAYMENT                   PIC 9(6).
          03 CA-QMO-LIQUOR-SALES-PCT          PIC 9(3)V9(2).
          03 CA-QMO-LIQUOR-RECEIPTS-AMT       PIC 9(9).
          03 CA-QMO-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-QMO-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-QMO-BASE-RATE                 PIC 9(4)V9(4).
