******************************************************************
*  COPYBOOK  : GQMSC001
*  KIND      : COMMAREA
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : MS
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-QMS-REQUEST-ID        PIC X(6).
     03 CA-QMS-RETURN-CODE       PIC 9(2).
     03 CA-QMS-POLICY-NUM        PIC 9(10).
     03 CA-QMS-CUSTOMER-NUM      PIC 9(10).

          03 CA-QMS-ISSUE-DATE                PIC X(10).
          03 CA-QMS-EXPIRY-DATE               PIC X(10).
          03 CA-QMS-LASTCHANGED               PIC X(26).
          03 CA-QMS-BROKERID                  PIC 9(10).
          03 CA-QMS-BROKERSREF                PIC X(10).
          03 CA-QMS-PAYMENT                   PIC 9(6).
          03 CA-QMS-LIQUOR-SALES-PCT          PIC 9(3)V9(2).
          03 CA-QMS-LIQUOR-RECEIPTS-AMT       PIC 9(9).
          03 CA-QMS-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-QMS-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-QMS-BASE-RATE                 PIC 9(4)V9(4).
