******************************************************************
*  COPYBOOK  : GQMSP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : MS
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-QMS-POLICY.

          03 DB2-QMS-ISSUE-DATE               PIC X(10).
          03 DB2-QMS-EXPIRY-DATE              PIC X(10).
          03 DB2-QMS-LASTCHANGED              PIC X(26).
          03 DB2-QMS-BROKERID                 PIC 9(10).
          03 DB2-QMS-BROKERSREF               PIC X(10).
          03 DB2-QMS-PAYMENT                  PIC 9(6).
          03 DB2-QMS-LIQUOR-SALES-PCT         PIC 9(3)V9(2).
          03 DB2-QMS-LIQUOR-RECEIPTS-AMT      PIC 9(9).
          03 DB2-QMS-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-QMS-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-QMS-BASE-RATE                PIC 9(4)V9(4).
