******************************************************************
*  COPYBOOK  : GQNHP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : NH
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-QNH-POLICY.

          03 DB2-QNH-ISSUE-DATE               PIC X(10).
          03 DB2-QNH-EXPIRY-DATE              PIC X(10).
          03 DB2-QNH-LASTCHANGED              PIC X(26).
          03 DB2-QNH-BROKERID                 PIC 9(10).
          03 DB2-QNH-BROKERSREF               PIC X(10).
          03 DB2-QNH-PAYMENT                  PIC 9(6).
          03 DB2-QNH-LIQUOR-SALES-PCT         PIC 9(3)V9(2).
          03 DB2-QNH-LIQUOR-RECEIPTS-AMT      PIC 9(9).
          03 DB2-QNH-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-QNH-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-QNH-BASE-RATE                PIC 9(4)V9(4).
