******************************************************************
*  COPYBOOK  : GQNMP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : NM
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-QNM-POLICY.

          03 DB2-QNM-ISSUE-DATE               PIC X(10).
          03 DB2-QNM-EXPIRY-DATE              PIC X(10).
          03 DB2-QNM-LASTCHANGED              PIC X(26).
          03 DB2-QNM-BROKERID                 PIC 9(10).
          03 DB2-QNM-BROKERSREF               PIC X(10).
          03 DB2-QNM-PAYMENT                  PIC 9(6).
          03 DB2-QNM-LIQUOR-SALES-PCT         PIC 9(3)V9(2).
          03 DB2-QNM-LIQUOR-RECEIPTS-AMT      PIC 9(9).
          03 DB2-QNM-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-QNM-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-QNM-BASE-RATE                PIC 9(4)V9(4).
