******************************************************************
*  COPYBOOK  : GQOHP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : OH
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-QOH-POLICY.

          03 DB2-QOH-ISSUE-DATE               PIC X(10).
          03 DB2-QOH-EXPIRY-DATE              PIC X(10).
          03 DB2-QOH-LASTCHANGED              PIC X(26).
          03 DB2-QOH-BROKERID                 PIC 9(10).
          03 DB2-QOH-BROKERSREF               PIC X(10).
          03 DB2-QOH-PAYMENT                  PIC 9(6).
          03 DB2-QOH-LIQUOR-SALES-PCT         PIC 9(3)V9(2).
          03 DB2-QOH-LIQUOR-RECEIPTS-AMT      PIC 9(9).
          03 DB2-QOH-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-QOH-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-QOH-BASE-RATE                PIC 9(4)V9(4).
