******************************************************************
*  COPYBOOK  : GQOHC001
*  KIND      : COMMAREA
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : OH
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-QOH-REQUEST-ID        PIC X(6).
     03 CA-QOH-RETURN-CODE       PIC 9(2).
     03 CA-QOH-POLICY-NUM        PIC 9(10).
     03 CA-QOH-CUSTOMER-NUM      PIC 9(10).

          03 CA-QOH-ISSUE-DATE                PIC X(10).
          03 CA-QOH-EXPIRY-DATE               PIC X(10).
          03 CA-QOH-LASTCHANGED               PIC X(26).
          03 CA-QOH-BROKERID                  PIC 9(10).
          03 CA-QOH-BROKERSREF                PIC X(10).
          03 CA-QOH-PAYMENT                   PIC 9(6).
          03 CA-QOH-LIQUOR-SALES-PCT          PIC 9(3)V9(2).
          03 CA-QOH-LIQUOR-RECEIPTS-AMT       PIC 9(9).
          03 CA-QOH-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-QOH-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-QOH-BASE-RATE                 PIC 9(4)V9(4).
