******************************************************************
*  COPYBOOK  : GQOKC001
*  KIND      : COMMAREA
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : OK
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-QOK-REQUEST-ID        PIC X(6).
     03 CA-QOK-RETURN-CODE       PIC 9(2).
     03 CA-QOK-POLICY-NUM        PIC 9(10).
     03 CA-QOK-CUSTOMER-NUM      PIC 9(10).

          03 CA-QOK-ISSUE-DATE                PIC X(10).
          03 CA-QOK-EXPIRY-DATE               PIC X(10).
          03 CA-QOK-LASTCHANGED               PIC X(26).
          03 CA-QOK-BROKERID                  PIC 9(10).
          03 CA-QOK-BROKERSREF                PIC X(10).
          03 CA-QOK-PAYMENT                   PIC 9(6).
          03 CA-QOK-LIQUOR-SALES-PCT          PIC 9(3)V9(2).
          03 CA-QOK-LIQUOR-RECEIPTS-AMT       PIC 9(9).
          03 CA-QOK-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-QOK-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-QOK-BASE-RATE                 PIC 9(4)V9(4).
