******************************************************************
*  COPYBOOK  : GQOKP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : OK
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-QOK-POLICY.

          03 DB2-QOK-ISSUE-DATE               PIC X(10).
          03 DB2-QOK-EXPIRY-DATE              PIC X(10).
          03 DB2-QOK-LASTCHANGED              PIC X(26).
          03 DB2-QOK-BROKERID                 PIC 9(10).
          03 DB2-QOK-BROKERSREF               PIC X(10).
          03 DB2-QOK-PAYMENT                  PIC 9(6).
          03 DB2-QOK-LIQUOR-SALES-PCT         PIC 9(3)V9(2).
          03 DB2-QOK-LIQUOR-RECEIPTS-AMT      PIC 9(9).
          03 DB2-QOK-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-QOK-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-QOK-BASE-RATE                PIC 9(4)V9(4).
