******************************************************************
*  COPYBOOK  : GQORC001
*  KIND      : COMMAREA
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : OR
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-QOR-REQUEST-ID        PIC X(6).
     03 CA-QOR-RETURN-CODE       PIC 9(2).
     03 CA-QOR-POLICY-NUM        PIC 9(10).
     03 CA-QOR-CUSTOMER-NUM      PIC 9(10).

          03 CA-QOR-ISSUE-DATE                PIC X(10).
          03 CA-QOR-EXPIRY-DATE               PIC X(10).
          03 CA-QOR-LASTCHANGED               PIC X(26).
          03 CA-QOR-BROKERID                  PIC 9(10).
          03 CA-QOR-BROKERSREF                PIC X(10).
          03 CA-QOR-PAYMENT                   PIC 9(6).
          03 CA-QOR-LIQUOR-SALES-PCT          PIC 9(3)V9(2).
          03 CA-QOR-LIQUOR-RECEIPTS-AMT       PIC 9(9).
          03 CA-QOR-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-QOR-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-QOR-BASE-RATE                 PIC 9(4)V9(4).
