******************************************************************
*  COPYBOOK  : GQRIC001
*  KIND      : COMMAREA
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : RI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-QRI-REQUEST-ID        PIC X(6).
     03 CA-QRI-RETURN-CODE       PIC 9(2).
     03 CA-QRI-POLICY-NUM        PIC 9(10).
     03 CA-QRI-CUSTOMER-NUM      PIC 9(10).

          03 CA-QRI-ISSUE-DATE                PIC X(10).
          03 CA-QRI-EXPIRY-DATE               PIC X(10).
          03 CA-QRI-LASTCHANGED               PIC X(26).
          03 CA-QRI-BROKERID                  PIC 9(10).
          03 CA-QRI-BROKERSREF                PIC X(10).
          03 CA-QRI-PAYMENT                   PIC 9(6).
          03 CA-QRI-LIQUOR-SALES-PCT          PIC 9(3)V9(2).
          03 CA-QRI-LIQUOR-RECEIPTS-AMT       PIC 9(9).
          03 CA-QRI-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-QRI-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-QRI-BASE-RATE                 PIC 9(4)V9(4).
