******************************************************************
*  COPYBOOK  : GQSCC001
*  KIND      : COMMAREA
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : SC
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-QSC-REQUEST-ID        PIC X(6).
     03 CA-QSC-RETURN-CODE       PIC 9(2).
     03 CA-QSC-POLICY-NUM        PIC 9(10).
     03 CA-QSC-CUSTOMER-NUM      PIC 9(10).

          03 CA-QSC-ISSUE-DATE                PIC X(10).
          03 CA-QSC-EXPIRY-DATE               PIC X(10).
          03 CA-QSC-LASTCHANGED               PIC X(26).
          03 CA-QSC-BROKERID                  PIC 9(10).
          03 CA-QSC-BROKERSREF                PIC X(10).
          03 CA-QSC-PAYMENT                   PIC 9(6).
          03 CA-QSC-LIQUOR-SALES-PCT          PIC 9(3)V9(2).
          03 CA-QSC-LIQUOR-RECEIPTS-AMT       PIC 9(9).
          03 CA-QSC-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-QSC-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-QSC-BASE-RATE                 PIC 9(4)V9(4).
