******************************************************************
*  COPYBOOK  : GQSDC001
*  KIND      : COMMAREA
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : SD
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-QSD-REQUEST-ID        PIC X(6).
     03 CA-QSD-RETURN-CODE       PIC 9(2).
     03 CA-QSD-POLICY-NUM        PIC 9(10).
     03 CA-QSD-CUSTOMER-NUM      PIC 9(10).

          03 CA-QSD-ISSUE-DATE                PIC X(10).
          03 CA-QSD-EXPIRY-DATE               PIC X(10).
          03 CA-QSD-LASTCHANGED               PIC X(26).
          03 CA-QSD-BROKERID                  PIC 9(10).
          03 CA-QSD-BROKERSREF                PIC X(10).
          03 CA-QSD-PAYMENT                   PIC 9(6).
          03 CA-QSD-LIQUOR-SALES-PCT          PIC 9(3)V9(2).
          03 CA-QSD-LIQUOR-RECEIPTS-AMT       PIC 9(9).
          03 CA-QSD-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-QSD-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-QSD-BASE-RATE                 PIC 9(4)V9(4).
