******************************************************************
*  COPYBOOK  : GQVAC001
*  KIND      : COMMAREA
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : VA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-QVA-REQUEST-ID        PIC X(6).
     03 CA-QVA-RETURN-CODE       PIC 9(2).
     03 CA-QVA-POLICY-NUM        PIC 9(10).
     03 CA-QVA-CUSTOMER-NUM      PIC 9(10).

          03 CA-QVA-ISSUE-DATE                PIC X(10).
          03 CA-QVA-EXPIRY-DATE               PIC X(10).
          03 CA-QVA-LASTCHANGED               PIC X(26).
          03 CA-QVA-BROKERID                  PIC 9(10).
          03 CA-QVA-BROKERSREF                PIC X(10).
          03 CA-QVA-PAYMENT                   PIC 9(6).
          03 CA-QVA-LIQUOR-SALES-PCT          PIC 9(3)V9(2).
          03 CA-QVA-LIQUOR-RECEIPTS-AMT       PIC 9(9).
          03 CA-QVA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-QVA-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-QVA-BASE-RATE                 PIC 9(4)V9(4).
