******************************************************************
*  COPYBOOK  : GQVTC001
*  KIND      : COMMAREA
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : VT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-QVT-REQUEST-ID        PIC X(6).
     03 CA-QVT-RETURN-CODE       PIC 9(2).
     03 CA-QVT-POLICY-NUM        PIC 9(10).
     03 CA-QVT-CUSTOMER-NUM      PIC 9(10).

          03 CA-QVT-ISSUE-DATE                PIC X(10).
          03 CA-QVT-EXPIRY-DATE               PIC X(10).
          03 CA-QVT-LASTCHANGED               PIC X(26).
          03 CA-QVT-BROKERID                  PIC 9(10).
          03 CA-QVT-BROKERSREF                PIC X(10).
          03 CA-QVT-PAYMENT                   PIC 9(6).
          03 CA-QVT-LIQUOR-SALES-PCT          PIC 9(3)V9(2).
          03 CA-QVT-LIQUOR-RECEIPTS-AMT       PIC 9(9).
          03 CA-QVT-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-QVT-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-QVT-BASE-RATE                 PIC 9(4)V9(4).
