******************************************************************
*  COPYBOOK  : GQWAC001
*  KIND      : COMMAREA
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : WA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-QWA-REQUEST-ID        PIC X(6).
     03 CA-QWA-RETURN-CODE       PIC 9(2).
     03 CA-QWA-POLICY-NUM        PIC 9(10).
     03 CA-QWA-CUSTOMER-NUM      PIC 9(10).

          03 CA-QWA-ISSUE-DATE                PIC X(10).
          03 CA-QWA-EXPIRY-DATE               PIC X(10).
          03 CA-QWA-LASTCHANGED               PIC X(26).
          03 CA-QWA-BROKERID                  PIC 9(10).
          03 CA-QWA-BROKERSREF                PIC X(10).
          03 CA-QWA-PAYMENT                   PIC 9(6).
          03 CA-QWA-LIQUOR-SALES-PCT          PIC 9(3)V9(2).
          03 CA-QWA-LIQUOR-RECEIPTS-AMT       PIC 9(9).
          03 CA-QWA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-QWA-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-QWA-BASE-RATE                 PIC 9(4)V9(4).
