******************************************************************
*  COPYBOOK  : GQWIC001
*  KIND      : COMMAREA
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : WI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-QWI-REQUEST-ID        PIC X(6).
     03 CA-QWI-RETURN-CODE       PIC 9(2).
     03 CA-QWI-POLICY-NUM        PIC 9(10).
     03 CA-QWI-CUSTOMER-NUM      PIC 9(10).

          03 CA-QWI-ISSUE-DATE                PIC X(10).
          03 CA-QWI-EXPIRY-DATE               PIC X(10).
          03 CA-QWI-LASTCHANGED               PIC X(26).
          03 CA-QWI-BROKERID                  PIC 9(10).
          03 CA-QWI-BROKERSREF                PIC X(10).
          03 CA-QWI-PAYMENT                   PIC 9(6).
          03 CA-QWI-LIQUOR-SALES-PCT          PIC 9(3)V9(2).
          03 CA-QWI-LIQUOR-RECEIPTS-AMT       PIC 9(9).
          03 CA-QWI-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-QWI-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-QWI-BASE-RATE                 PIC 9(4)V9(4).
