******************************************************************
*  COPYBOOK  : GQWIP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Liquor Liability (LQ)
*  STATE     : WI
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-QWI-POLICY.

          03 DB2-QWI-ISSUE-DATE               PIC X(10).
          03 DB2-QWI-EXPIRY-DATE              PIC X(10).
          03 DB2-QWI-LASTCHANGED              PIC X(26).
          03 DB2-QWI-BROKERID                 PIC 9(10).
          03 DB2-QWI-BROKERSREF               PIC X(10).
          03 DB2-QWI-PAYMENT                  PIC 9(6).
          03 DB2-QWI-LIQUOR-SALES-PCT         PIC 9(3)V9(2).
          03 DB2-QWI-LIQUOR-RECEIPTS-AMT      PIC 9(9).
          03 DB2-QWI-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-QWI-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-QWI-BASE-RATE                PIC 9(4)V9(4).
