******************************************************************
*  COPYBOOK  : GBAKP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : AK
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-BAK-POLICY.

          03 DB2-BAK-ISSUE-DATE               PIC X(10).
          03 DB2-BAK-EXPIRY-DATE              PIC X(10).
          03 DB2-BAK-LASTCHANGED              PIC X(26).
          03 DB2-BAK-BROKERID                 PIC 9(10).
          03 DB2-BAK-BROKERSREF               PIC X(10).
          03 DB2-BAK-PAYMENT                  PIC 9(6).
          03 DB2-BAK-EMPLOYEE-COUNT           PIC 9(6).
          03 DB2-BAK-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-BAK-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-BAK-RETRO-DATE               PIC X(10).
          03 DB2-BAK-BASE-RATE                PIC 9(4)V9(4).
