******************************************************************
*  COPYBOOK  : GBCAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : CA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-BCA-POLICY.

          03 DB2-BCA-ISSUE-DATE               PIC X(10).
          03 DB2-BCA-EXPIRY-DATE              PIC X(10).
          03 DB2-BCA-LASTCHANGED              PIC X(26).
          03 DB2-BCA-BROKERID                 PIC 9(10).
          03 DB2-BCA-BROKERSREF               PIC X(10).
          03 DB2-BCA-PAYMENT                  PIC 9(6).
          03 DB2-BCA-EMPLOYEE-COUNT           PIC 9(6).
          03 DB2-BCA-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-BCA-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-BCA-RETRO-DATE               PIC X(10).
          03 DB2-BCA-BASE-RATE                PIC 9(4)V9(4).
