******************************************************************
*  COPYBOOK  : GBDEC001
*  KIND      : COMMAREA
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : DE
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-BDE-REQUEST-ID        PIC X(6).
     03 CA-BDE-RETURN-CODE       PIC 9(2).
     03 CA-BDE-POLICY-NUM        PIC 9(10).
     03 CA-BDE-CUSTOMER-NUM      PIC 9(10).

          03 CA-BDE-ISSUE-DATE                PIC X(10).
          03 CA-BDE-EXPIRY-DATE               PIC X(10).
          03 CA-BDE-LASTCHANGED               PIC X(26).
          03 CA-BDE-BROKERID                  PIC 9(10).
          03 CA-BDE-BROKERSREF                PIC X(10).
          03 CA-BDE-PAYMENT                   PIC 9(6).
          03 CA-BDE-EMPLOYEE-COUNT            PIC 9(6).
          03 CA-BDE-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-BDE-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-BDE-RETRO-DATE                PIC X(10).
          03 CA-BDE-BASE-RATE                 PIC 9(4)V9(4).
