******************************************************************
*  COPYBOOK  : GBFLC001
*  KIND      : COMMAREA
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : FL
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-BFL-REQUEST-ID        PIC X(6).
     03 CA-BFL-RETURN-CODE       PIC 9(2).
     03 CA-BFL-POLICY-NUM        PIC 9(10).
     03 CA-BFL-CUSTOMER-NUM      PIC 9(10).

          03 CA-BFL-ISSUE-DATE                PIC X(10).
          03 CA-BFL-EXPIRY-DATE               PIC X(10).
          03 CA-BFL-LASTCHANGED               PIC X(26).
          03 CA-BFL-BROKERID                  PIC 9(10).
          03 CA-BFL-BROKERSREF                PIC X(10).
          03 CA-BFL-PAYMENT                   PIC 9(6).
          03 CA-BFL-EMPLOYEE-COUNT            PIC 9(6).
          03 CA-BFL-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-BFL-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-BFL-RETRO-DATE                PIC X(10).
          03 CA-BFL-BASE-RATE                 PIC 9(4)V9(4).
