******************************************************************
*  COPYBOOK  : GBGAC001
*  KIND      : COMMAREA
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : GA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-BGA-REQUEST-ID        PIC X(6).
     03 CA-BGA-RETURN-CODE       PIC 9(2).
     03 CA-BGA-POLICY-NUM        PIC 9(10).
     03 CA-BGA-CUSTOMER-NUM      PIC 9(10).

          03 CA-BGA-ISSUE-DATE                PIC X(10).
          03 CA-BGA-EXPIRY-DATE               PIC X(10).
          03 CA-BGA-LASTCHANGED               PIC X(26).
          03 CA-BGA-BROKERID                  PIC 9(10).
          03 CA-BGA-BROKERSREF                PIC X(10).
          03 CA-BGA-PAYMENT                   PIC 9(6).
          03 CA-BGA-EMPLOYEE-COUNT            PIC 9(6).
          03 CA-BGA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-BGA-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-BGA-RETRO-DATE                PIC X(10).
          03 CA-BGA-BASE-RATE                 PIC 9(4)V9(4).
