******************************************************************
*  COPYBOOK  : GBIAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : IA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-BIA-POLICY.

          03 DB2-BIA-ISSUE-DATE               PIC X(10).
          03 DB2-BIA-EXPIRY-DATE              PIC X(10).
          03 DB2-BIA-LASTCHANGED              PIC X(26).
          03 DB2-BIA-BROKERID                 PIC 9(10).
          03 DB2-BIA-BROKERSREF               PIC X(10).
          03 DB2-BIA-PAYMENT                  PIC 9(6).
          03 DB2-BIA-EMPLOYEE-COUNT           PIC 9(6).
          03 DB2-BIA-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-BIA-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-BIA-RETRO-DATE               PIC X(10).
          03 DB2-BIA-BASE-RATE                PIC 9(4)V9(4).
