******************************************************************
*  COPYBOOK  : GBILC001
*  KIND      : COMMAREA
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : IL
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-BIL-REQUEST-ID        PIC X(6).
     03 CA-BIL-RETURN-CODE       PIC 9(2).
     03 CA-BIL-POLICY-NUM        PIC 9(10).
     03 CA-BIL-CUSTOMER-NUM      PIC 9(10).

          03 CA-BIL-ISSUE-DATE                PIC X(10).
          03 CA-BIL-EXPIRY-DATE               PIC X(10).
          03 CA-BIL-LASTCHANGED               PIC X(26).
          03 CA-BIL-BROKERID                  PIC 9(10).
          03 CA-BIL-BROKERSREF                PIC X(10).
          03 CA-BIL-PAYMENT                   PIC 9(6).
          03 CA-BIL-EMPLOYEE-COUNT            PIC 9(6).
          03 CA-BIL-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-BIL-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-BIL-RETRO-DATE                PIC X(10).
          03 CA-BIL-BASE-RATE                 PIC 9(4)V9(4).
