******************************************************************
*  COPYBOOK  : GBINC001
*  KIND      : COMMAREA
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : IN
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-BIN-REQUEST-ID        PIC X(6).
     03 CA-BIN-RETURN-CODE       PIC 9(2).
     03 CA-BIN-POLICY-NUM        PIC 9(10).
     03 CA-BIN-CUSTOMER-NUM      PIC 9(10).

          03 CA-BIN-ISSUE-DATE                PIC X(10).
          03 CA-BIN-EXPIRY-DATE               PIC X(10).
          03 CA-BIN-LASTCHANGED               PIC X(26).
          03 CA-BIN-BROKERID                  PIC 9(10).
          03 CA-BIN-BROKERSREF                PIC X(10).
          03 CA-BIN-PAYMENT                   PIC 9(6).
          03 CA-BIN-EMPLOYEE-COUNT            PIC 9(6).
          03 CA-BIN-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-BIN-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-BIN-RETRO-DATE                PIC X(10).
          03 CA-BIN-BASE-RATE                 PIC 9(4)V9(4).
