******************************************************************
*  COPYBOOK  : GBLAC001
*  KIND      : COMMAREA
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : LA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-BLA-REQUEST-ID        PIC X(6).
     03 CA-BLA-RETURN-CODE       PIC 9(2).
     03 CA-BLA-POLICY-NUM        PIC 9(10).
     03 CA-BLA-CUSTOMER-NUM      PIC 9(10).

          03 CA-BLA-ISSUE-DATE                PIC X(10).
          03 CA-BLA-EXPIRY-DATE               PIC X(10).
          03 CA-BLA-LASTCHANGED               PIC X(26).
          03 CA-BLA-BROKERID                  PIC 9(10).
          03 CA-BLA-BROKERSREF                PIC X(10).
          03 CA-BLA-PAYMENT                   PIC 9(6).
          03 CA-BLA-EMPLOYEE-COUNT            PIC 9(6).
          03 CA-BLA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-BLA-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-BLA-RETRO-DATE                PIC X(10).
          03 CA-BLA-BASE-RATE                 PIC 9(4)V9(4).
