******************************************************************
*  COPYBOOK  : GBMAC001
*  KIND      : COMMAREA
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : MA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-BMA-REQUEST-ID        PIC X(6).
     03 CA-BMA-RETURN-CODE       PIC 9(2).
     03 CA-BMA-POLICY-NUM        PIC 9(10).
     03 CA-BMA-CUSTOMER-NUM      PIC 9(10).

          03 CA-BMA-ISSUE-DATE                PIC X(10).
          03 CA-BMA-EXPIRY-DATE               PIC X(10).
          03 CA-BMA-LASTCHANGED               PIC X(26).
          03 CA-BMA-BROKERID                  PIC 9(10).
          03 CA-BMA-BROKERSREF                PIC X(10).
          03 CA-BMA-PAYMENT                   PIC 9(6).
          03 CA-BMA-EMPLOYEE-COUNT            PIC 9(6).
          03 CA-BMA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-BMA-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-BMA-RETRO-DATE                PIC X(10).
          03 CA-BMA-BASE-RATE                 PIC 9(4)V9(4).
