******************************************************************
*  COPYBOOK  : GBMDP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : MD
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-BMD-POLICY.

          03 DB2-BMD-ISSUE-DATE               PIC X(10).
          03 DB2-BMD-EXPIRY-DATE              PIC X(10).
          03 DB2-BMD-LASTCHANGED              PIC X(26).
          03 DB2-BMD-BROKERID                 PIC 9(10).
          03 DB2-BMD-BROKERSREF               PIC X(10).
          03 DB2-BMD-PAYMENT                  PIC 9(6).
          03 DB2-BMD-EMPLOYEE-COUNT           PIC 9(6).
          03 DB2-BMD-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-BMD-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-BMD-RETRO-DATE               PIC X(10).
          03 DB2-BMD-BASE-RATE                PIC 9(4)V9(4).
