******************************************************************
*  COPYBOOK  : GBMDC001
*  KIND      : COMMAREA
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : MD
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-BMD-REQUEST-ID        PIC X(6).
     03 CA-BMD-RETURN-CODE       PIC 9(2).
     03 CA-BMD-POLICY-NUM        PIC 9(10).
     03 CA-BMD-CUSTOMER-NUM      PIC 9(10).

          03 CA-BMD-ISSUE-DATE                PIC X(10).
          03 CA-BMD-EXPIRY-DATE               PIC X(10).
          03 CA-BMD-LASTCHANGED               PIC X(26).
          03 CA-BMD-BROKERID                  PIC 9(10).
          03 CA-BMD-BROKERSREF                PIC X(10).
          03 CA-BMD-PAYMENT                   PIC 9(6).
          03 CA-BMD-EMPLOYEE-COUNT            PIC 9(6).
          03 CA-BMD-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-BMD-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-BMD-RETRO-DATE                PIC X(10).
          03 CA-BMD-BASE-RATE                 PIC 9(4)V9(4).
