******************************************************************
*  COPYBOOK  : GBMNP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : MN
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-BMN-POLICY.

          03 DB2-BMN-ISSUE-DATE               PIC X(10).
          03 DB2-BMN-EXPIRY-DATE              PIC X(10).
          03 DB2-BMN-LASTCHANGED              PIC X(26).
          03 DB2-BMN-BROKERID                 PIC 9(10).
          03 DB2-BMN-BROKERSREF               PIC X(10).
          03 DB2-BMN-PAYMENT                  PIC 9(6).
          03 DB2-BMN-EMPLOYEE-COUNT           PIC 9(6).
          03 DB2-BMN-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-BMN-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-BMN-RETRO-DATE               PIC X(10).
          03 DB2-BMN-BASE-RATE                PIC 9(4)V9(4).
