******************************************************************
*  COPYBOOK  : GBMSP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : MS
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-BMS-POLICY.

          03 DB2-BMS-ISSUE-DATE               PIC X(10).
          03 DB2-BMS-EXPIRY-DATE              PIC X(10).
          03 DB2-BMS-LASTCHANGED              PIC X(26).
          03 DB2-BMS-BROKERID                 PIC 9(10).
          03 DB2-BMS-BROKERSREF               PIC X(10).
          03 DB2-BMS-PAYMENT                  PIC 9(6).
          03 DB2-BMS-EMPLOYEE-COUNT           PIC 9(6).
          03 DB2-BMS-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-BMS-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-BMS-RETRO-DATE               PIC X(10).
          03 DB2-BMS-BASE-RATE                PIC 9(4)V9(4).
