******************************************************************
*  COPYBOOK  : GBNEP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : NE
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-BNE-POLICY.

          03 DB2-BNE-ISSUE-DATE               PIC X(10).
          03 DB2-BNE-EXPIRY-DATE              PIC X(10).
          03 DB2-BNE-LASTCHANGED              PIC X(26).
          03 DB2-BNE-BROKERID                 PIC 9(10).
          03 DB2-BNE-BROKERSREF               PIC X(10).
          03 DB2-BNE-PAYMENT                  PIC 9(6).
          03 DB2-BNE-EMPLOYEE-COUNT           PIC 9(6).
          03 DB2-BNE-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-BNE-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-BNE-RETRO-DATE               PIC X(10).
          03 DB2-BNE-BASE-RATE                PIC 9(4)V9(4).
