******************************************************************
*  COPYBOOK  : GBNHP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : NH
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-BNH-POLICY.

          03 DB2-BNH-ISSUE-DATE               PIC X(10).
          03 DB2-BNH-EXPIRY-DATE              PIC X(10).
          03 DB2-BNH-LASTCHANGED              PIC X(26).
          03 DB2-BNH-BROKERID                 PIC 9(10).
          03 DB2-BNH-BROKERSREF               PIC X(10).
          03 DB2-BNH-PAYMENT                  PIC 9(6).
          03 DB2-BNH-EMPLOYEE-COUNT           PIC 9(6).
          03 DB2-BNH-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-BNH-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-BNH-RETRO-DATE               PIC X(10).
          03 DB2-BNH-BASE-RATE                PIC 9(4)V9(4).
