******************************************************************
*  COPYBOOK  : GBNJC001
*  KIND      : COMMAREA
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : NJ
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-BNJ-REQUEST-ID        PIC X(6).
     03 CA-BNJ-RETURN-CODE       PIC 9(2).
     03 CA-BNJ-POLICY-NUM        PIC 9(10).
     03 CA-BNJ-CUSTOMER-NUM      PIC 9(10).

          03 CA-BNJ-ISSUE-DATE                PIC X(10).
          03 CA-BNJ-EXPIRY-DATE               PIC X(10).
          03 CA-BNJ-LASTCHANGED               PIC X(26).
          03 CA-BNJ-BROKERID                  PIC 9(10).
          03 CA-BNJ-BROKERSREF                PIC X(10).
          03 CA-BNJ-PAYMENT                   PIC 9(6).
          03 CA-BNJ-EMPLOYEE-COUNT            PIC 9(6).
          03 CA-BNJ-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-BNJ-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-BNJ-RETRO-DATE                PIC X(10).
          03 CA-BNJ-BASE-RATE                 PIC 9(4)V9(4).
