******************************************************************
*  COPYBOOK  : GBNMC001
*  KIND      : COMMAREA
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : NM
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-BNM-REQUEST-ID        PIC X(6).
     03 CA-BNM-RETURN-CODE       PIC 9(2).
     03 CA-BNM-POLICY-NUM        PIC 9(10).
     03 CA-BNM-CUSTOMER-NUM      PIC 9(10).

          03 CA-BNM-ISSUE-DATE                PIC X(10).
          03 CA-BNM-EXPIRY-DATE               PIC X(10).
          03 CA-BNM-LASTCHANGED               PIC X(26).
          03 CA-BNM-BROKERID                  PIC 9(10).
          03 CA-BNM-BROKERSREF                PIC X(10).
          03 CA-BNM-PAYMENT                   PIC 9(6).
          03 CA-BNM-EMPLOYEE-COUNT            PIC 9(6).
          03 CA-BNM-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-BNM-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-BNM-RETRO-DATE                PIC X(10).
          03 CA-BNM-BASE-RATE                 PIC 9(4)V9(4).
