******************************************************************
*  COPYBOOK  : GBNYP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : NY
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-BNY-POLICY.

          03 DB2-BNY-ISSUE-DATE               PIC X(10).
          03 DB2-BNY-EXPIRY-DATE              PIC X(10).
          03 DB2-BNY-LASTCHANGED              PIC X(26).
          03 DB2-BNY-BROKERID                 PIC 9(10).
          03 DB2-BNY-BROKERSREF               PIC X(10).
          03 DB2-BNY-PAYMENT                  PIC 9(6).
          03 DB2-BNY-EMPLOYEE-COUNT           PIC 9(6).
          03 DB2-BNY-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-BNY-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-BNY-RETRO-DATE               PIC X(10).
          03 DB2-BNY-BASE-RATE                PIC 9(4)V9(4).
