******************************************************************
*  COPYBOOK  : GBOHC001
*  KIND      : COMMAREA
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : OH
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-BOH-REQUEST-ID        PIC X(6).
     03 CA-BOH-RETURN-CODE       PIC 9(2).
     03 CA-BOH-POLICY-NUM        PIC 9(10).
     03 CA-BOH-CUSTOMER-NUM      PIC 9(10).

          03 CA-BOH-ISSUE-DATE                PIC X(10).
          03 CA-BOH-EXPIRY-DATE               PIC X(10).
          03 CA-BOH-LASTCHANGED               PIC X(26).
          03 CA-BOH-BROKERID                  PIC 9(10).
          03 CA-BOH-BROKERSREF                PIC X(10).
          03 CA-BOH-PAYMENT                   PIC 9(6).
          03 CA-BOH-EMPLOYEE-COUNT            PIC 9(6).
          03 CA-BOH-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-BOH-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-BOH-RETRO-DATE                PIC X(10).
          03 CA-BOH-BASE-RATE                 PIC 9(4)V9(4).
