******************************************************************
*  COPYBOOK  : GBOHP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : OH
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-BOH-POLICY.

          03 DB2-BOH-ISSUE-DATE               PIC X(10).
          03 DB2-BOH-EXPIRY-DATE              PIC X(10).
          03 DB2-BOH-LASTCHANGED              PIC X(26).
          03 DB2-BOH-BROKERID                 PIC 9(10).
          03 DB2-BOH-BROKERSREF               PIC X(10).
          03 DB2-BOH-PAYMENT                  PIC 9(6).
          03 DB2-BOH-EMPLOYEE-COUNT           PIC 9(6).
          03 DB2-BOH-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-BOH-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-BOH-RETRO-DATE               PIC X(10).
          03 DB2-BOH-BASE-RATE                PIC 9(4)V9(4).
