******************************************************************
*  COPYBOOK  : GBPAC001
*  KIND      : COMMAREA
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : PA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-BPA-REQUEST-ID        PIC X(6).
     03 CA-BPA-RETURN-CODE       PIC 9(2).
     03 CA-BPA-POLICY-NUM        PIC 9(10).
     03 CA-BPA-CUSTOMER-NUM      PIC 9(10).

          03 CA-BPA-ISSUE-DATE                PIC X(10).
          03 CA-BPA-EXPIRY-DATE               PIC X(10).
          03 CA-BPA-LASTCHANGED               PIC X(26).
          03 CA-BPA-BROKERID                  PIC 9(10).
          03 CA-BPA-BROKERSREF                PIC X(10).
          03 CA-BPA-PAYMENT                   PIC 9(6).
          03 CA-BPA-EMPLOYEE-COUNT            PIC 9(6).
          03 CA-BPA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-BPA-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-BPA-RETRO-DATE                PIC X(10).
          03 CA-BPA-BASE-RATE                 PIC 9(4)V9(4).
