******************************************************************
*  COPYBOOK  : GBSDC001
*  KIND      : COMMAREA
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : SD
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-BSD-REQUEST-ID        PIC X(6).
     03 CA-BSD-RETURN-CODE       PIC 9(2).
     03 CA-BSD-POLICY-NUM        PIC 9(10).
     03 CA-BSD-CUSTOMER-NUM      PIC 9(10).

          03 CA-BSD-ISSUE-DATE                PIC X(10).
          03 CA-BSD-EXPIRY-DATE               PIC X(10).
          03 CA-BSD-LASTCHANGED               PIC X(26).
          03 CA-BSD-BROKERID                  PIC 9(10).
          03 CA-BSD-BROKERSREF                PIC X(10).
          03 CA-BSD-PAYMENT                   PIC 9(6).
          03 CA-BSD-EMPLOYEE-COUNT            PIC 9(6).
          03 CA-BSD-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-BSD-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-BSD-RETRO-DATE                PIC X(10).
          03 CA-BSD-BASE-RATE                 PIC 9(4)V9(4).
