******************************************************************
*  COPYBOOK  : GBVAP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : VA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-BVA-POLICY.

          03 DB2-BVA-ISSUE-DATE               PIC X(10).
          03 DB2-BVA-EXPIRY-DATE              PIC X(10).
          03 DB2-BVA-LASTCHANGED              PIC X(26).
          03 DB2-BVA-BROKERID                 PIC 9(10).
          03 DB2-BVA-BROKERSREF               PIC X(10).
          03 DB2-BVA-PAYMENT                  PIC 9(6).
          03 DB2-BVA-EMPLOYEE-COUNT           PIC 9(6).
          03 DB2-BVA-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-BVA-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-BVA-RETRO-DATE               PIC X(10).
          03 DB2-BVA-BASE-RATE                PIC 9(4)V9(4).
