******************************************************************
*  COPYBOOK  : GBVTC001
*  KIND      : COMMAREA
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : VT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-BVT-REQUEST-ID        PIC X(6).
     03 CA-BVT-RETURN-CODE       PIC 9(2).
     03 CA-BVT-POLICY-NUM        PIC 9(10).
     03 CA-BVT-CUSTOMER-NUM      PIC 9(10).

          03 CA-BVT-ISSUE-DATE                PIC X(10).
          03 CA-BVT-EXPIRY-DATE               PIC X(10).
          03 CA-BVT-LASTCHANGED               PIC X(26).
          03 CA-BVT-BROKERID                  PIC 9(10).
          03 CA-BVT-BROKERSREF                PIC X(10).
          03 CA-BVT-PAYMENT                   PIC 9(6).
          03 CA-BVT-EMPLOYEE-COUNT            PIC 9(6).
          03 CA-BVT-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-BVT-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-BVT-RETRO-DATE                PIC X(10).
          03 CA-BVT-BASE-RATE                 PIC 9(4)V9(4).
