******************************************************************
*  COPYBOOK  : GBVTP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : VT
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-BVT-POLICY.

          03 DB2-BVT-ISSUE-DATE               PIC X(10).
          03 DB2-BVT-EXPIRY-DATE              PIC X(10).
          03 DB2-BVT-LASTCHANGED              PIC X(26).
          03 DB2-BVT-BROKERID                 PIC 9(10).
          03 DB2-BVT-BROKERSREF               PIC X(10).
          03 DB2-BVT-PAYMENT                  PIC 9(6).
          03 DB2-BVT-EMPLOYEE-COUNT           PIC 9(6).
          03 DB2-BVT-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-BVT-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-BVT-RETRO-DATE               PIC X(10).
          03 DB2-BVT-BASE-RATE                PIC 9(4)V9(4).
