******************************************************************
*  COPYBOOK  : GBWAC001
*  KIND      : COMMAREA
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : WA
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGCMAREA copybook (github.com/cicsdev/cics-genapp).
******************************************************************
     03 CA-BWA-REQUEST-ID        PIC X(6).
     03 CA-BWA-RETURN-CODE       PIC 9(2).
     03 CA-BWA-POLICY-NUM        PIC 9(10).
     03 CA-BWA-CUSTOMER-NUM      PIC 9(10).

          03 CA-BWA-ISSUE-DATE                PIC X(10).
          03 CA-BWA-EXPIRY-DATE               PIC X(10).
          03 CA-BWA-LASTCHANGED               PIC X(26).
          03 CA-BWA-BROKERID                  PIC 9(10).
          03 CA-BWA-BROKERSREF                PIC X(10).
          03 CA-BWA-PAYMENT                   PIC 9(6).
          03 CA-BWA-EMPLOYEE-COUNT            PIC 9(6).
          03 CA-BWA-LIMIT-OCCURRENCE          PIC 9(9).
          03 CA-BWA-LIMIT-AGGREGATE           PIC 9(9).
          03 CA-BWA-RETRO-DATE                PIC X(10).
          03 CA-BWA-BASE-RATE                 PIC 9(4)V9(4).
