******************************************************************
*  COPYBOOK  : GBWVP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : WV
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-BWV-POLICY.

          03 DB2-BWV-ISSUE-DATE               PIC X(10).
          03 DB2-BWV-EXPIRY-DATE              PIC X(10).
          03 DB2-BWV-LASTCHANGED              PIC X(26).
          03 DB2-BWV-BROKERID                 PIC 9(10).
          03 DB2-BWV-BROKERSREF               PIC X(10).
          03 DB2-BWV-PAYMENT                  PIC 9(6).
          03 DB2-BWV-EMPLOYEE-COUNT           PIC 9(6).
          03 DB2-BWV-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-BWV-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-BWV-RETRO-DATE               PIC X(10).
          03 DB2-BWV-BASE-RATE                PIC 9(4)V9(4).
