******************************************************************
*  COPYBOOK  : GBWYP001
*  KIND      : POLICY-RECORD (DB2 host-variable layout)
*  COVERAGE  : Employee Benefits Liability (EB)
*  STATE     : WY
*  Generated by generate_synthetic_class.py -- pattern derived from
*  GenApp's LGPOLICY copybook (github.com/cicsdev/cics-genapp).
******************************************************************
 01  DB2-BWY-POLICY.

          03 DB2-BWY-ISSUE-DATE               PIC X(10).
          03 DB2-BWY-EXPIRY-DATE              PIC X(10).
          03 DB2-BWY-LASTCHANGED              PIC X(26).
          03 DB2-BWY-BROKERID                 PIC 9(10).
          03 DB2-BWY-BROKERSREF               PIC X(10).
          03 DB2-BWY-PAYMENT                  PIC 9(6).
          03 DB2-BWY-EMPLOYEE-COUNT           PIC 9(6).
          03 DB2-BWY-LIMIT-OCCURRENCE         PIC 9(9).
          03 DB2-BWY-LIMIT-AGGREGATE          PIC 9(9).
          03 DB2-BWY-RETRO-DATE               PIC X(10).
          03 DB2-BWY-BASE-RATE                PIC 9(4)V9(4).
